Repository phac-nml/irida, pull requests merged in 2018-11, with the labels that each got.

#190 Fix issue with flaky testing on the Project Line List Page
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectLineListPage.java
Labels: UI, bug, test

#56 Contributing guide
  CONTRIBUTING.md
  README.md
  doc/developer/files/eclipse-code-formatter.xml
  doc/developer/files/intellij-code-style-schemes.xml
  doc/developer/getting-started/index.md
  doc/developer/index.html
Labels: documentation

#194 Removing GitLab links
  CHANGELOG.md
  ci/README.md
  doc/administrator/web/building/index.md
  doc/developer/authorization/oauth2.md
  doc/developer/getting-started/index.md
  doc/developer/rest/index.md
  doc/developer/setup/index.md
  doc/developer/tools/pipelines/workflow-description/index.md
  doc/downloads/using-the-virtual-appliance.md
  doc/index.html
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/exceptions/EntityRevisionDeletedException.java
  src/main/webapp/resources/js/pages/analyses/analysis-outputs-table.js
Labels: documentation

#193 Update CartController responses to use proper servlet responses
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/CartController.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/CartControllerIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/CartControllerTest.java
Labels: UI

#204 Cart page empty state
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/CartController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/components/Cart.java
  src/main/resources/i18n/messages_en.properties
  src/main/webapp/configs/entries.js
  src/main/webapp/pages/cart.html
  src/main/webapp/pages/template/main-navigation.html
  src/main/webapp/resources/img/empty-cart.svg
  src/main/webapp/resources/js/apis/cart/cart.js
  src/main/webapp/resources/js/pages/cart/EmptyCart.js
  src/main/webapp/resources/js/pages/cart/index.js
  src/main/webapp/resources/js/redux/sagas/cart.js
  src/main/webapp/resources/sass/app.scss
Labels: UI, feature

#200 Ensure locked sample have an icon and are not editable.
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/agGrid/AgGridColumn.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/LineListController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/dto/UISampleMetadata.java
  src/main/webapp/pages/projects/project_linelist.html
  src/main/webapp/resources/js/pages/projects/linelist/components/Table/Table.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/Table/renderers/IconCellRenderer.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/Table/renderers/index.js
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/Columns/ColumnVisibility.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TableControlPanel.jsx
  src/main/webapp/resources/js/pages/projects/linelist/constants.js
  src/main/webapp/resources/js/pages/projects/linelist/reducers/fields.js
  src/main/webapp/resources/js/pages/projects/linelist/sagas/templates.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectLineListPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/LineListControllerTest.java
Labels: UI
