Repository phac-nml/irida, pull requests merged in 2019-07, with the labels that each got.

#417 Projects Page Refactor
  doc/user/user/project/images/project-name-button.png
  doc/user/user/project/images/project-search.png
  doc/user/user/project/images/projects-list.png
  doc/user/user/project/images/projects-search-outbreak.png
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsRestController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/ProjectModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/ProjectsRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/ProjectsResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/ProjectServiceImpl.java
  src/main/resources/i18n/messages_en.properties
  src/main/webapp/entries.js
  src/main/webapp/package.json
  src/main/webapp/pages/projects/projects.html
  src/main/webapp/pages/template/page.html
  src/main/webapp/resources/js/apis/projects/projects.js
  src/main/webapp/resources/js/components/ant.design/table-renderers.js
  src/main/webapp/resources/js/components/page/PageWrapper.jsx
  src/main/webapp/resources/js/pages/projects/list/ProjectsTable.jsx
  src/main/webapp/resources/js/pages/projects/list/index.js
  src/main/webapp/resources/js/utilities/date-utilities.js
  src/main/webapp/webpack.config.js
  src/main/webapp/wepack.config.prod.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectDeletePageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectsAdminPageViewIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectsControllerTest.java
Labels: UI

#427 Fix lodash security vulnerability
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/resources/js/pages/projects/list/index.js
  src/main/webapp/yarn.lock
Labels: security

#432 Upgraded lodash to v4.17.13 using resolutions in package.json
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: security

#426 Testing and documentation for automated analysis
  CHANGELOG.md
  doc/_includes/tutorials/common/creating-a-project.md
  doc/images/tutorials/common/projects/create-new-project-form.png
  doc/user/user/project/images/project-settings-automated-pipelines.png
  doc/user/user/project/images/project-settings-no-auto-pipelines.png
  doc/user/user/project/images/project-settings-processing.png
  doc/user/user/project/images/project-settings-with-auto-pipeline.png
  doc/user/user/project/index.md
  doc/user/user/samples/index.md
  src/main/webapp/pages/projects/settings/pages/basic.html
  src/main/webapp/pages/projects/templates/remove-analysis-template-modal.html
  src/main/webapp/resources/js/components/pipeline/Pipeline.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/processing/impl/unit/AutomatedAnalysisFileProcessorTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/AbstractIridaUIITChromeDriver.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/cart/CartPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/pipelines/BasicPipelinePage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/pipelines/PipelinesPhylogenomicsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSettingsProcessingPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pipelines/AssemblyPipelinePageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSettingsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/pipelines/PipelineControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/utils/NullReplacementDatasetLoader.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/ProjectsPageIT.xml
Labels: UI, test, tools
