Repository phac-nml/irida, pull requests merged in 2019-01, with the labels that each got.

#239 (Cart) Display samples on dedicated cart page
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/CartController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/components/Cart.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/dto/AddToCartRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/dto/CartSample.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/dto/CartSampleRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
  src/main/webapp/pages/cart.html
  src/main/webapp/pages/index.html
  src/main/webapp/resources/js/apis/cart/cart.js
  src/main/webapp/resources/js/components/SampleDetails/SampleDetails.jsx
  src/main/webapp/resources/js/pages/cart/components/Cart.jsx
  src/main/webapp/resources/js/pages/cart/components/CartEmpty.js
  src/main/webapp/resources/js/pages/cart/components/CartPage.js
  src/main/webapp/resources/js/pages/cart/components/CartSamples.jsx
  src/main/webapp/resources/js/pages/cart/components/SampleDetailsContainer.js
  src/main/webapp/resources/js/pages/cart/index.js
  src/main/webapp/resources/js/pages/cart/reducer.js
  src/main/webapp/resources/js/pages/cart/sagas.js
  src/main/webapp/resources/js/redux/reducers/app.js
  src/main/webapp/resources/js/redux/reducers/cart.js
  src/main/webapp/resources/js/redux/sagas/cart.js
  src/main/webapp/resources/js/redux/sagas/index.js
  src/main/webapp/resources/sass/app.scss
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/CartControllerIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/TestDataFactory.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/CartControllerTest.java
Labels: UI

#248 (Cart) Show sample details
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/dto/SampleDetails.java
  src/main/resources/i18n/messages_en.properties
  src/main/webapp/package.json
  src/main/webapp/pages/cart.html
  src/main/webapp/resources/js/apis/samples/samples.js
  src/main/webapp/resources/js/components/SampleDetails/SampleDetails.jsx
  src/main/webapp/resources/js/components/SampleDetails/index.js
  src/main/webapp/resources/js/components/SampleDetails/reducer.js
  src/main/webapp/resources/js/components/SampleDetails/sagas.js
  src/main/webapp/resources/js/pages/cart/components/Cart.jsx
  src/main/webapp/resources/js/pages/cart/components/CartSamples.jsx
  src/main/webapp/resources/js/pages/cart/components/SampleDetailsContainer.js
  src/main/webapp/resources/js/pages/cart/index.js
  src/main/webapp/resources/js/pages/cart/reducer.js
  src/main/webapp/resources/js/pages/cart/sagas.js
  src/main/webapp/resources/js/redux/reducers/cart.js
  src/main/webapp/resources/js/styles/colours.js
  src/main/webapp/resources/js/styles/index.js
  src/main/webapp/resources/js/styles/spacing.js
  src/main/webapp/yarn.lock
Labels: UI, feature

#234 Update shovill
  CHANGELOG.md
  doc/_includes/administrator/galaxy/pipelines/shovill-0.9.0.md
  doc/_includes/administrator/galaxy/pipelines/shovill-1.0.4.md
  doc/administrator/galaxy/pipelines/assembly-annotation-collection/index.md
  doc/administrator/galaxy/pipelines/assembly-annotation/index.md
  doc/administrator/galaxy/pipelines/sistr/index.md
  doc/administrator/galaxy/pipelines/test/assembly-annotation-collection/assembly-annotation-collection.ga
  doc/administrator/galaxy/pipelines/test/assembly-annotation/assembly-annotation.ga
  doc/administrator/galaxy/pipelines/test/sistr/sistr.ga
  src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/AssemblyAnnotation/0.5/irida_workflow.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/AssemblyAnnotation/0.5/irida_workflow_structure.ga
  src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/AssemblyAnnotation/0.5/messages_en.properties
  src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/AssemblyAnnotationCollection/0.4/irida_workflow.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/AssemblyAnnotationCollection/0.4/irida_workflow_structure.ga
  src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/AssemblyAnnotationCollection/0.4/messages_en.properties
  src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/SISTRTyping/0.3/irida_workflow.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/SISTRTyping/0.3/irida_workflow_structure.ga
Labels: tools

#253 Fixed up info in docs
  doc/administrator/web/config/irida.conf
Labels: documentation

#243 Link to sample page for analysis input files
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java
  src/main/resources/i18n/messages_en.properties
  src/main/webapp/pages/analysis/details/details.html
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisDetailsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectAnalysisPageIT.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAdminView.xml
  src/test/resources/files/sequence-files/03-3333_S1_L001_F2_001.fastq
Labels: UI, enhancement

#255 Fixes issue where selecting all samples after filtering selected all samples
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesController.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
Labels: UI, bug

#254 [Cart] Ability to select a pipeline directly from the cart.
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/CartController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java
  src/main/resources/i18n/messages_en.properties
  src/main/webapp/package.json
  src/main/webapp/pages/cart.html
  src/main/webapp/pages/template/main-navigation.html
  src/main/webapp/resources/js/apis/pipelines/pipelines.js
  src/main/webapp/resources/js/components/SampleDetails/SampleDetails.jsx
  src/main/webapp/resources/js/components/pipeline/Pipeline.jsx
  src/main/webapp/resources/js/components/pipelines/Pipelines.jsx
  src/main/webapp/resources/js/components/pipelines/styles.css
  src/main/webapp/resources/js/pages/cart/components/Cart.jsx
  src/main/webapp/resources/js/pages/cart/components/CartSamples.jsx
  src/main/webapp/resources/js/pages/cart/components/CartTools.jsx
  src/main/webapp/resources/js/styles/break-points.js
  src/main/webapp/resources/js/styles/index.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/CartControllerTest.java
Labels: UI, feature
