Repository phac-nml/irida, pull requests merged in 2019-04, with the labels that each got.

#236 Fastqc to filesystem
  CHANGELOG.md
  UPGRADING.md
  doc/administrator/index.html
  doc/administrator/upgrades/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/database/changesets/FastqcToFilesystem.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/Analysis.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/AnalysisFastQC.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/AnalysisOutputFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/FastqcFileProcessor.java
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/19.04/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/19.04/fastqc-filesystem.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/sql/required-data.sql
  src/main/webapp/pages/samples/sample_files.html
  src/main/webapp/resources/js/pages/analysis/json-preview.js
  src/main/webapp/resources/js/pages/analysis/plaintext-preview.js
  src/test/java/ca/corefacility/bioinformatics/irida/processing/impl/unit/FastqcFileProcessorTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/AnalysisServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/sample/SampleServiceImplTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/repositories/analysis/AnalysisRepositoryIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/sequenceFiles/SequenceFileView.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/SampleServiceImplIT.xml
Labels: UI, back-end

#303 fix-locked-samples-on-project-create
  CHANGELOG.md
  doc/_includes/tutorials/common/creating-a-project.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/ProjectService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/ProjectServiceImpl.java
  src/main/resources/i18n/messages_en.properties
  src/main/webapp/pages/projects/project_new.html
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectsNewPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectsNewPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectsControllerTest.java
Labels: UI, bug

#341 Adding citation to docs
  README.md
  doc/index.html
Labels: documentation

#333 Fix user group removal from project
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/user/group/UserGroup.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/joins/project/UserGroupProjectJoinRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/GroupsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/user/UserGroupServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/user/UserGroupService.java
  src/main/resources/i18n/messages_en.properties
  src/main/webapp/pages/groups/remove-group-modal.html
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/groups/GroupsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/groups/GroupsPage.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/GroupsPageIT.xml
Labels: UI, bug

#356 Import metadata should exclude default fields
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/metadata/ProjectSampleMetadataController.java
  src/main/webapp/pages/projects/project_samples_metadata_upload.html
Labels: UI, bug

#344 Update REST API status code returned when adding files to the wrong type of run
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/samples/RESTSampleSequenceFilesController.java
Labels: REST API

#362 Upgraded TravisCI mariadb version to 10.1
  .travis.yml
  CHANGELOG.md
Labels: developer

#373 MySQL for TravisCI
  .travis.yml
  CHANGELOG.md
Labels: test
