Repository phac-nml/irida, pull requests merged in 2019-05, with the labels that each got.

#372 Fixes issue with creating linelist templates
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/agGrid/AgGridColumn.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/LineListController.java
  src/main/webapp/resources/js/pages/projects/linelist/reducers/fields.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectLineListPageIT.java
Labels: UI, bug

#371 Fixes issue where selecting all samples and adding to cart failed.
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/ProjectCartSample.java
  src/main/webapp/resources/js/pages/projects/samples/project-samples.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
Labels: UI, bug

#378 Fixed changlog link from 1904 to 1905
  CHANGELOG.md
Labels: documentation

#379 Remove datatables-bootstrap3-plugin
  CHANGELOG.md
  src/main/webapp/bower.json
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: UI, bug

#383 Rest project user role
  CHANGELOG.md
  doc/developer/rest/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectUsersController.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/project/ProjectUsersControllerTest.java
Labels: REST API

#387 Remove bootstrap from bower and load through webpack.
  CHANGELOG.md
  src/main/webapp/bower.json
  src/main/webapp/entries.js
  src/main/webapp/package.json
  src/main/webapp/pages/template/base.html
  src/main/webapp/pages/template/page.html
  src/main/webapp/resources/js/vendors.js
  src/main/webapp/yarn.lock
Labels: UI
