Repository phac-nml/irida, pull requests merged in 2019-08, with the labels that each got.

#446 updated chromedriver to 76 to be compatible with travis
  src/main/webapp/package.json
Labels: test

#439 Analysis Output Files all automated submissions
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/analysis/submission/AnalysisSubmissionRepositoryImpl.java
  src/main/webapp/package.json
  src/main/webapp/pages/cart.html
  src/main/webapp/resources/js/apis/pipelines/pipelines.js
  src/main/webapp/resources/js/pages/analyses/analysis-outputs-table.js
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceIT_getAnalysisOutputFileInfo.xml
Labels: tools

#443 Doc/troubleshooting guide
  CHANGELOG.md
  doc/user/administrator/index.md
  doc/user/administrator/troubleshooting/images/assembly-pipeline-default-error.png
  doc/user/administrator/troubleshooting/images/assembly-pipeline-default-galaxy-history-error.png
  doc/user/administrator/troubleshooting/images/assembly-pipeline-default-galaxy-history-id.png
  doc/user/administrator/troubleshooting/images/assembly-pipeline-default-job-details.png
  doc/user/administrator/troubleshooting/images/assembly-pipeline-default-rerun.png
  doc/user/administrator/troubleshooting/images/assembly-pipeline-default-success.png
  doc/user/administrator/troubleshooting/images/assembly-pipeline-default.png
  doc/user/administrator/troubleshooting/images/galaxy-command-line.png
  doc/user/administrator/troubleshooting/images/galaxy-histories-list.png
  doc/user/administrator/troubleshooting/images/galaxy-home.png
  doc/user/administrator/troubleshooting/images/galaxy-job-debug.png
  doc/user/administrator/troubleshooting/images/galaxy-job-id.png
  doc/user/administrator/troubleshooting/images/galaxy-job-information.png
  doc/user/administrator/troubleshooting/images/galaxy-job-information2.png
  doc/user/administrator/troubleshooting/images/galaxy-saved-histories.png
  doc/user/administrator/troubleshooting/images/galaxy-switch-to-history.png
  doc/user/administrator/troubleshooting/images/galaxy-view-history.png
  doc/user/administrator/troubleshooting/images/irida-job-id.png
  doc/user/administrator/troubleshooting/images/job-details-galaxy-history.png
  doc/user/administrator/troubleshooting/images/job-error-details.png
  doc/user/administrator/troubleshooting/images/job-error-nodetails.png
  doc/user/administrator/troubleshooting/images/job-runner-id.png
  doc/user/administrator/troubleshooting/images/jobs-all-error-details.png
  doc/user/administrator/troubleshooting/images/rerun-galaxy-job.png
  doc/user/administrator/troubleshooting/images/sistr-default-pipeline-state.png
  doc/user/administrator/troubleshooting/images/sistr-pipeline-default-completed.png
  doc/user/administrator/troubleshooting/images/sistr-pipeline-default-galaxy-jobinfo.png
  doc/user/administrator/troubleshooting/images/sistr-pipeline-default-shovill-running.png
  doc/user/administrator/troubleshooting/images/snvphyl-pipeline-default-debug.png
  doc/user/administrator/troubleshooting/images/snvphyl-pipeline-default-error.png
  doc/user/administrator/troubleshooting/images/snvphyl-pipeline-default-galaxy-jobid.png
  doc/user/administrator/troubleshooting/images/snvphyl-pipeline-default-history.png
  doc/user/administrator/troubleshooting/images/snvphyl-pipeline-default-jobinfo.png
  doc/user/administrator/troubleshooting/images/snvphyl-pipeline-default-rerun-error.png
  doc/user/administrator/troubleshooting/images/snvphyl-pipeline-default-rerun.png
  doc/user/administrator/troubleshooting/images/snvphyl-pipeline-default.png
  doc/user/administrator/troubleshooting/images/snvphyl-pipeline-no-density-parameters.png
  doc/user/administrator/troubleshooting/images/snvphyl-pipeline-no-density-results.png
  doc/user/administrator/troubleshooting/pipelines/index.md
Labels: documentation

#438 added Exception Handler for Uploading to non UPLOADING sequencing runs
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/exception/ControllerExceptionHandler.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/samples/RESTSampleSequenceFilesController.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/exception/ControllerExceptionHandlerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/samples/SampleSequenceFilesControllerTest.java
Labels: REST API

#418 Spring using user's i18n settings
  CHANGELOG.md
  CONTRIBUTING.md
  doc/administrator/web/config/web.conf
  doc/administrator/web/index.md
  doc/developer/authentication/index.md
  doc/developer/authentication/persona-flow-small.png
  doc/developer/authentication/persona-flow.png
  doc/developer/index.html
  doc/developer/index.md
  doc/developer/interface/i18n/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaWebSecurityConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/config/services/IridaApiServicesConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/config/web/IridaUIWebConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/security/LoginSuccessHandler.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/UsersController.java
  src/main/resources/configuration.properties
  src/main/resources/i18n/messages.properties
  src/main/resources/i18n/messages_fr.properties
  src/main/webapp/pages/template/page.html
  src/main/webapp/pages/user/create.html
  src/main/webapp/pages/user/edit.html
  src/main/webapp/resources/js/pages/sequence-files/run-files.js
  src/main/webapp/resources/js/utilities/date-utilities.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/UsersControllerTest.java
Labels: UI, developer

#420 Analyses Page Refactor
  CHANGELOG.md
  CONTRIBUTING.md
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/specification/AnalysisSubmissionSpecification.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysesFilters.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysesListRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysesListResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysisModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysisStateModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysisTypeModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/AnalysesListingService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/utilities/DateUtilities.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/AnalysisSubmissionService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceImpl.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/.prettierignore
  src/main/webapp/entries.js
  src/main/webapp/package.json
  src/main/webapp/pages/analyses/analyses.html
  src/main/webapp/pages/sequencingRuns/run_files.html
  src/main/webapp/resources/js/apis/analysis/analysis.js
  src/main/webapp/resources/js/components/ant.design/table-renderers.js
  src/main/webapp/resources/js/components/ant.design/table-search-props.js
  src/main/webapp/resources/js/components/page/PageWrapper.jsx
  src/main/webapp/resources/js/contexts/AnalysesContext.js
  src/main/webapp/resources/js/pages/analyses/AnalysesTable.jsx
  src/main/webapp/resources/js/pages/analyses/AnalysisState.jsx
  src/main/webapp/resources/js/pages/analyses/analyses-table.js
  src/main/webapp/resources/js/pages/analyses/index.js
  src/main/webapp/resources/js/pages/projects/list/ProjectsTable.jsx
  src/main/webapp/resources/js/pages/projects/samples/project-samples.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysesUserPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisAdminPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysesUserPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectAnalysisPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysesAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysisControllerDataTablesTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/analysis/submission/AnalysisSubmissionServiceImplIT.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAdminView.xml
Labels: UI
