Repository phac-nml/irida, pull requests merged in 2019-02, with the labels that each got.

#271 Added the calver info to the getting started guide
  CHANGELOG.md
  doc/developer/getting-started/index.md
Labels: documentation

#277 Updated lodash to version 4.17.11 to fix security issue
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: security

#201 added sample instructions for setting up test databases
  doc/administrator/faq/index.md
  doc/developer/getting-started/index.md
Labels: documentation

#279 Analysis submission class heirarchy
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/submission/AbstractAnalysisSubmission.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/submission/AnalysisSubmission.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/submission/AnalysisSubmissionTemplate.java
  src/main/resources/ca/corefacility/bioinformatics/irida/database/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/19.04/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/19.04/analysis-templates.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/sql/required-data.sql
  src/main/webapp/pages/analysis/details/details.html
  src/test/resources/ca/corefacility/bioinformatics/irida/pipeline/results/impl/AnalysisSubmissionSampleProcessorImplIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/pipeline/results/impl/AssemblySampleUpdaterIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/repositories/sample/SampleRepositoryIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/ProjectsPageIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAdminView.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplePagesIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/ProjectServiceImplIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/SampleServiceImplIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/SequencingRunServiceImplIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionCleanupServiceIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceIT_getAnalysisOutputFileInfo.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/web/controller/test/integration/analysis/RESTAnalysisSubmissionControllerIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/web/controller/test/integration/project/RESTProjectAnalysisControllerIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/web/controller/test/integration/sample/SampleSequenceFilesIntegrationTest.xml
Labels: tools

#289 Fix jquery vulnerability
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/resources/js/pages/projects/samples/project-samples.js
  src/main/webapp/resources/js/pages/remote-apis/remote-apis.js
  src/main/webapp/yarn.lock
Labels: security
