Repository phac-nml/irida, pull requests merged in 2019-12, with the labels that each got.

#518 Removed REST Login Controller and removed exceptionhandler for oauth …
  src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaOauthSecurityConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/RESTLoginController.java
Labels: REST API

#539 Fixed url for downloading multiple analysis outputs.
  CHANGELOG.md
  src/main/webapp/resources/js/apis/analysis/analysis.js
Labels: bug

#542 Upgraded spring to 5.2.2
  CHANGELOG.md
  pom.xml
Labels: back-end

#540 Sra docs link broken
  CHANGELOG.md
  doc/administrator/web/index.md
  src/main/resources/i18n/messages.properties
Labels: documentation

#548 Update Line List Page to use new Ag Grid
  src/main/webapp/package.json
  src/main/webapp/pages/analyses/user-analysis-outputs.html
  src/main/webapp/resources/js/components/Tables/AgGridLayout.jsx
  src/main/webapp/resources/js/pages/analyses/analysis-outputs-table.js
  src/main/webapp/resources/js/pages/analysis/tabular-preview.js
  src/main/webapp/resources/js/pages/projects/linelist/components/InfoBar/InfoBar.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/LineList/LineListLayoutComponent.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/Table/Table.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/Table/renderers/IconCellRenderer.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/Table/renderers/SampleNameRenderer.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/Columns/ColumnVisibility.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TableControlPanel.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/TemplatesPanel.jsx
  src/main/webapp/resources/js/pages/projects/linelist/linelist.scss
  src/main/webapp/resources/js/pages/projects/linelist/styles.js
  src/main/webapp/webpack.config.js
  src/main/webapp/yarn.lock
Labels: UI
