Repository phac-nml/irida, pull requests merged in 2019-09, with the labels that each got.

#456 Setting the priority of an analysis template by project
  doc/user/user/project/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/project/Project.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/submission/AbstractAnalysisSubmission.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/submission/AnalysisSubmission.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/submission/AnalysisSubmissionTemplate.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/AutomatedAnalysisFileProcessor.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/ProjectServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceImpl.java
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/19.09/analysis-templates.xml
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/analysis/details/details.html
  src/main/webapp/pages/projects/settings/pages/basic.html
  src/main/webapp/resources/js/pages/projects/settings/project-settings-basic.js
  src/test/java/ca/corefacility/bioinformatics/irida/processing/impl/unit/AutomatedAnalysisFileProcessorTest.java
Labels: UI, tools

#452 Hotfix/ftp mode
  CHANGELOG.md
  doc/administrator/web/config/irida.conf
  src/main/java/ca/corefacility/bioinformatics/irida/service/export/ExportUploadService.java
  src/main/resources/configuration.properties
  src/main/webapp/resources/js/pages/analyses/analysis-outputs-table.js
  src/main/webapp/resources/js/pages/sequence-files/run-files.js
Labels: back-end

#457 Project analyses updated to use ant.design
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
  src/main/webapp/.babelrc
  src/main/webapp/entries.js
  src/main/webapp/package.json
  src/main/webapp/pages/analyses/analyses.html
  src/main/webapp/pages/projects/analyses/_base.html
  src/main/webapp/pages/projects/analyses/pages/analyses_table.html
  src/main/webapp/resources/js/apis/analysis/analysis.js
  src/main/webapp/resources/js/components/AnalysesTable/AnalysesTable.jsx
  src/main/webapp/resources/js/components/AnalysesTable/AnalysisState.jsx
  src/main/webapp/resources/js/components/ant.design/table-renderers.js
  src/main/webapp/resources/js/contexts/AnalysesContext.js
  src/main/webapp/resources/js/pages/analyses/AnalysesPage.jsx
  src/main/webapp/resources/js/pages/analyses/index.js
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TableControlPanel.jsx
  src/main/webapp/resources/js/pages/projects/project-analyses/ProjectAnalysesPage.jsx
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectAnalysesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectAnalysisPageIT.java
Labels: UI

#459 Delete multiple analyses
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/AnalysisSubmissionService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceImpl.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/analyses/analyses.html
  src/main/webapp/pages/projects/analyses/pages/analyses_table.html
  src/main/webapp/resources/js/apis/analysis/analysis.js
  src/main/webapp/resources/js/components/AnalysesTable/AnalysesTable.jsx
  src/main/webapp/resources/js/components/ant.design/table-renderers.js
  src/main/webapp/resources/js/contexts/AnalysesContext.js
  src/main/webapp/resources/js/pages/projects/list/ProjectsTable.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysesUserPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectAnalysisPageIT.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/ProjectsPageIT.xml
Labels: UI, feature
