Repository phac-nml/irida, pull requests merged in 2019-06, with the labels that each got.

#401 Updated fstream to v1.0.12 to fix security vulnerability
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: security

#403 Updated developers portion of pom file.
  CHANGELOG.md
  pom.xml
Labels: developer

#407 Updated session modal
  CHANGELOG.md
  src/main/resources/i18n/messages_en.properties
  src/main/webapp/pages/template/page.html
  src/main/webapp/resources/js/app.js
  src/main/webapp/resources/js/components/Header/PageHeader.jsx
  src/main/webapp/resources/js/components/session/Session.jsx
  src/main/webapp/resources/js/components/session/SessionModal.jsx
  src/main/webapp/resources/js/hooks/useInterval.js
  src/main/webapp/resources/js/services/IridaSession.js
Labels: UI

#408 Remove momentjs from being loaded on every page.
  CHANGELOG.md
  src/main/resources/i18n/messages_en.properties
  src/main/webapp/bower.json
  src/main/webapp/entries.js
  src/main/webapp/package.json
  src/main/webapp/pages/clients/_base.html
  src/main/webapp/pages/template/page.html
  src/main/webapp/resources/js/client.js
  src/main/webapp/webpack.config.js
  src/main/webapp/yarn.lock
Labels: UI

#409 Remove livestampjs as a project dependency
  CHANGELOG.md
  src/main/webapp/bower.json
  src/main/webapp/package.json
  src/main/webapp/pages/announcements/announcements.html
  src/main/webapp/pages/events/events.html
  src/main/webapp/pages/index.html
  src/main/webapp/pages/samples/_base.html
  src/main/webapp/pages/sequencingRuns/_details_base.html
  src/main/webapp/resources/js/modules/events/events.js
  src/main/webapp/resources/sass/modules/announcements.scss
  src/main/webapp/resources/sass/modules/events.scss
  src/main/webapp/yarn.lock
Labels: UI

#389 Fixed REST analysis output file URLS truncated by `.`
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/RESTAnalysisSubmissionController.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/integration/analysis/RESTAnalysisSubmissionControllerIT.java
Labels: REST API, bug

#410 Remove noty from bower
  CHANGELOG.md
  src/main/webapp/bower.json
  src/main/webapp/pages/sequencingRuns/run_files.html
Labels: UI

#404 Analysis automation - Disable old analysis templates
  src/main/java/ca/corefacility/bioinformatics/irida/database/changesets/AutomatedAnalysisToTemplate.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/project/Project.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/submission/AnalysisSubmissionTemplate.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/AutomatedAnalysisFileProcessor.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/analysis/submission/AnalysisSubmissionTemplateRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/dto/TemplateResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/AnalysisSubmissionService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceImpl.java
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/19.09/analysis-templates.xml
  src/main/resources/i18n/messages_en.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/projects/settings/_base.html
  src/main/webapp/pages/projects/settings/pages/basic.html
  src/main/webapp/pages/projects/settings/pages/delete.html
  src/main/webapp/resources/js/pages/projects/settings/project-settings-basic.js
  src/main/webapp/resources/sass/pages/project-settings-basic.scss
  src/test/java/ca/corefacility/bioinformatics/irida/processing/impl/unit/AutomatedAnalysisFileProcessorTest.java
Labels: tools

#414 Remove unnecessary exists in update
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/CRUDServiceImpl.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/user/UserServiceImplTest.java
Labels: developer

#416 Sequence file details remove lighthouse javascript
  CHANGELOG.md
  src/main/webapp/bower.json
  src/main/webapp/pages/sequenceFiles/_base.html
  src/main/webapp/pages/sequenceFiles/file_details.html
  src/main/webapp/resources/js/pages/sequence-files/sequence-files.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/sequenceFiles/SequenceFilePages.java
Labels: UI
