Repository phac-nml/irida, pull requests merged in 2019-03, with the labels that each got.

#280 linked new uploader in the docs
  doc/user/tutorials/uploader-tool/index.md
Labels: documentation

#305 Developer request template
  .github/ISSUE_TEMPLATE/1_bug_report.md
  .github/ISSUE_TEMPLATE/2_feature_request.md
  .github/ISSUE_TEMPLATE/3_developer_request.md
Labels: developer

#302 Analysis template submission ui
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/analysis/submission/AnalysisSubmissionTemplateRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/dto/PipelineStartParameters.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/AnalysisSubmissionService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceImpl.java
  src/main/resources/i18n/messages_en.properties
  src/main/webapp/pages/pipelines/pipeline_selection.html
  src/main/webapp/pages/pipelines/types/generic_pipeline.html
  src/main/webapp/pages/projects/settings/pages/basic.html
  src/main/webapp/resources/js/pages/pipelines/pipeline.launch.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/pipelines/PipelineControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/analysis/submission/AnalysisSubmissionServiceImplTest.java
Labels: UI, tools

#297 CartController testing
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/CartController.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/CartControllerIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/CartControllerTest.java
Labels: test

#311 Spring security update 4.x
  CHANGELOG.md
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaApiSecurityConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaWebSecurityConfig.java
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/model/enums/analysis/integration/SNVPhylAnalysisIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/pipeline/results/impl/integration/AnalysisSubmissionSampleProcessorImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/pipeline/results/updater/impl/integration/AssemblySampleUpdaterIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/pipeline/results/updater/impl/unit/SISTRSampleUpdaterTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/pipeline/upload/galaxy/integration/GalaxyJobErrorsServiceIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/repositories/UserRepositoryImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/repositories/analysis/submission/AnalysisSubmissionRepositoryIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/repositories/relational/auditing/UserRevListenerIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/repositories/sample/SampleRepositoryIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/CartControllerIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/analysis/execution/galaxy/impl/integration/AnalysisExecutionServiceGalaxyIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/analysis/workspace/galaxy/impl/integration/AnalysisCollectionServiceGalaxyIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/analysis/workspace/galaxy/impl/integration/AnalysisWorkspaceServiceGalaxyIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/AnalysisExecutionScheduledTaskImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/AnalysisServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/AnnouncementServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/InMemoryTaxonomyServiceIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/IridaClientDetailsServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/ProjectEventServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/ProjectServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/ReferenceFileServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/RemoteAPIServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/SequencingObjectServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/SequencingRunServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/WorkflowNamedParametersServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/analysis/submission/AnalysisSubmissionCleanupServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/analysis/submission/AnalysisSubmissionServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/analysis/submission/AnalysisSubmissionServiceImpl_getAnalysisOutputFileInfoIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/sample/MetadataTemplateServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/sample/SampleServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/user/PasswordResetServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/user/UserGroupServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/user/UserServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/workflow/integration/IridaWorkflowLoaderServiceIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/workflow/integration/IridaWorkflowsServiceIT.java
Labels: security

#299 Cart/pipelines page
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java
  src/main/webapp/pages/pipelines/pipeline_selection.html
  src/main/webapp/resources/js/components/pipeline/Pipeline.jsx
  src/main/webapp/resources/js/pages/cart/components/CartTools.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/CartPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/pipelines/PipelinesSelectionPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pipelines/AssemblyPipelinePageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pipelines/PipelinesPhylogenomicsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pipelines/PipelinesSelectionPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/pipelines/PipelineControllerTest.java
Labels: test

#286 Email user on pipeline completion
  CHANGELOG.md
  doc/user/user/pipelines/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/config/services/IridaApiAspectsConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/config/services/WebEmailConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/config/services/scheduled/AnalysisScheduledTaskConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/submission/AnalysisSubmission.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/dto/PipelineStartParameters.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/AnalysisSubmissionService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/EmailController.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/analysis/execution/AnalysisExecutionServiceAspect.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/AnalysisExecutionScheduledTaskImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/EmailControllerImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/TestEmailController.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceImpl.java
  src/main/resources/ca/corefacility/bioinformatics/irida/database/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/19.04/add-email-pipeline-result-to-analysis-submission.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/19.04/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/sql/required-data.sql
  src/main/resources/i18n/messages_en.properties
  src/main/resources/mail/pipeline-status-email.html
  src/main/webapp/pages/pipelines/types/generic_pipeline.html
  src/main/webapp/resources/js/pages/pipelines/pipeline.launch.js
  src/test/java/ca/corefacility/bioinformatics/irida/model/enums/analysis/integration/SNVPhylAnalysisIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/pipeline/upload/galaxy/integration/GalaxyJobErrorsServiceIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/pipelines/PipelinesAssemblyPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pipelines/AssemblyPipelinePageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/pipelines/PipelineControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/AnalysisExecutionScheduledTaskImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/AnalysisExecutionScheduledTaskImplTest.java
Labels: UI, back-end, documentation, enhancement

#325 fixed the email subscription toggle on the user details page
  CHANGELOG.md
  src/main/webapp/pages/user/user_details.html
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/user/UserDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/users/UserDetailsPageIT.java
Labels: UI, bug

#321 Fix add group member search
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/GroupsController.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/groups/GroupsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/groups/GroupsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/GroupsControllerTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/GroupsPageIT.xml
Labels: bug

#315 fix-remote-project-user-groups
  CHANGELOG.md
  src/main/webapp/pages/projects/settings/pages/groups.html
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/LoginPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java
Labels: UI, documentation, test

#327 Cart/documentation
  doc/_includes/tutorials/common/samples/galaxy-export.md
  doc/images/tutorials/common/samples/cart-galaxy-oauth2.png
  doc/images/tutorials/common/samples/cart-galaxy-page.png
  doc/images/tutorials/common/samples/export-to-galaxy-button.png
  doc/images/tutorials/common/samples/export-to-galaxy-dialog.png
  doc/images/tutorials/common/samples/galaxy-irida-projects-list.png
  doc/user/user/pipelines/images/cart-clear-button.png
  doc/user/user/pipelines/images/cart-filter-input.gif
  doc/user/user/pipelines/images/cart-filter-input.png
  doc/user/user/pipelines/images/empty-cart.png
  doc/user/user/pipelines/images/full-cart.png
  doc/user/user/pipelines/images/menu-icon.png
  doc/user/user/pipelines/images/pipeline-launch-cart.png
  doc/user/user/pipelines/images/pipeline-tab.png
  doc/user/user/pipelines/images/remove-icon.png
  doc/user/user/pipelines/images/select-a-pipeline-button.png
  doc/user/user/pipelines/images/select-a-pipeline-page.png
  doc/user/user/pipelines/index.md
Labels: documentation
