Repository phac-nml/irida, pull requests merged in 2019-10, with the labels that each got.

#472 Hotfix - Missing upgrading message
  UPGRADING.md
Labels: documentation

#473 Upgrade to java 11
  .travis.yml
  CHANGELOG.md
  UPGRADING.md
  doc/administrator/web/centos/index.md
  doc/administrator/web/index.md
  doc/administrator/web/ubuntu/index.md
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/InMemoryTaxonomyService.java
  src/main/webapp/resources/js/pages/analyses/analysis-outputs-table.js
  src/main/webapp/resources/js/pages/sequence-files/run-files.js
  src/test/java/ca/corefacility/bioinformatics/irida/events/ProjectEventAspectTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/analysis/annotations/RunAsUserAspectTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/validators/ValidateMethodParametersAspectTest.java
Labels: developer

#479 Fixed default server language
  CHANGELOG.md
  pom.xml
  src/main/resources/configuration.properties
Labels: bug

#482 Concatenate zipped fastq
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/exceptions/ConcatenateException.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/concatenate/SequencingObjectConcatenator.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/concatenate/impl/SequenceFilePairConcatenator.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/concatenate/impl/SingleEndSequenceFileConcatenator.java
  src/test/java/ca/corefacility/bioinformatics/irida/processing/concatenate/SequencingObjectConcatenatorFactoryTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/processing/concatenate/impl/SequenceFilePairConcatenatorTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/processing/concatenate/impl/SingleEndSequenceFileConcatenatorTest.java
Labels: bug

#486 Fixed issue with "Let the pipeline run" button not working.
  CHANGELOG.md
  src/main/webapp/resources/js/modules/cart/irida.cart.js
  src/main/webapp/resources/js/pages/pipelines/pipeline.launch.js
Labels: UI, bug

#483 Fix client edit form to correctly populate authorized grant types
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/oauth/ClientsController.java
  src/main/webapp/pages/clients/create.html
  src/main/webapp/pages/clients/edit.html
Labels: bug

#454 Update spring
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaOauthSecurityConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaWebSecurityConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/OauthRedirectResolver.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/integration/project/ProjectSamplesIT.java
Labels: REST API, back-end, enhancement

#484 Fix issue with browser filling in password field on user edit page.
  CHANGELOG.md
  src/main/webapp/pages/templates/password.html
  src/main/webapp/pages/user/edit.html
Labels: UI, bug

#458 added version api route and note in docs
  CHANGELOG.md
  doc/developer/rest/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/RESTRootController.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/RootControllerTest.java
Labels: REST API
