Repository phac-nml/irida, pull requests merged in 2020-04, with the labels that each got.

#636 Upload assemblies through the IRIDA UI
  CHANGELOG.md
  doc/_includes/tutorials/common/uploading-sample-files.md
  doc/images/tutorials/common/samples/concatenate-link.png
  doc/images/tutorials/common/samples/upload-assembly.png
  doc/images/tutorials/common/samples/upload-sample-cancel-btn.png
  doc/images/tutorials/common/samples/upload-sample-file-btn.png
  doc/images/tutorials/common/samples/upload-sample-file-selection.png
  doc/images/tutorials/common/samples/upload-sample-progress-cancel.png
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesController.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/samples/sample_files.html
  src/main/webapp/resources/js/apis/files/files.js
  src/main/webapp/resources/js/components/MenuBar.jsx
  src/main/webapp/resources/js/components/files/FileUploader.jsx
  src/main/webapp/resources/js/components/icons/Icons.jsx
  src/main/webapp/resources/js/components/sample/SampleFileUploader.jsx
  src/main/webapp/resources/js/components/sample/SampleMenuBar.jsx
  src/main/webapp/resources/js/pages/SamplePage.jsx
  src/main/webapp/resources/js/pages/samples/sample-files.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/samples/SampleFilesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/samples/SampleFilesPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/samples/SamplesAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/samples/SamplesControllerTest.java
Labels: UI, feature

#642 Fixed checking to see if table sorted by modified date
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/AntTable.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/AdminUsersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/users/AdminUsersPageIT.java
Labels: test

#631 Remove global angular ui bootstrap
  CHANGELOG.md
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/user/user_details.html
  src/main/webapp/resources/js/app.js
  src/main/webapp/resources/js/pages/pipelines/pipeline.launch.js
  src/main/webapp/resources/js/pages/projects/project-reference-files.js
  src/main/webapp/resources/js/pages/projects/projects-new.js
  src/main/webapp/resources/js/pages/user-details.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/announcements/AnnouncementPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/AnnouncementControlPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/CreateAnnouncementComponent.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/sequencingRuns/SequencingRunDetailsPageIT.java
Labels: UI

#647 /static endpoint for customizing brand
  src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaWebSecurityConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/config/web/IridaUIWebConfig.java
Labels: UI

#634 Upload assemblies
  CHANGELOG.md
  UPGRADING.md
  doc/_includes/tutorials/common/uploading-sample-files.md
  doc/administrator/web/config/irida.conf
  doc/administrator/web/index.md
  doc/images/tutorials/common/samples/concatenate-link.png
  doc/images/tutorials/common/samples/upload-assembly.png
  doc/images/tutorials/common/samples/upload-sample-cancel-btn.png
  doc/images/tutorials/common/samples/upload-sample-file-btn.png
  doc/images/tutorials/common/samples/upload-sample-file-selection.png
  doc/images/tutorials/common/samples/upload-sample-progress-cancel.png
  src/main/java/ca/corefacility/bioinformatics/irida/config/repository/IridaApiFilesystemRepositoryConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/assembly/GenomeAssembly.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/assembly/GenomeAssemblyFromAnalysis.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/assembly/UploadedAssembly.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/joins/impl/SampleGenomeAssemblyJoin.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/assembly/GenomeAssemblyRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/assembly/GenomeAssemblyRepositoryImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/joins/sample/GenomeAssemblyRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/GenomeAssemblyService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/GenomeAssemblyServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/SampleServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/sample/SampleService.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/samples/RESTSampleAssemblyController.java
  src/main/resources/ca/corefacility/bioinformatics/irida/config/filesystem.properties
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/20.05/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/20.05/uploaded-assemblies.xml
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/samples/sample_files.html
  src/main/webapp/resources/js/apis/files/files.js
  src/main/webapp/resources/js/components/MenuBar.jsx
  src/main/webapp/resources/js/components/files/FileUploader.jsx
  src/main/webapp/resources/js/components/files/UploadProgressNotification.js
  src/main/webapp/resources/js/components/files/file-upload-utilities.js
  src/main/webapp/resources/js/components/icons/Icons.jsx
  src/main/webapp/resources/js/components/sample/SampleFileUploader.jsx
  src/main/webapp/resources/js/components/sample/SampleMenuBar.jsx
  src/main/webapp/resources/js/pages/SamplePage.jsx
  src/main/webapp/resources/js/pages/samples/sample-files.js
  src/test/java/ca/corefacility/bioinformatics/irida/config/data/IridaApiTestFilesystemConfig.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/samples/SampleFilesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/samples/SampleFilesPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/samples/SamplesAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/samples/SamplesControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/GenomeAssemblyServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/sample/SampleServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/sample/SampleServiceImplTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/samples/RESTSampleAssemblyControllerTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/test/integration/TableReset.xml
Labels: REST API, UI, documentation

#648 Basic custom login
  doc/developer/interface/custom-login/basic-login.html.md
  doc/developer/interface/custom-login/images/irida-basic-login.png
  doc/developer/interface/custom-login/index.md
Labels: UI, documentation

#638 Linker assembly toggle
  CHANGELOG.md
  doc/_includes/tutorials/common/samples/command-line.md
  doc/images/tutorials/common/samples/command-line-linker-dialog.png
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/pages/projects/samples/linker/Linker.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
Labels: UI

#645 Add excel viewer to analysis output preview
  CHANGELOG.md
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/ria/utilities/FileUtilities.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/dto/ExcelCol.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/dto/ExcelData.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/dto/ExcelHeader.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/dto/ExcelRow.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/analysis/analysis.js
  src/main/webapp/resources/js/contexts/AnalysisOutputsContext.js
  src/main/webapp/resources/js/pages/analysis/components/AnalysisExcelPreview.jsx
  src/main/webapp/resources/js/pages/analysis/components/outputs/OutputFilePreview.jsx
Labels: UI, enhancement

#649 Final bower removal
  doc/developer/setup/index.md
  src/main/webapp/package.json
  src/main/webapp/pages/password/reset_created.html
  src/main/webapp/webpack.config.js
  src/main/webapp/yarn.lock
Labels: UI

#643 Project members updated to remove DataTables
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/joins/project/ProjectUserJoinRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/user/UserRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/security/LoginSuccessHandler.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/exceptions/UIProjectWithoutOwnerException.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/tables/TableRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/ProjectMemberTableModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectMembersAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectMembersController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/dto/NewProjectMemberRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/dto/Role.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectMembersService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectsService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/projects/settings/pages/members.html
  src/main/webapp/resources/js/apis/projects/members.js
  src/main/webapp/resources/js/apis/projects/projects.js
  src/main/webapp/resources/js/components/icons/Icons.jsx
  src/main/webapp/resources/js/components/project-members/AddMemberButton.jsx
  src/main/webapp/resources/js/components/project-members/ProjectMembersTable.jsx
  src/main/webapp/resources/js/components/project-members/ProjectRole.jsx
  src/main/webapp/resources/js/components/project-members/RemoveMemberButton.jsx
  src/main/webapp/resources/js/components/project-members/index.js
  src/main/webapp/resources/js/contexts/ProjectRolesContext.js
  src/main/webapp/resources/js/hooks/index.js
  src/main/webapp/resources/js/hooks/useDebounce.js
  src/main/webapp/resources/js/hooks/useResetFormOnCloseModal.js
  src/main/webapp/resources/js/pages/projects/ProjectMembers.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/UIProjectMembersServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectMembersControllerTest.java
Labels: UI

#658 Added analysis result image viewer
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/AnalysisOutputFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/analysis/analysis.js
  src/main/webapp/resources/js/contexts/AnalysisOutputsContext.js
  src/main/webapp/resources/js/pages/analysis/components/AnalysisImagePreview.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisJsonPreview.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisTextPreview.jsx
  src/main/webapp/resources/js/pages/analysis/components/outputs/OutputFilePreview.jsx
Labels: UI, enhancement

#652 Galaxy assembly export toggle
  CHANGELOG.md
  doc/_includes/tutorials/common/samples/galaxy-export.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/assembly/GenomeAssembly.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/irida/IridaSequenceFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/SequenceFile.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/galaxy/submission.js
  src/main/webapp/resources/js/components/galaxy/GalaxyDetailsForm.jsx
  src/main/webapp/resources/js/components/galaxy/GalaxySubmission.jsx
  src/main/webapp/resources/js/components/galaxy/reducer.js
Labels: REST API, UI, galaxy

#660 removed all notes of java 8 from the docs
  doc/administrator/web/ubuntu/index.md
  doc/developer/getting-started/index.md
  doc/developer/setup/index.md
Labels: documentation

#659 Move project details to settings
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/TaxonomyEntry.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/ontologies/TaxonomyAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectExportController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/metadata/ProjectSampleMetadataController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectDetailsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/dto/ProjectDetailsResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/dto/UpdateProjectAttributeRequest.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/.babelrc
  src/main/webapp/entries.js
  src/main/webapp/package.json
  src/main/webapp/pages/projects/_base.html
  src/main/webapp/pages/projects/project_metadata.html
  src/main/webapp/pages/projects/settings/_base.html
  src/main/webapp/pages/projects/settings/pages/details.html
  src/main/webapp/pages/projects/settings/pages/processing.html
  src/main/webapp/resources/js/apis/ontology/taxonomy/index.js
  src/main/webapp/resources/js/apis/ontology/taxonomy/query.js
  src/main/webapp/resources/js/apis/projects/projects.js
  src/main/webapp/resources/js/components/Buttons/IconButton.jsx
  src/main/webapp/resources/js/components/Buttons/index.js
  src/main/webapp/resources/js/components/ant.design/EditableParagraph.jsx
  src/main/webapp/resources/js/components/ant.design/index.js
  src/main/webapp/resources/js/components/ontology/OntologySelect.jsx
  src/main/webapp/resources/js/components/ontology/index.js
  src/main/webapp/resources/js/pages/projects/ProjectMembers.jsx
  src/main/webapp/resources/js/pages/projects/details/ProjectDetails.jsx
  src/main/webapp/resources/js/pages/projects/details/index.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectActivityPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectMetadataEditPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectMetadataPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSettingsProcessingPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectActivityPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectDetailsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMetadataEditPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMetadataPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSyncPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectsNewPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/ajax/ontologies/TaxonomyAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectDetailsAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectsControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/TestDataFactory.java
Labels: UI

#662 Project navigation update
  CHANGELOG.md
  src/main/webapp/entries.js
  src/main/webapp/package.json
  src/main/webapp/pages/projects/_base.html
  src/main/webapp/pages/template/page.html
  src/main/webapp/resources/js/components/project/ProjectNav.jsx
  src/main/webapp/resources/js/components/project/RemoteProjectStatus.jsx
  src/main/webapp/resources/js/components/project/index.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectPageBase.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
Labels: UI
