Repository phac-nml/irida, pull requests merged in 2020-11, with the labels that each got.

#835 Refactor fastqc page
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/AnalysisFastQC.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/AnalysisOutputFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/files/SequenceFileAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/files/SequenceFileController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/files/dto/FastQCDetailsResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/files/dto/FastQCImagesResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISequenceFileService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/sequenceFiles/_base.html
  src/main/webapp/pages/sequenceFiles/fastqc.html
  src/main/webapp/pages/sequenceFiles/file_details.html
  src/main/webapp/pages/sequenceFiles/file_overrepresented.html
  src/main/webapp/resources/js/apis/files/sequence-files.js
  src/main/webapp/resources/js/components/lists/BasicList.jsx
  src/main/webapp/resources/js/pages/sequence-files/components/FastQC.jsx
  src/main/webapp/resources/js/pages/sequence-files/components/FastQCCharts.jsx
  src/main/webapp/resources/js/pages/sequence-files/components/FastQCDetails.jsx
  src/main/webapp/resources/js/pages/sequence-files/components/OverRepresentedSequences.jsx
  src/main/webapp/resources/js/pages/sequence-files/fastqc-context.js
  src/main/webapp/resources/js/pages/sequence-files/fastqc-utilities.js
  src/main/webapp/resources/js/pages/sequence-files/index.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/sequenceFiles/SequenceFilePages.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/sequenceFiles/SequenceFilePageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/files/SequenceFileAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/files/SequenceFileControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UISequenceFileServiceTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/sequenceFiles/SequenceFileView.xml
  src/test/resources/files/duplicationLevelChart.png
  src/test/resources/files/perBaseQualityScoreChart.png
  src/test/resources/files/perSequenceQualityScoreChart.png
Labels: UI, enhancement

#844 Announcements upgrade database
  src/main/java/ca/corefacility/bioinformatics/irida/model/announcements/Announcement.java
  src/main/resources/ca/corefacility/bioinformatics/irida/database/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.01/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.01/announcements_upgrade.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/sql/required-data.sql
  src/main/resources/scripts/announcements/README.txt
  src/main/resources/scripts/announcements/generate_json.py
  src/main/resources/scripts/announcements/requirements.txt
  src/main/resources/scripts/announcements/update_announcements.py
Labels: back-end

#847 Added fastqc page documentation
  CHANGELOG.md
  doc/_includes/tutorials/common/view-sequence-file-fastqc.md
  doc/images/tutorials/common/samples/fastqc-charts.png
  doc/images/tutorials/common/samples/fastqc-details.png
  doc/images/tutorials/common/samples/fastqc-overrepresented.png
  doc/user/user/samples/index.md
Labels: documentation

#759 Object store/ azure
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/config/services/IridaApiServicesConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/Fast5Object.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/concatenate/impl/SingleEndSequenceFileConcatenator.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/FastqcFileProcessor.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageAzureUtilityImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageLocalUtilityImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageUtility.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaTemporaryFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/SequencingObjectServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/util/IridaFiles.java
  src/test/java/ca/corefacility/bioinformatics/irida/processing/impl/unit/FastqcFileProcessorTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysesTableAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/integration/security/SecurityIT.java
Labels: back-end, developer

#855 Refactor project reference file page
  CHANGELOG.md
  doc/_includes/tutorials/common/uploading-a-reference.md
  doc/images/tutorials/common/pipelines/reference-file-uploaded.png
  doc/images/tutorials/common/pipelines/reference-files-page.png
  doc/user/user/project/images/project-details-reference-files-tab.png
  doc/user/user/project/images/upload-reference-file-button.png
  doc/user/user/project/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/utilities/FileUtilities.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/ReferenceFileAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/ajax/AjaxSuccessResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/references/UIReferenceFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/files/ReferenceFileController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/ProjectInfoResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectReferenceFileController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectReferenceFileService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectsService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/projects/settings/pages/references.html
  src/main/webapp/resources/js/apis/projects/projects.js
  src/main/webapp/resources/js/apis/projects/reference-files.js
  src/main/webapp/resources/js/components/Buttons/DownloadTableItemButton.jsx
  src/main/webapp/resources/js/components/Buttons/RemoveTableItemButton.jsx
  src/main/webapp/resources/js/components/Buttons/index.js
  src/main/webapp/resources/js/components/files/DragUpload.jsx
  src/main/webapp/resources/js/components/icons/Icons.jsx
  src/main/webapp/resources/js/pages/projects/project-reference-files.js
  src/main/webapp/resources/js/pages/projects/reference-files/ReferenceFiles.jsx
  src/main/webapp/resources/js/pages/projects/reference-files/index.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectReferenceFilePage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectReferenceFilePageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/files/ReferenceFileAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIProjectReferenceFileServiceTest.java
Labels: UI

#861 Set chromedriver to version 87.0.0 as latest not working
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: developer

#834 Refactor statistics queries
  src/main/java/ca/corefacility/bioinformatics/irida/model/enums/StatisticTimePeriod.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/ProjectRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/analysis/submission/AnalysisSubmissionRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/SampleRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/user/UserRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAdminStatisticsService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/AnalysisSubmissionService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/ProjectService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/ProjectServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/SampleServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/user/UserServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/sample/SampleService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/user/UserService.java
Labels: UI, back-end

#760 Object store/ aws
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/config/services/IridaApiServicesConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageAwsUtilityImpl.java
Labels: back-end, developer

#860 Upgrade admin new announcement modal
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAnnouncementsService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/announcements/announcements.js
  src/main/webapp/resources/js/pages/admin/components/announcements/AnnouncementAdminPage.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/AnnouncementsTable.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/CreateAnnouncementModal.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/CreateNewAnnouncement.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/announcements/AnnouncementPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/CreateAnnouncementComponent.java
Labels: UI

#863 Admin statistics/ translations
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/pages/admin/components/statistics/AdvancedStatistics.jsx
  src/main/webapp/resources/js/pages/admin/components/statistics/BasicStats.jsx
  src/main/webapp/resources/js/pages/admin/components/statistics/TimePeriodSelect.jsx
Labels: UI

#859 Moved project reference file request
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/ReferenceFileAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectReferenceFileController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectReferenceFileService.java
  src/main/webapp/resources/js/apis/projects/reference-files.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/files/ReferenceFileAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIProjectReferenceFileServiceTest.java
Labels: back-end

#865 Object_store/_update-filesystem-startup
  src/main/java/ca/corefacility/bioinformatics/irida/config/repository/IridaApiFilesystemRepositoryConfig.java
Labels: back-end

#868 Admin statistics/ tests
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/admin/AdminPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/admin/AdminPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIAdminStatisticsServiceTest.java
Labels: test

#846 Change custom login page example to use `window.TL`
  CHANGELOG.md
  doc/developer/interface/custom-login/basic-login.html.md
  doc/developer/interface/custom-login/custom-login.html.md
  doc/developer/interface/custom-login/index.md
Labels: documentation

#867 Announcements upgrade admin edit & details forms
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/announcements/details.html
  src/main/webapp/resources/js/apis/announcements/announcements.js
  src/main/webapp/resources/js/pages/admin/components/announcements/AnnouncementAdminPage.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/AnnouncementModal.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/CreateAnnouncementModal.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/CreateNewAnnouncement.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/EditAnnouncement.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/announcements/AnnouncementPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/AnnouncementControlPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/AnnouncementDetailPage.java
Labels: UI

#871 Admin statistics/ docs
  doc/user/administrator/images/admin-panel-adv-stats.png
  doc/user/administrator/images/admin-panel-stats.png
  doc/user/administrator/index.md
  src/main/webapp/resources/js/pages/admin/chart-config.js
Labels: documentation

#874 Enabling GitHub Actions for CI
  .github/workflows/ci-test.yml
  .travis.yml
  CHANGELOG.md
  doc/developer/getting-started/index.md
  run-tests.sh
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: developer, test

#761 Object store/ gui
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/model/assembly/GenomeAssembly.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/project/ReferenceFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/AnalysisFastQC.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/AnalysisOutputFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/FastqcFileProcessor.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageAwsUtilityImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageAzureUtilityImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageLocalUtilityImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageUtility.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/utilities/FileUtilities.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/ReferenceFileAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/files/SequenceFileController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectReferenceFileService.java
  src/main/java/ca/corefacility/bioinformatics/irida/util/IridaFiles.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/pages/projects/reference-files/ReferenceFiles.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/files/ReferenceFileAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/files/SequenceFileControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/samples/SamplesControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIProjectReferenceFileServiceTest.java
Labels: UI
