Repository phac-nml/irida, pull requests merged in 2020-06, with the labels that each got.

#699 Remove momentjs (except on project samples page)
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/resources/js/client.js
  src/main/webapp/resources/js/pages/projects/samples/project-samples.js
  src/main/webapp/resources/js/utilities/date-utilities.js
  src/main/webapp/resources/js/utilities/date-utilities.test.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisDetailsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/AnnouncementControlPage.java
Labels: UI

#717 Removed deprecated Long constructor
  CHANGELOG.md
  src/test/java/ca/corefacility/bioinformatics/irida/model/SampleTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/model/UserTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/model/sample/metadata/unit/MetadataEntryTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/SequenceFileRepositoryImplTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/repositories/relational/auditing/UserRevListenerIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/AnnouncementServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/GenomeAssemblyServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/ProjectServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/SequencingObjectServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/SequencingRunServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/analysis/submission/AnalysisSubmissionServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/CRUDServiceImplTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/ProjectServiceImplTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/util/impl/SequenceFileUtilitiesTest.java
Labels: developer

#722 Upgrade webpack dependencies to fix issue with websocket-extensions from 0.1.3 to 0.1.4
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: UI

#730 Update node
  CHANGELOG.md
  pom.xml
Labels: developer

#719 Sync assemblies
  CHANGELOG.md
  doc/user/user/project/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/assembly/UploadedAssembly.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/remote/GenomeAssemblyRemoteRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/remote/impl/GenomeAssemblyRemoteRepositoryImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/remote/resttemplate/SequenceFileMessageConverter.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/remote/GenomeAssemblyRemoteService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectSynchronizationService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/remote/impl/GenomeAssemblyRemoteServiceImpl.java
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/20.09/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/20.09/assembly-sync-remote-status.xml
  src/test/java/ca/corefacility/bioinformatics/irida/repositories/remote/resttemplate/SequenceFileMessageConverterTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectSynchronizationServiceTest.java
Labels: REST API, federation

#735 Admin layout
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/admin/AdminBaseController.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/admin/index.html
  src/main/webapp/resources/js/components/UsersTable/UsersTable.jsx
  src/main/webapp/resources/js/pages/UsersPage.jsx
  src/main/webapp/resources/js/pages/admin/components/Admin.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminHeader.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminSideMenu.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminStatistics.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminUsersPage.jsx
  src/main/webapp/resources/js/pages/admin/index.js
  src/main/webapp/resources/js/pages/admin/routes.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/admin/AdminPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/UsersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/admin/AdminPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/users/UsersPageIT.java
Labels: UI

#741 Chromedriver 83 update
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: developer, test

#739 Remove gravatar
  CHANGELOG.md
  doc/user/user/dashboard/images/cart.png
  doc/user/user/dashboard/images/dashboard.png
  doc/user/user/dashboard/images/main-menu.png
  doc/user/user/dashboard/images/search-bar.png
  doc/user/user/dashboard/images/settings-panel.png
  doc/user/user/dashboard/images/user-settings.png
  doc/user/user/dashboard/index.md
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/ria/security/LoginSuccessHandler.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/users/UsersController.java
  src/main/webapp/pages/template/main-navigation.html
  src/main/webapp/resources/css/app.css
Labels: UI

#740 Removed webpack-dev-server
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: dependencies, developer, security

#745 Hotfix: Changed RemoteStatus constructor to `protected`
  CHANGELOG.md
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/model/remote/RemoteStatus.java
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/AnnouncementControlPage.java
Labels: UI, bug

#742 Updated frontend dependencies (`babel`, `fontawesome`, and `ant-icons`)
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: UI, developer

#728 Display metadata template
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/metadata/MetadataTemplatesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/metadata/ProjectSamplesMetadataTemplateController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectMetadataTemplateController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIMetadataTemplateService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/projects/project_samples_metadata_template.html
  src/main/webapp/pages/projects/settings/_base.html
  src/main/webapp/resources/js/apis/metadata/metadata-templates.js
  src/main/webapp/resources/js/apis/metadata/templates.js
  src/main/webapp/resources/js/components/metadata-template/list/index.js
  src/main/webapp/resources/js/components/metadata-template/template/details/index.js
  src/main/webapp/resources/js/components/metadata-template/template/fields/index.js
  src/main/webapp/resources/js/components/metadata-template/template/index.js
  src/main/webapp/resources/js/contexts/metadata-template-context.js
  src/main/webapp/resources/js/pages/projects/metadata-template/create-metadata-template.js
  src/main/webapp/resources/js/pages/projects/metadata-templates/index.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectMetadataTemplatesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMetadataTemplateIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIMetadataTemplateServiceTest.java
Labels: UI
