Repository phac-nml/irida, pull requests merged in 2020-01, with the labels that each got.

#553 Ag Grid Update
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/pages/analyses/user-analysis-outputs.html
  src/main/webapp/pages/projects/analyses/_base.html
  src/main/webapp/pages/projects/analyses/pages/analyses_table.html
  src/main/webapp/pages/projects/analyses/pages/outputs.html
  src/main/webapp/resources/js/components/Tables/AgGridLayout.jsx
  src/main/webapp/resources/js/pages/analyses/analysis-outputs-table.js
  src/main/webapp/resources/js/pages/analysis/tabular-preview.js
  src/main/webapp/resources/js/pages/projects/linelist/components/InfoBar/InfoBar.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/LineList/LineListLayoutComponent.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/Table/Table.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/Table/renderers/IconCellRenderer.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/Table/renderers/SampleNameRenderer.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/Columns/ColumnVisibility.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TableControlPanel.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/TemplatesPanel.jsx
  src/main/webapp/resources/js/pages/projects/linelist/linelist.scss
  src/main/webapp/resources/js/pages/projects/linelist/styles.js
  src/main/webapp/resources/js/styles/fonts.js
  src/main/webapp/webpack.config.js
  src/main/webapp/yarn.lock
Labels: UI

#578 Fix issue with fixed width of the id column of projects table.
  src/main/webapp/resources/js/components/ant.design/table-renderers.js
  src/main/webapp/resources/js/pages/projects/list/ProjectsTable.jsx
  src/main/webapp/yarn.lock
Labels: UI

#569 Update styled components
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectLineListPageIT.java
Labels: UI

#571 Babel & eslint updates
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: UI, developer

#581 Fix auth doc link
  CHANGELOG.md
  UPGRADING.md
  doc/administrator/web/index.md
  doc/developer/authorization/index.md
  doc/developer/index.md
Labels: documentation

#564 SRA Upload: Append .gz to uploaded filenames if fastq files are compressed
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/service/export/ExportUploadService.java
  src/main/resources/ca/corefacility/bioinformatics/irida/export/ncbi.xml
  src/test/java/ca/corefacility/bioinformatics/irida/service/export/ExportUploadServiceTest.java
Labels: back-end

#584 Fix issue with path to i18n files in Tomcat.
  .gitignore
  src/main/java/ca/corefacility/bioinformatics/irida/ria/config/thymeleaf/I18nPreProcessorDialect.java
  src/main/webapp/pages/templates/i18n/README.md
  src/main/webapp/webpack/i18nThymeleafWebpackPlugin.js
Labels: UI

#585 Fixes issue where galaxy banner does not load
  src/main/webapp/resources/js/components/Header/PageHeader.jsx
  src/main/webapp/resources/js/utilities/url-utilities.js
Labels: UI

#586 Fixed issue where servlet path was being added multiple times.
  src/main/webapp/resources/js/utilities/url-utilities.js
Labels: UI, critical

#587 Re-enabled tabular previews.
  src/main/webapp/resources/js/pages/analysis/tabular-preview.js
Labels: UI, bug

#588 Added mysql5.5 dialect change to upgrading guide
  CHANGELOG.md
  UPGRADING.md
Labels: documentation

#589 Fixed the title of the users list page
  CHANGELOG.md
  src/main/webapp/pages/user/list.html
Labels: UI, bug
