Repository phac-nml/irida, pull requests merged in 2020-02, with the labels that each got.

#577 Update to Ant Design v4
  src/main/resources/i18n/messages.properties
  src/main/webapp/package.json
  src/main/webapp/resources/js/components/AnalysesTable/AnalysesTable.jsx
  src/main/webapp/resources/js/components/AnalysesTable/AnalysisState.jsx
  src/main/webapp/resources/js/components/Header/GalaxyAlert.jsx
  src/main/webapp/resources/js/components/Tables/fitlers/FilterIcon.jsx
  src/main/webapp/resources/js/components/ant.design/table-renderers.js
  src/main/webapp/resources/js/components/ant.design/table-search-props.js
  src/main/webapp/resources/js/components/galaxy/GalaxySamples.jsx
  src/main/webapp/resources/js/components/popovers/HelpPopover.jsx
  src/main/webapp/resources/js/components/session/SessionModal.jsx
  src/main/webapp/resources/js/contexts/PagedTableContext.js
  src/main/webapp/resources/js/pages/cart/components/CartNotification.jsx
  src/main/webapp/resources/js/pages/cart/components/CartSider.jsx
  src/main/webapp/resources/js/pages/cart/components/CartToolsMenu.jsx
  src/main/webapp/resources/js/pages/cart/components/SampleRenderer.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/AddToCartButton/AddSamplesToCart.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/Export/ExportDropdown.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/Loader/Loader.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/Table/renderers/DateCellRenderer.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/Table/renderers/IconCellRenderer.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TableControlPanel.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/SaveTemplate/SaveTemplateButton.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/SaveTemplate/SaveTemplateForm.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/SaveTemplate/index.js
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/SaveTemplateModal.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/TemplateSelect/SaveTemplateButton.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/TemplateSelect/TemplateSelect.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/TemplateSelect/TemplateSelectOption.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/TemplatesPanel.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/Toolbar/Toolbar.jsx
  src/main/webapp/resources/js/pages/projects/linelist/linelist.scss
  src/main/webapp/resources/js/pages/projects/linelist/reducers/templates.js
  src/main/webapp/resources/js/pages/projects/list/ProjectsTable.jsx
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysesUserPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/AssociatedProjectPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectLineListPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectsPageIT.java
Labels: UI

#570 Clients ant design table to replace Datatables
  CHANGELOG.md
  doc/images/tutorials/clients/clients-list-add-client-button.png
  doc/images/tutorials/clients/clients-list.png
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysesListRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysesListResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysisModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/clients/ClientsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/clients/dto/ClientModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/clients/dto/ClientTableRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/TableModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/TableResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/datatables/DTClient.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/tables/TableModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/tables/TableRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/tables/TableResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/sequencingRuns/SequencingRunAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/sequencingRuns/dto/SequencingRunModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/sequencingRuns/dto/SequencingRunsListRequest.java
  src/main/webapp/entries.js
  src/main/webapp/package.json
  src/main/webapp/pages/clients/list.html
  src/main/webapp/resources/js/apis/clients/clients.js
  src/main/webapp/resources/js/components/AnalysesTable/AnalysesTable.jsx
  src/main/webapp/resources/js/components/AnalysesTable/AnalysisState.jsx
  src/main/webapp/resources/js/components/ant.design/PagedTable/PagedTable.jsx
  src/main/webapp/resources/js/components/ant.design/PagedTable/PagedTableContext.js
  src/main/webapp/resources/js/components/ant.design/PagedTable/index.js
  src/main/webapp/resources/js/components/ant.design/table-renderers.js
  src/main/webapp/resources/js/components/page/PageWrapper.jsx
  src/main/webapp/resources/js/contexts/PagedTableContext.js
  src/main/webapp/resources/js/pages/analyses/AnalysesPage.jsx
  src/main/webapp/resources/js/pages/clients/clients-list.js
  src/main/webapp/resources/js/pages/clients/listing/ClientListingPage.jsx
  src/main/webapp/resources/js/pages/clients/listing/ClientsTables.jsx
  src/main/webapp/resources/js/pages/projects/project-analyses/ProjectAnalysesPage.jsx
  src/main/webapp/resources/js/pages/sequencing-runs/SequencingRunsList.jsx
  src/main/webapp/resources/js/pages/sequencing-runs/SequencingRunsPage.jsx
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/clients/ClientsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/clients/ClientsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/ClientsControllerTest.java
Labels: UI

#601 Sync expired email
  CHANGELOG.md
  doc/user/user/project/images/sync-expired.png
  doc/user/user/project/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/service/EmailController.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/EmailControllerImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/TestEmailController.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectSynchronizationService.java
  src/main/resources/i18n/messages.properties
  src/main/resources/mail/sync-expired.html
  src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectSynchronizationServiceTest.java
Labels: federation

#602 Hotfix ant table filtering
  CHANGELOG.md
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysesFilters.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/TableRequest.java
  src/main/webapp/resources/js/components/ant.design/table-search-props.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysesUserPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisAdminPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysesUserPage.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAdminView.xml
Labels: UI, bug

#606 Changed trim for tablerequests
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/tables/TableRequest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysesUserPage.java
Labels: bug, test

#609 Fix ngs-linker exporting >= 330 samples
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/NGSLinkerAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/NGSLinkerCmdRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/NGSLinkerService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/projects/partials/samples.tmpl.html
  src/main/webapp/pages/projects/project_samples.html
  src/main/webapp/pages/projects/templates/linker-modal.tmpl.html
  src/main/webapp/resources/js/apis/linker/linker.js
  src/main/webapp/resources/js/pages/projects/list/ProjectsTable.jsx
  src/main/webapp/resources/js/pages/projects/samples/linker/Linker.jsx
  src/main/webapp/resources/js/pages/projects/samples/project-samples.js
  src/main/webapp/resources/js/styles/borders.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
Labels: UI, bug

#599 Updated breadcrumbs
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/config/web/IridaUIWebConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/config/BreadCrumbInterceptor.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/package.json
  src/main/webapp/pages/announcements/control.html
  src/main/webapp/pages/projects/project_samples.html
  src/main/webapp/pages/template/page.html
  src/main/webapp/resources/js/components/Header/Breadcrumbs.jsx
  src/main/webapp/resources/js/components/Header/PageHeader.jsx
  src/main/webapp/resources/js/components/ant.design/PagedTable/PagedTableContext.js
  src/main/webapp/resources/sass/app.scss
  src/main/webapp/resources/sass/components/_breadcrumbs.scss
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/AbstractPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/samples/SampleFilesPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/BreadCrumbInterceptorTest.java
Labels: UI
