Repository phac-nml/irida, pull requests merged in 2020-12, with the labels that each got.

#877 adding the github acitons CI badge to the readme
  README.md
Labels: developer

#873 Add reference file upload progress
  CHANGELOG.md
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/projects/reference-files.js
  src/main/webapp/resources/js/components/files/DragUpload.jsx
  src/main/webapp/resources/js/pages/projects/reference-files/ReferenceFiles.jsx
Labels: UI, enhancement

#879 Added link to GitHub Actions CI in readme badge
  .github/workflows/ci-test.yml
  README.md
Labels: developer, test

#864 Add fast5 sync
  CHANGELOG.md
  doc/user/user/project/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/Fast5Object.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/remote/Fast5ObjectRemoteRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/remote/impl/Fast5ObjectRemoteRepositoryImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/remote/resttemplate/SequenceFileMessageConverter.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/remote/Fast5ObjectRemoteService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectSynchronizationService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/remote/impl/Fast5ObjectRemoteServiceImpl.java
  src/test/java/ca/corefacility/bioinformatics/irida/repositories/remote/resttemplate/SequenceFileMessageConverterTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectSynchronizationServiceTest.java
  src/test/resources/files/testfast5file.fast5
Labels: enhancement, federation

#882 Updating main branch to use Github Actions for CI
  .github/workflows/ci-test.yml
  .travis.yml
  CHANGELOG.md
  README.md
  run-tests.sh
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: test

#875 Admin statistics
  CHANGELOG.md
  doc/user/administrator/images/admin-panel-adv-stats.png
  doc/user/administrator/images/admin-panel-stats.png
  doc/user/administrator/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/enums/StatisticTimePeriod.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/ProjectRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/analysis/submission/AnalysisSubmissionRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/SampleRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/user/UserRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/admin/AdminStatisticsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/admin/dto/statistics/BasicStatsResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/admin/dto/statistics/GenericStatModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/admin/dto/statistics/StatisticsResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAdminStatisticsService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/AnalysisSubmissionService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/ProjectService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/ProjectServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/SampleServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/user/UserServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/sample/SampleService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/user/UserService.java
  src/main/resources/ca/corefacility/bioinformatics/irida/sql/required-data.sql
  src/main/resources/i18n/messages.properties
  src/main/webapp/package.json
  src/main/webapp/resources/js/apis/admin/admin.js
  src/main/webapp/resources/js/pages/admin/chart-config.js
  src/main/webapp/resources/js/pages/admin/components/Admin.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminSideMenu.jsx
  src/main/webapp/resources/js/pages/admin/components/statistics/AdvancedStatistics.jsx
  src/main/webapp/resources/js/pages/admin/components/statistics/BasicStats.jsx
  src/main/webapp/resources/js/pages/admin/components/statistics/ChartTypeButtons.jsx
  src/main/webapp/resources/js/pages/admin/components/statistics/TimePeriodSelect.jsx
  src/main/webapp/resources/js/pages/admin/index.js
  src/main/webapp/resources/js/pages/admin/routes.js
  src/main/webapp/resources/js/pages/admin/statistics-constants.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/admin/AdminPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/admin/AdminPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIAdminStatisticsServiceTest.java
Labels: UI, enhancement

#885 Analysis results UI updates
  CHANGELOG.md
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/components/AnalysesTable/AnalysisDownloadButton.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisJsonPreview.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisTabularPreview.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisTextPreview.jsx
  src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisReferenceFileRenderer.jsx
Labels: UI

#876 Announcements upgrade admin details page
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/announcements/AnnouncementAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/announcements/dto/AnnouncementUserTableModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAnnouncementsService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/announcements/create.html
  src/main/webapp/pages/announcements/details.html
  src/main/webapp/resources/js/components/ant.design/PagedTable/PagedTable.jsx
  src/main/webapp/resources/js/components/icons/Icons.jsx
  src/main/webapp/resources/js/contexts/visibility-context.js
  src/main/webapp/resources/js/pages/admin/components/announcements/AnnouncementAdminPage.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/AnnouncementForm.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/AnnouncementModal.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/AnnouncementUserTable.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/AnnouncementsTable.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/CreateNewAnnouncement.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/DeleteAnnouncement.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/EditAnnouncement.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/ViewAnnouncement.jsx
  src/main/webapp/resources/js/pages/announcement/announcement-users.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/announcements/AnnouncementPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/AnnouncementControlPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/AnnouncementDetailPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/CreateAnnouncementComponent.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/EditAnnouncementComponent.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/ViewAnnouncementComponent.java
Labels: UI

#884 Updated displaying sample details within the cart
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/dto/SampleDetails.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/dto/SampleFiles.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UICartService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/sessionAttrs/Cart.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/samples/samples.js
  src/main/webapp/resources/js/components/CalendarDate.jsx
  src/main/webapp/resources/js/components/SampleDetails/SampleDetails.jsx
  src/main/webapp/resources/js/components/SampleDetails/SampleDetailsLoader.jsx
  src/main/webapp/resources/js/components/SampleDetails/index.js
  src/main/webapp/resources/js/components/SampleDetails/reducer.js
  src/main/webapp/resources/js/components/SampleDetails/sagas.js
  src/main/webapp/resources/js/components/icons/Icons.jsx
  src/main/webapp/resources/js/components/samples/SampleDetailViewer.jsx
  src/main/webapp/resources/js/components/samples/components/SampleDetails.jsx
  src/main/webapp/resources/js/components/samples/components/SampleFiles.jsx
  src/main/webapp/resources/js/components/samples/components/SampleMetadata.jsx
  src/main/webapp/resources/js/components/samples/components/SequenceFileTypeRenderer.jsx
  src/main/webapp/resources/js/components/sequence-files/PairedFileRenderer.jsx
  src/main/webapp/resources/js/components/sequence-files/SequenceFileDetailsRenderer.jsx
  src/main/webapp/resources/js/components/sequence-files/SequenceFileHeader.jsx
  src/main/webapp/resources/js/components/sequence-files/SingleEndFileRenderer.jsx
  src/main/webapp/resources/js/pages/cart/components/Cart.jsx
  src/main/webapp/resources/js/pages/cart/components/CartSamples.jsx
  src/main/webapp/resources/js/pages/cart/components/SampleRenderer.jsx
  src/main/webapp/resources/js/pages/cart/index.js
  src/main/webapp/resources/js/redux/reducers/cart.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/CartPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/SampleDetailsViewer.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/cart/CartPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/samples/SamplesAjaxControllerTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/CartView.xml
Labels: UI, feature

#890 Bump ini to 1.3.7
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: security

#893 Fix for oauth redirect
  src/main/webapp/pages/oauth/access_confirmation.html
  src/main/webapp/resources/js/apis/oauth/oauth.js
Labels: UI, bug

#896 Updated jest to fix node-notifier warning
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: UI, developer

#862 Main navigation upgrade to Ant Design
  CHANGELOG.md
  doc/user/user/dashboard/images/api-list.png
  doc/user/user/dashboard/images/cart.png
  doc/user/user/dashboard/images/dashboard.png
  doc/user/user/dashboard/images/main-menu.png
  doc/user/user/dashboard/images/oauth-approval.png
  doc/user/user/dashboard/images/search-bar.png
  doc/user/user/dashboard/images/settings-panel.png
  doc/user/user/dashboard/images/user-settings.png
  doc/user/user/login/images/irida-dashboard.png
  doc/user/user/pipelines/images/analyses-button.png
  doc/user/user/project/images/synchronize-menu-option.png
  doc/user/user/project/images/your-projects.png
  doc/user/user/user-groups/images/groups-menu.png
  src/main/java/ca/corefacility/bioinformatics/irida/ria/config/WebStylesConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/security/LoginSuccessHandler.java
  src/main/resources/ca/corefacility/bioinformatics/irida/config/styles.properties
  src/main/resources/i18n/messages.properties
  src/main/webapp/.babelrc
  src/main/webapp/package.json
  src/main/webapp/pages/template/main-navigation.html
  src/main/webapp/pages/template/page.html
  src/main/webapp/resources/js/app.js
  src/main/webapp/resources/js/components/AnalysesQueue.jsx
  src/main/webapp/resources/js/components/Buttons/AddNewButton.jsx
  src/main/webapp/resources/js/components/Header/MainNavigation.jsx
  src/main/webapp/resources/js/components/Header/PageHeader.jsx
  src/main/webapp/resources/js/components/Header/main-navigation/components/CartLink.jsx
  src/main/webapp/resources/js/components/Header/main-navigation/components/GlobalSearch.jsx
  src/main/webapp/resources/js/components/Header/main-navigation/style.css
  src/main/webapp/resources/js/components/icons/Icons.jsx
  src/main/webapp/resources/js/pages/analysis/components/Analysis.jsx
  src/main/webapp/resources/js/pages/cart/components/CartToolsMenu.jsx
  src/main/webapp/resources/js/utilities/theme-utilities.js
  src/main/webapp/styles.js
  src/main/webapp/webpack.config.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/SearchResultPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/AbstractPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/cart/CartPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
Labels: UI

#576 Metadata entry reformat
  CHANGELOG.md
  UPGRADING.md
  doc/administrator/upgrades/index.md
  doc/developer/tools/pipelines/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/sample/MetadataTemplateField.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/sample/Sample.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/sample/metadata/MetadataEntry.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/sample/metadata/PipelineProvidedMetadataEntry.java
  src/main/java/ca/corefacility/bioinformatics/irida/pipeline/results/updater/impl/BioHanselSampleUpdater.java
  src/main/java/ca/corefacility/bioinformatics/irida/pipeline/results/updater/impl/SISTRSampleUpdater.java
  src/main/java/ca/corefacility/bioinformatics/irida/plugins/IridaPlugin.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/MetadataEntryRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/MetadataFieldRepositoryImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/LineListController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/dto/UISampleMetadata.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/metadata/ProjectSampleMetadataController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/dto/SampleDetails.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/export/ExportUploadService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/MetadataTemplateServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/SampleServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectSynchronizationService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/sample/MetadataTemplateService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/sample/SampleService.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/samples/RESTSampleMetadataController.java
  src/main/resources/ca/corefacility/bioinformatics/irida/database/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.01/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.01/metadata-entry-refactor.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/sql/required-data.sql
  src/main/resources/scripts/metadata-mappings/metadata-mappings.pl
  src/main/webapp/pages/samples/sample.html
  src/main/webapp/pages/samples/sample_edit.html
  src/test/java/ca/corefacility/bioinformatics/irida/model/SampleTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/pipeline/results/updater/impl/unit/BioHanselSampleUpdaterTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/pipeline/results/updater/impl/unit/SISTRSampleUpdaterTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/samples/SamplesControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectSynchronizationServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/export/ExportUploadServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/sample/SampleServiceImplTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/CartView.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectLineListView.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/MetadataTemplateServiceImplIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/test/integration/TableReset.xml
Labels: back-end, metadata
