Repository phac-nml/irida, pull requests merged in 2020-05, with the labels that each got.

#667 Model and db changes for fast5
  src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/Fast5Object.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectSamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/samples/RESTSampleSequenceFilesController.java
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/20.05/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/20.05/fast5-file-model.xml
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/project/RESTProjectSamplesControllerTest.java
Labels: REST API, back-end

#675 Nanopore fast5 upload and display interface
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplePairer.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesController.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/samples/sample_files.html
  src/main/webapp/resources/js/components/sample/SampleFileUploader.jsx
  src/main/webapp/resources/sass/pages/sample-files.scss
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/samples/SamplePairerTest.java
Labels: UI

#673 Update to global user groups to remove DataTables
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/UserGroupsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/UserGroupTableModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/users/UserGroupsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/datatables/DTProjectMember.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/datatables/DTUserGroup.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIUserGroupsService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/groups/list.html
  src/main/webapp/pages/groups/remove-group-modal.html
  src/main/webapp/resources/js/apis/users/groups.js
  src/main/webapp/resources/js/components/Buttons/RemoveTableItemButton.jsx
  src/main/webapp/resources/js/components/Buttons/index.js
  src/main/webapp/resources/js/components/project-members/ProjectMembersTable.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupsTable.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/index.js
  src/main/webapp/resources/js/pages/users/groups-list.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/groups/GroupsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/groups/GroupsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/UserGroupsControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIUserGroupsServiceTest.java
Labels: UI

#684 Add missing messages key for users.id
  src/main/resources/i18n/messages.properties
Labels: UI, bug

#681 Fix mac upload fastq.gz
  CHANGELOG.md
  src/main/webapp/resources/js/components/sample/SampleFileUploader.jsx
Labels: UI, bug

#689 Analysis provenance fix
  CHANGELOG.md
  src/main/webapp/resources/js/pages/analysis/components/AnalysisProvenance.jsx
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisDetailsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAdminView.xml
  src/test/resources/files/filterStats.txt
Labels: UI

#685 Specific upload method for fast5
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/CoverageFileProcessor.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/DefaultFileProcessingChain.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/FastqcFileProcessor.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/GzipFileProcessor.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplePairer.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/components/sample/SampleFileUploader.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/samples/SampleFilesPage.java
Labels: UI, back-end

#691 Dev primer updates
  CHANGELOG.md
  doc/developer/getting-started/index.md
Labels: documentation

#692 Fast5 types
  src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/Fast5Object.java
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/20.05/fast5-file-model.xml
  src/test/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/unit/Fast5ObjectTest.java
Labels: REST API, back-end

#687 Create new user group using Ant Design
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/UserGroupsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/users/UserGroupsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/exceptions/UIConstraintViolationException.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIUserGroupsService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/package.json
  src/main/webapp/pages/groups/create.html
  src/main/webapp/pages/template/main-navigation.html
  src/main/webapp/resources/js/apis/users/groups.js
  src/main/webapp/resources/js/pages/UserGroupsPage/components/CreateNewUserGroupButton.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupDetailsPage.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupsPage.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupsTable.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/index.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/groups/UserGroupsIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/groups/UserGroupsDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/groups/UserGroupsListingPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/groups/UserGroupsPage.java
Labels: UI

#694 Added documentation for FAST5 data
  CHANGELOG.md
  doc/_includes/tutorials/common/uploading-sample-files.md
  doc/administrator/upgrades/index.md
  doc/developer/rest/index.md
  doc/images/tutorials/common/samples/upload-assembly.png
  doc/images/tutorials/common/samples/upload-sample-file-btn.png
  doc/user/user/samples/index.md
Labels: documentation

#680 updated spring version in getting started docs
  doc/developer/getting-started/index.md
Labels: documentation

#679 Added pipeline plugin link to the readme
  README.md
Labels: documentation

#702 Advanced visualization view fix
  CHANGELOG.md
  src/main/webapp/resources/js/pages/visualizations/phylogenetics/components/app/app.module.js
Labels: UI

#703 Fixes for sample buttons and groups page.
  src/main/webapp/resources/js/components/Header/PageHeader.jsx
  src/main/webapp/resources/js/pages/SamplePage.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupDetailsPage.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupsTable.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/index.js
Labels: UI, bug

#704 Analysis context path
  CHANGELOG.md
  src/main/webapp/resources/js/pages/analysis/components/Analysis.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisError.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisOutputFiles.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisSettings.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisSistr.jsx
  src/main/webapp/resources/js/pages/analysis/index.js
Labels: UI, bug

#700 Added missing translations for project samples date range filter
  src/main/webapp/pages/projects/project_samples.html
Labels: UI, bug

#698 Galaxy fast5 export selector
  doc/_includes/tutorials/common/samples/galaxy-export.md
  doc/images/tutorials/common/samples/cart-galaxy-page.png
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/galaxy/submission.js
  src/main/webapp/resources/js/components/galaxy/GalaxyDetailsForm.jsx
  src/main/webapp/resources/js/components/galaxy/GalaxySubmission.jsx
  src/main/webapp/resources/js/components/galaxy/reducer.js
Labels: UI

#707 Analysis error page galaxy history id link
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysisJobError.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/pages/analysis/components/AnalysisError.jsx
  src/main/webapp/resources/js/pages/analysis/components/jobErrors/GalaxyJobInfo.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisDetailsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAdminView.xml
Labels: enhancement

#705 Outputs width change
  CHANGELOG.md
  src/main/webapp/resources/js/pages/analysis/components/AnalysisPhylogeneticTree.jsx
  src/main/webapp/resources/js/pages/analysis/components/outputs/OutputFilePreview.jsx
Labels: UI

#708 Disbale fastqc zipped
  src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/Fast5Object.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/FileProcessor.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/AutomatedAnalysisFileProcessor.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/DefaultFileProcessingChain.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/FastqcFileProcessor.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/GzipFileProcessor.java
  src/test/java/ca/corefacility/bioinformatics/irida/processing/impl/unit/AutomatedAnalysisFileProcessorTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/processing/impl/unit/FastqcFileProcessorTest.java
Labels: back-end

#712 Fix file upload styles
  src/main/webapp/resources/sass/pages/sample-files.scss
Labels: UI, bug

#710 Added navbar button for base admin panel
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/admin/AdminBaseController.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/admin/index.html
  src/main/webapp/pages/template/main-navigation.html
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/admin/AdminPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/admin/AdminPage.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/admin/AdminPageView.xml
Labels: UI
