Repository phac-nml/irida, pull requests merged in 2020-03, with the labels that each got.

#603 Generic sequencing runs
  CHANGELOG.md
  UPGRADING.md
  doc/developer/rest/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/run/MiseqRun.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/run/SequencingRun.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/exception/ControllerExceptionHandler.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/sequencingrun/RESTSequencingRunController.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/sequencingrun/RESTSequencingRunSequenceFilesController.java
  src/main/resources/ValidationMessages.properties
  src/main/resources/ca/corefacility/bioinformatics/irida/database/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/20.05/add-generic-sequencing-runs.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/20.05/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/sql/required-data.sql
  src/main/webapp/pages/sequencingRuns/details.html
  src/main/webapp/pages/sequencingRuns/sequencers.html
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/sequencingRuns/SequencingRunDetailsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/SequencingRunControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/SequencingRunSequenceFilesControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/SequencingRunServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/SequencingObjectServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/integration/sequencingrun/SequencingRunIT.java
  src/test/resources/ca/corefacility/bioinformatics/irida/model/enums/analysis/integration/SNVPhyl/SNVPhylAnalysisIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/repositories/analysis/AnalysisRepositoryIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAdminView.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/sequencingRuns/SequencingRunsPagesIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/AnalysisServiceImplIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/SequenceFileServiceImplIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/SequencingRunServiceImplIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceIT.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/test/integration/TableReset.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/web/controller/test/integration/sequencingrun/SequencingRunIntegrationTest.xml
Labels: REST API, UI, back-end

#620 Updated jetty plugin to 9.4.24.v20191120
  CHANGELOG.md
  pom.xml
Labels: developer

#583 Remote api remove datatables
  CHANGELOG.md
  doc/user/administrator/images/add-api.png
  doc/user/administrator/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/ant/table/TableModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/ant/table/TableRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/ant/table/TableResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/tables/TableRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/oauth/RemoteAPIAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/oauth/RemoteAPIController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/ProjectModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/ProjectsResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/rempoteapi/dto/RemoteAPITableModel.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/remote_apis/fragments.html
  src/main/webapp/pages/remote_apis/list.html
  src/main/webapp/pages/remote_apis/parent_reload.html
  src/main/webapp/resources/js/apis/remote-api/remote-api.js
  src/main/webapp/resources/js/pages/announcement/AnnouncementAdminPage.jsx
  src/main/webapp/resources/js/pages/clients/ClientsPage.jsx
  src/main/webapp/resources/js/pages/clients/ClientsTable.jsx
  src/main/webapp/resources/js/pages/projects/list/ProjectsTable.jsx
  src/main/webapp/resources/js/pages/remote-apis/RemoteApiPage.jsx
  src/main/webapp/resources/js/pages/remote-apis/RemoteApiStatus.jsx
  src/main/webapp/resources/js/pages/remote-apis/RemoteApiTable.jsx
  src/main/webapp/resources/js/pages/remote-apis/remote-apis-list.js
  src/main/webapp/webpack.config.prod.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/remoteapi/RemoteAPIDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/remoteapi/RemoteAPIsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/remoteapi/RemoteAPIsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/RemoteAPIAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/RemoteAPIControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/integration/project/ProjectSamplesIT.java
Labels: UI

#623 Refactor admin users list to ant design
  CHANGELOG.md
  doc/user/administrator/images/users-list.png
  doc/user/administrator/includes/start-from-the-user-list.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/AdminUsersService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/users/AdminUsersAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/users/UsersController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/users/dto/AdminUsersTableRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/users/dto/UserTableModel.java
  src/main/resources/ca/corefacility/bioinformatics/irida/sql/required-data.sql
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/template/page.html
  src/main/webapp/pages/user/list.html
  src/main/webapp/resources/js/apis/users/users.js
  src/main/webapp/resources/js/components/ant.design/PagedTable/PagedTable.jsx
  src/main/webapp/resources/js/components/ant.design/table-renderers.js
  src/main/webapp/resources/js/pages/AdminUsersPage.jsx
  src/main/webapp/resources/js/pages/users/users-list.js
  src/main/webapp/resources/sass/app.scss
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/AntTable.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/AdminUsersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/user/UsersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/users/AdminUsersPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/users/UsersPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/UsersControllerTest.java
Labels: UI

#626 Remove DataTables from overrepresented sequences for sequencing files
  CHANGELOG.md
  src/main/webapp/entries.js
  src/main/webapp/pages/sequenceFiles/file_overrepresented.html
  src/main/webapp/resources/js/pages/sequence-files/overrepresented.js
Labels: UI

#624 Rest api assemblies
  CHANGELOG.md
  doc/developer/rest/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/assembly/GenomeAssembly.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/assembly/GenomeAssemblyFromAnalysis.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/irida/IridaProject.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/irida/IridaSample.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/irida/IridaSequenceFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/irida/IridaSequenceFilePair.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/irida/IridaSingleEndSequenceFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/project/Project.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/sample/Sample.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/SequenceFilePair.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/SingleEndSequenceFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplePairer.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/analysis/workspace/galaxy/AnalysisCollectionServiceGalaxy.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectSamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/samples/RESTSampleAssemblyController.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/spring/view/FastaView.java
  src/main/resources/ca/corefacility/bioinformatics/irida/sql/required-data.sql
  src/main/webapp/pages/samples/sample_files.html
  src/test/java/ca/corefacility/bioinformatics/irida/service/analysis/workspace/galaxy/impl/integration/AnalysisCollectionServiceGalaxyIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/integration/sample/RESTSampleAssemblyControllerIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/project/RESTProjectSamplesControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/samples/RESTSampleAssemblyControllerTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/web/controller/test/integration/sample/RESTSampleAssemblyControllerIT.xml
Labels: REST API, developer

#625 Antd v4 including update analysis pages.
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/LineListController.java
  src/main/webapp/package.json
  src/main/webapp/pages/oauth/access_confirmation.html
  src/main/webapp/resources/js/components/AnalysesTable/AnalysesTable.jsx
  src/main/webapp/resources/js/components/Header/Breadcrumbs.jsx
  src/main/webapp/resources/js/components/OutputFiles/OutputFileHeader.jsx
  src/main/webapp/resources/js/components/ant.design/PagedTable/PagedTable.jsx
  src/main/webapp/resources/js/components/ant.design/PagedTable/PagedTableContext.js
  src/main/webapp/resources/js/components/ant.design/table-renderers.js
  src/main/webapp/resources/js/components/icons/Icons.jsx
  src/main/webapp/resources/js/components/icons/Running.jsx
  src/main/webapp/resources/js/components/icons/Warning.jsx
  src/main/webapp/resources/js/pages/AdminUsersPage.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisTabularPreview.jsx
  src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisReferenceFileRenderer.jsx
  src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisSampleRenderer.jsx
  src/main/webapp/resources/js/pages/cart/components/CartToolsMenu.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/SaveTemplateModal.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/TemplateSelect/SaveTemplateButton.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/TemplateSelect/TemplateSelect.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/TemplateSelect/TemplateSelectOption.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/TemplatesPanel.jsx
  src/main/webapp/resources/js/pages/projects/linelist/reducers/templates.js
  src/main/webapp/resources/js/pages/projects/samples/linker/Linker.jsx
  src/main/webapp/resources/js/pages/remote-apis/RemoteApiStatus.jsx
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/AntTable.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/AdminUsersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/CreateAnnouncementComoponent.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/AssociatedProjectPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectLineListPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/remoteapi/CreateRemoteAPIPageIT.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/oauth/CreateRemoteApisIT.xml
Labels: UI
