Repository phac-nml/irida, pull requests merged in 2020-08, with the labels that each got.

#763 Update create sample in project
  CHANGELOG.md
  doc/_includes/tutorials/common/creating-a-sample.md
  doc/images/tutorials/common/samples/add-sample-button.png
  doc/images/tutorials/common/samples/add-sample.gif
  doc/images/tutorials/common/samples/create-sample-page-create.png
  doc/images/tutorials/common/samples/create-sample-page-organism.png
  doc/images/tutorials/common/samples/create-sample-page.png
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/CreateSampleErrorResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/CreateSampleRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/CreateSampleResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/CreateSampleSuccessResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/SampleNameValidationResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/ProjectSamplesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectSampleService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/package.json
  src/main/webapp/pages/projects/project_add_sample.html
  src/main/webapp/pages/projects/project_samples.html
  src/main/webapp/resources/js/apis/projects/samples.js
  src/main/webapp/resources/js/hooks/useDebounce.js
  src/main/webapp/resources/js/pages/projects/project-add-samples.js
  src/main/webapp/resources/js/pages/projects/samples/add-sample/AddSampleButton.jsx
  src/main/webapp/resources/js/pages/projects/samples/project-samples.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectAddSamplePage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectAddSamplePageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
Labels: UI

#758 Fixed user groups redirect routing
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/UserGroupsController.java
  src/main/webapp/pages/admin/index.html
  src/main/webapp/resources/js/contexts/UserGroupsContext.js
  src/main/webapp/resources/js/pages/UserGroupsPage/components/CreateNewUserGroupButton.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupDetailsPage.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupMembersTable.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupsPage.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupsTable.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/index.js
  src/main/webapp/resources/js/pages/admin/components/Admin.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminSideMenu.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminUserGroupsPage.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/groups/UserGroupsIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/groups/UserGroupsDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/groups/UserGroupsListingPage.java
Labels: UI

#769 Removed broken XML content/accept types from REST API
  CHANGELOG.md
  doc/developer/rest/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/config/web/IridaRestApiWebConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/assembler/resource/LabelledRelationshipResource.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/assembler/resource/ResourceCollection.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/assembler/resource/RootResource.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/RESTGenericController.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/RESTRootController.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/exception/ControllerExceptionHandler.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectSamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/sequencingrun/RESTSequencingRunController.java
Labels: REST API

#772 Project add new sample test timing
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
Labels: test

#774 Added Create New Project button
  CHANGELOG.md
  doc/_includes/tutorials/common/creating-a-project.md
  doc/_includes/tutorials/common/images/create-new-project-btn.png
  doc/_includes/tutorials/common/images/create-new-project.png
  doc/_includes/tutorials/common/images/your-projects.png
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/template/main-navigation.html
  src/main/webapp/resources/js/pages/projects/list/ProjectsTable.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectsPageIT.java
Labels: UI

#773 Fixes project > "Add User Group" button displayed to collaborators.
  src/main/webapp/resources/js/components/project-user-groups/AddGroupButton.jsx
  src/main/webapp/resources/js/components/project-user-groups/ProjectUserGroupsTable.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectUserGroupsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectUserGroupsPageIT.java
Labels: UI, bug

#781 Admin documentation
  doc/_includes/tutorials/clients/creating-a-client.md
  doc/_includes/tutorials/clients/start-from-the-clients-list.md
  doc/_includes/tutorials/common/creating-a-user-account.md
  doc/_includes/tutorials/common/creating-a-user-group.md
  doc/_includes/tutorials/common/managing-user-groups.md
  doc/images/tutorials/common/users/add-user-groups-button.png
  doc/images/tutorials/common/users/create-user-menu.png
  doc/images/tutorials/common/users/edit-user-group-details.png
  doc/images/tutorials/common/users/user-group-details-link.png
  doc/images/tutorials/common/users/user-group-details-remove-user-modal.png
  doc/images/tutorials/common/users/user-group-details-remove-user.png
  doc/images/tutorials/common/users/user-group-details-role.png
  doc/images/tutorials/common/users/user-group-details.png
  doc/images/tutorials/common/users/user-groups-list.png
  doc/user/administrator/images/add-announcement-button.png
  doc/user/administrator/images/add-announcement.png
  doc/user/administrator/images/add-client-button.png
  doc/user/administrator/images/add-user-button.png
  doc/user/administrator/images/admin-panel-navbar-button.png
  doc/user/administrator/images/admin-panel.png
  doc/user/administrator/images/announcement-details-link.png
  doc/user/administrator/images/announcement-details.png
  doc/user/administrator/images/announcements-home-page.png
  doc/user/administrator/images/announcements-side-menu.png
  doc/user/administrator/images/client-details-link.png
  doc/user/administrator/images/clients-side-menu.png
  doc/user/administrator/images/ncbi-exports-list.png
  doc/user/administrator/images/ncbi-exports-side-menu.png
  doc/user/administrator/images/remote-api-list.png
  doc/user/administrator/images/remote-api-side-menu.png
  doc/user/administrator/images/reset-password-success.png
  doc/user/administrator/images/sequencing-runs-details-link.png
  doc/user/administrator/images/sequencing-runs-list.png
  doc/user/administrator/images/sequencing-runs-side-menu.png
  doc/user/administrator/images/user-groups-side-menu.png
  doc/user/administrator/images/users-side-menu.png
  doc/user/administrator/includes/select-a-specific-client.md
  doc/user/administrator/includes/start-from-the-user-list.md
  doc/user/administrator/index.md
  doc/user/tutorials/sharing/index.md
  doc/user/user/user-groups/images/group-search.png
  doc/user/user/user-groups/index.md
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/pages/admin/components/Admin.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminRemoteApiPage.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminSideMenu.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminStatistics.jsx
  src/main/webapp/resources/js/pages/admin/routes.js
  src/main/webapp/resources/js/pages/remote-apis/RemoteApiPage.jsx
  src/main/webapp/resources/js/pages/remote-apis/RemoteApiTable.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/admin/AdminPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/admin/AdminPage.java
Labels: UI, documentation

#785 Updated icons next to analysis name on the analysis details page
  src/main/webapp/resources/js/components/icons/Error.jsx
  src/main/webapp/resources/js/components/icons/Icons.jsx
  src/main/webapp/resources/js/components/icons/Success.jsx
  src/main/webapp/resources/js/pages/analysis/components/Analysis.jsx
  src/main/webapp/yarn.lock
Labels: UI

#727 Added viewer listing to analysis service
  CHANGELOG.md
  doc/developer/tools/pipelines/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/config/workflow/IridaAnalysisTypesServiceConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/plugins/IridaPlugin.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/AnalysisTypesService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/AnalysisTypesServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/util/ToolsListExporter.java
  src/main/webapp/pages/analysis.html
  src/main/webapp/resources/js/contexts/AnalysisContext.js
  src/main/webapp/resources/js/pages/analysis/components/Analysis.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysesListingServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysisControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/workflow/unit/IridaWorkflowLoaderServiceTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAdminView.xml
Labels: UI, developer, tools

#786 Auto update analysis progress
  CHANGELOG.md
  doc/user/user/pipelines/images/updated-progress.png
  doc/user/user/pipelines/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/UpdatedAnalysisProgress.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/webapp/resources/js/apis/analysis/analysis.js
  src/main/webapp/resources/js/contexts/AnalysisContext.js
  src/main/webapp/resources/js/contexts/AnalysisDetailsContext.js
  src/main/webapp/resources/js/hooks/useInterval.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysisAjaxControllerTest.java
Labels: UI, enhancement

#784 Admin create client
  doc/images/tutorials/clients/client-details.png
  doc/user/administrator/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/ClientsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/CreateSampleErrorResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/CreateSampleResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/CreateSampleSuccessResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/ajax/AjaxCreateItemResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/ajax/AjaxErrorResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/ajax/AjaxResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/clients/ClientTableModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/clients/ClientTableRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/clients/CreateClientRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/ProjectSamplesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIClientService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectSampleService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/IridaClientDetailsService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/IridaClientDetailsServiceImpl.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/clients/clients.js
  src/main/webapp/resources/js/components/popovers/HelpPopover.jsx
  src/main/webapp/resources/js/pages/admin/components/clients/add/AddClientButton.jsx
  src/main/webapp/resources/js/pages/admin/components/clients/add/AddClientModal.jsx
  src/main/webapp/resources/js/pages/admin/components/clients/constants.js
  src/main/webapp/resources/js/pages/admin/components/clients/listing/ClientListingPage.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIClientServiceTest.java
Labels: UI, feature

#787 AnalysisSteps state update
  doc/user/user/pipelines/index.md
  src/main/webapp/resources/js/contexts/AnalysisContext.js
  src/main/webapp/resources/js/pages/analysis/components/AnalysisSteps.jsx
Labels: UI
