Repository phac-nml/irida, pull requests merged in 2020-07, with the labels that each got.

#746 NCBI Exports replace DataTables with Ant Design Table
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/NcbiExportSubmissionAdminTableModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/NcbiExportSubmissionTableModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/export/NCBIAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UINcbiService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/export/NcbiExportSubmissionServiceImpl.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/projects/export/admin.html
  src/main/webapp/pages/projects/export/list.html
  src/main/webapp/resources/js/admin/ncbi-exports/AdminNcbiExports.jsx
  src/main/webapp/resources/js/admin/ncbi-exports/AdminNcbiExportsTable.jsx
  src/main/webapp/resources/js/admin/ncbi-exports/index.js
  src/main/webapp/resources/js/apis/ncbi/ncbi.js
  src/main/webapp/resources/js/components/ncbi/export-table/NcbiExportTable.jsx
  src/main/webapp/resources/js/components/ncbi/upload-states/NcbiUploadStates.jsx
  src/main/webapp/resources/js/components/ncbi/upload-states/index.js
  src/main/webapp/resources/js/pages/projects/export/ncbi-export.js
  src/main/webapp/resources/js/pages/projects/ncbi-export.js
  src/main/webapp/resources/js/pages/projects/ncbi-export/index.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/NcbiExportsListingPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/NcbiExportsListingPageIT.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/projects/NcbiExportsListingPageIT.xml
Labels: UI

#749 Remove older irida.cart.js angularjs service
  CHANGELOG.md
  src/main/webapp/resources/js/app.js
  src/main/webapp/resources/js/modules/cart/irida.cart.js
  src/main/webapp/resources/js/pages/pipelines/pipeline.launch.js
  src/main/webapp/yarn.lock
Labels: UI, developer

#751 Fixes the toggles for viewing metadata on the advanced phylogentic veiwer.
  CHANGELOG.md
  doc/user/user/analysis-visualizations/images/toggle_metadatafield.png
  doc/user/user/analysis-visualizations/images/toggle_metadatafield_after.png
  doc/user/user/analysis-visualizations/index.md
  src/main/resources/i18n/messages.properties
  src/main/webapp/package.json
  src/main/webapp/pages/analysis/visualizations/phylocanvas-metadata.html
  src/main/webapp/resources/js/pages/visualizations/phylogenetics/components/metadata/metadata.module.js
  src/main/webapp/resources/js/vendor/plugins/angular/angular-bootstrap-switch.js
  src/main/webapp/yarn.lock
Labels: UI, bug

#743 Porting pages to Admin Panel
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/admin/AdminBaseController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/announcements/AnnouncementAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/announcements/AnnouncementsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/clients/ClientsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/clients/ClientsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAnnouncementsService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/announcements/details.html
  src/main/webapp/pages/template/main-navigation.html
  src/main/webapp/resources/js/pages/admin/components/Admin.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminRemoteApiPage.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminSequencingRunsPage.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminSideMenu.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminUsersPage.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/AnnouncementAdminPage.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/AnnouncementsTable.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/CreateNewAnnouncement.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/DeleteAnnouncement.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/EditAnnouncement.jsx
  src/main/webapp/resources/js/pages/admin/components/clients/ClientsPage.jsx
  src/main/webapp/resources/js/pages/admin/components/clients/ClientsTable.jsx
  src/main/webapp/resources/js/pages/admin/components/clients/listing/ClientListingPage.jsx
  src/main/webapp/resources/js/pages/admin/components/clients/listing/ClientsTables.jsx
  src/main/webapp/resources/js/pages/admin/routes.js
  src/main/webapp/resources/js/pages/clients/ClientsPage.jsx
  src/main/webapp/resources/js/pages/remote-apis/RemoteApiPage.jsx
  src/main/webapp/resources/js/pages/sequencing-runs/SequencingRunsPage.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/admin/AdminPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/admin/AdminPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/AnnouncementControlPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/clients/ClientDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/clients/ClientsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/ClientsAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/ClientsControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/announcements/AnnouncementsAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/announcements/AnnouncementsControllerTest.java
Labels: UI

#752 Admin port ncbi
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/template/main-navigation.html
  src/main/webapp/resources/js/admin/ncbi-exports/AdminNcbiExports.jsx
  src/main/webapp/resources/js/admin/ncbi-exports/index.js
  src/main/webapp/resources/js/pages/admin/components/Admin.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminSideMenu.jsx
  src/main/webapp/resources/js/pages/admin/components/ncbi-exports/AdminNcbiExportsPage.jsx
  src/main/webapp/resources/js/pages/admin/components/ncbi-exports/AdminNcbiExportsTable.jsx
  src/main/webapp/resources/js/pages/admin/routes.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/admin/AdminPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/admin/AdminPage.java
Labels: UI

#750 Remove global angular `irida`
  CHANGELOG.md
  src/main/webapp/entries.js
  src/main/webapp/pages/analysis/visualizations/phylocanvas-metadata.html
  src/main/webapp/pages/announcements/details.html
  src/main/webapp/pages/events/admin.html
  src/main/webapp/pages/index.html
  src/main/webapp/pages/pipelines/types/generic_pipeline.html
  src/main/webapp/pages/projects/export/ncbi.html
  src/main/webapp/pages/projects/project_details.html
  src/main/webapp/pages/projects/project_new.html
  src/main/webapp/pages/projects/project_samples_metadata_upload.html
  src/main/webapp/pages/projects/project_sync.html
  src/main/webapp/pages/projects/settings/pages/references.html
  src/main/webapp/pages/samples/_base.html
  src/main/webapp/pages/samples/sample_files.html
  src/main/webapp/pages/template/base.html
  src/main/webapp/pages/template/page.html
  src/main/webapp/resources/js/app.js
  src/main/webapp/resources/js/pages/activities/activities.js
  src/main/webapp/resources/js/pages/announcement/announcement-read.js
  src/main/webapp/resources/js/pages/dashboard.js
  src/main/webapp/resources/js/pages/pipelines/pipeline.launch.js
  src/main/webapp/resources/js/pages/projects/project-events.js
  src/main/webapp/resources/js/pages/projects/project-reference-files.js
  src/main/webapp/resources/js/pages/projects/project-sync.js
  src/main/webapp/resources/js/pages/projects/projects-new.js
  src/main/webapp/resources/js/pages/projects/samples-metadata-import/index.js
  src/main/webapp/resources/js/pages/samples/sample-files.js
  src/main/webapp/resources/js/pages/visualizations/phylogenetics/index.js
  src/main/webapp/webpack.config.js
Labels: UI, developer

#756 Upgrade ant design v4.4.2
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupDetailsPage.jsx
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/groups/UserGroupsDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/AssociatedProjectPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
Labels: UI

#748 Create metadata template
  src/main/java/ca/corefacility/bioinformatics/irida/model/sample/MetadataTemplate.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/NewMetadataTemplateRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/metadata/MetadataTemplatesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIMetadataTemplateService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/metadata/metadata-templates.js
  src/main/webapp/resources/js/components/metadata-template/create-template/index.js
  src/main/webapp/resources/js/components/metadata-template/list/index.js
  src/main/webapp/resources/js/pages/projects/metadata-templates/index.js
  src/main/webapp/yarn.lock
Labels: UI

#650 Object store/ base
  src/main/java/ca/corefacility/bioinformatics/irida/config/services/IridaApiServicesConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/VersionedFileFields.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/assembly/GenomeAssembly.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/irida/IridaSequenceFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/project/ReferenceFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/Fast5Object.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/SequenceFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/AnalysisOutputFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/concatenate/SequencingObjectConcatenator.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/concatenate/SequencingObjectConcatenatorFactory.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/concatenate/impl/SequenceFilePairConcatenator.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/concatenate/impl/SingleEndSequenceFileConcatenator.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/ChecksumFileProcessor.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/DefaultFileProcessingChain.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/FastqcFileProcessor.java
  src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/GzipFileProcessor.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/analysis/AnalysisOutputFileRepositoryImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/assembly/GenomeAssemblyRepositoryImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/FilesystemSupplementedRepositoryImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageLocalUtilityImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageUtility.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/referencefile/ReferenceFileRepositoryImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/sequencefile/SequenceFileRepositoryImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectReferenceFileController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/sequencingRuns/SequencingRunController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/sequencingRuns/dto/SequenceFileDetails.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/sequencingRuns/dto/SequencingObjectDetails.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/SequencingObjectServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/util/FileUtils.java
  src/main/java/ca/corefacility/bioinformatics/irida/util/IridaFiles.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/assembler/resource/sequencefile/SequenceFileResource.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/samples/RESTSampleSequenceFilesController.java
  src/main/resources/ca/corefacility/bioinformatics/irida/config/filesystem.properties
  src/main/webapp/pages/samples/sample_files.html
  src/test/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/unit/Fast5ObjectTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/processing/concatenate/SequencingObjectConcatenatorFactoryTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/processing/concatenate/impl/SequenceFilePairConcatenatorTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/processing/concatenate/impl/SingleEndSequenceFileConcatenatorTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/processing/impl/unit/ChecksumFileProcessorTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/processing/impl/unit/DefaultFileProcessingChainTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/processing/impl/unit/FastqcFileProcessorTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/processing/impl/unit/GzipFileProcessorTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/SequenceFileRepositoryImplTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/TestDataFactory.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/pipelines/PipelineControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectSamplesControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/security/permissions/analysis/ReadAnalysisSubmissionPermissionTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/SequencingObjectServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/TestDataFactory.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/samples/SampleSequenceFilesControllerTest.java
Labels: back-end, enhancement, feature

#766 Updated babel-env to fix issue with security vulnerability elliptic
  .travis.yml
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: dependencies
