Repository phac-nml/irida, pull requests merged in 2020-10, with the labels that each got.

#809 HOTFIX: Fixed removal of sequencing runs
  CHANGELOG.md
  UPGRADING.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/SistrResult.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/resources/js/pages/analysis/components/AnalysisSistr.jsx
  src/main/webapp/resources/js/pages/analysis/components/sistr/CgMlst.jsx
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisDetailsPageIT.java
Labels: UI, bug

#816 Spellcheck documentation
  doc/developer/getting-started/index.md
Labels: documentation

#813 Cart server refactor
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/config/web/IridaUIWebConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/CartAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/CartSampleModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/cart/CartProjectModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/CartController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/CartGalaxyController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/components/Cart.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/dto/AddToCartRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/dto/CartSample.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UICartService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/sessionAttrs/Cart.java
  src/main/webapp/resources/js/apis/cart/cart.js
  src/main/webapp/resources/js/pages/cart/components/CartSamples.jsx
  src/main/webapp/resources/js/pages/cart/components/SampleRenderer.jsx
  src/main/webapp/resources/js/pages/pipelines/pipeline.launch.js
  src/main/webapp/resources/js/pages/projects/samples/project-samples.js
  src/main/webapp/resources/js/redux/reducers/cart.js
  src/main/webapp/resources/js/redux/sagas/cart.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/TestDataFactory.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/CartControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/pipelines/PipelineControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectsControllerTest.java
Labels: developer

#821 Hotfix manage remote api
  CHANGELOG.md
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/RemoteAPIAjaxController.java
  src/main/webapp/pages/oauth/access_confirmation.html
  src/main/webapp/resources/js/apis/oauth/oauth.js
  src/main/webapp/resources/js/pages/admin/components/remote-connections/RemoteApiStatus.jsx
  src/main/webapp/resources/js/pages/admin/components/remote-connections/RemoteApiTable.jsx
  src/main/webapp/resources/js/pages/remote-apis/remote-apis.js
  src/main/webapp/resources/js/utilities/role-utilities.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/AddMemberButton.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/groups/UserGroupsListingPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/remoteapi/RemoteAPIsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/remoteapi/RemoteAPIsPageIT.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/oauth/RemoteApisIT.xml
Labels: bug

#824 Admin Stats UI
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/admin/AdminStatisticsAjaxController.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/package.json
  src/main/webapp/resources/js/apis/admin/admin.js
  src/main/webapp/resources/js/contexts/statistics-context.js
  src/main/webapp/resources/js/pages/admin/chart-config.js
  src/main/webapp/resources/js/pages/admin/components/Admin.jsx
  src/main/webapp/resources/js/pages/admin/components/AdminSideMenu.jsx
  src/main/webapp/resources/js/pages/admin/components/statistics/AdvancedStatistics.jsx
  src/main/webapp/resources/js/pages/admin/components/statistics/BasicStats.jsx
  src/main/webapp/resources/js/pages/admin/components/statistics/ChartTypeButtons.jsx
  src/main/webapp/resources/js/pages/admin/components/statistics/TimePeriodSelect.jsx
  src/main/webapp/resources/js/pages/admin/index.js
  src/main/webapp/resources/js/pages/admin/routes.js
  src/main/webapp/resources/js/pages/admin/statistics-constants.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/admin/AdminPageIT.java
Labels: UI

#829 Pipeline Launch: Basics
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/PipelineAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/ajax/AjaxResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/launch/UIPipelineDetailsResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/LaunchController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UICartService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineService.java
  src/main/webapp/entries.js
  src/main/webapp/pages/entry.html
  src/main/webapp/resources/js/apis/pipelines/pipelines.js
  src/main/webapp/resources/js/components/pipeline/Pipeline.jsx
  src/main/webapp/resources/js/pages/launch/LaunchPage.jsx
  src/main/webapp/resources/js/pages/launch/LaunchPageHeader.jsx
  src/main/webapp/resources/js/pages/launch/index.js
  src/main/webapp/resources/js/pages/launch/launch-context.js
Labels: UI, feature

#693 Invoke workflow
  CHANGELOG.md
  lib/blend4j-0.2.1-2201df9.jar
  lib/blend4j-0.2.1-2201df9.pom
  lib/install-libs.sh
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/config/services/scheduled/AnalysisScheduledTaskConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/execution/galaxy/WorkflowInputsGalaxy.java
  src/main/java/ca/corefacility/bioinformatics/irida/pipeline/upload/galaxy/GalaxyWorkflowService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/analysis/workspace/AnalysisWorkspaceService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/analysis/workspace/galaxy/AnalysisParameterServiceGalaxy.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/analysis/workspace/galaxy/AnalysisWorkspaceServiceGalaxy.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/AnalysisExecutionScheduledTaskImpl.java
  src/test/java/ca/corefacility/bioinformatics/irida/model/enums/analysis/integration/SNVPhylAnalysisIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/pipeline/upload/galaxy/integration/GalaxyJobErrorsServiceIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/pipeline/upload/galaxy/integration/GalaxyWorkflowsIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/pipeline/upload/galaxy/integration/LocalGalaxy.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/analysis/workspace/galaxy/impl/integration/AnalysisWorkspaceServiceGalaxyIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/analysis/workspace/galaxy/impl/unit/AnalysisParameterServiceGalaxyTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/analysis/workspace/galaxy/impl/unit/AnalysisWorkspaceServiceGalaxyTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/AnalysisExecutionScheduledTaskImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/AnalysisExecutionScheduledTaskImplTest.java
Labels: tools

#836 Remove resolve-url-loader
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: UI, security

#839 Remove bootstap sass
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: UI

#842 Fixed last login bug
  CHANGELOG.md
  src/main/webapp/resources/js/components/ant.design/table-renderers.js
Labels: UI, bug
