Repository phac-nml/irida, pull requests merged in 2020-09, with the labels that each got.

#790 Fix OAuth2 redirect url builder
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/oauth/OltuAuthorizationController.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/OltuAuthorizationControllerTest.java
Labels: REST API, bug, federation

#789 Removed page variables for analysis and updated to use ajax to get an…
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysisInfo.java
  src/main/webapp/pages/analysis.html
  src/main/webapp/resources/js/apis/analysis/analysis.js
  src/main/webapp/resources/js/contexts/AnalysisContext.js
  src/main/webapp/resources/js/contexts/AnalysisDetailsContext.js
  src/main/webapp/resources/js/contexts/AnalysisOutputsContext.js
  src/main/webapp/resources/js/contexts/AnalysisSamplesContext.js
  src/main/webapp/resources/js/pages/analysis/components/Analysis.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisBioHansel.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisError.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisJsonPreview.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisOutputFiles.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisPhylogeneticTree.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisProvenance.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisSettings.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisSistr.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisSteps.jsx
  src/main/webapp/resources/js/pages/analysis/components/jobErrors/GalaxyJobInfo.jsx
  src/main/webapp/resources/js/pages/analysis/components/outputs/OutputFilePreview.jsx
  src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisDelete.jsx
  src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisDetails.jsx
  src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisShare.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisDetailsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysisAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysisControllerTest.java
Labels: UI

#661 Rest project sample add graceful
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/exceptions/ExistingSampleNameException.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/ProjectServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectSamplesController.java
  src/main/resources/i18n/messages.properties
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/integration/project/ProjectSamplesIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/project/RESTProjectSamplesControllerTest.java
Labels: REST API

#788 Added polling to update state and duration of an analysis to the anal…
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/UpdatedAnalysisTableProgress.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysesTableAjaxController.java
  src/main/webapp/resources/js/apis/analysis/analysis.js
  src/main/webapp/resources/js/components/AnalysesQueue.jsx
  src/main/webapp/resources/js/components/AnalysesTable/AnalysesTable.jsx
  src/main/webapp/resources/js/components/AnalysesTable/AnalysisDownloadButton.jsx
  src/main/webapp/resources/js/components/AnalysesTable/AnalysisDuration.jsx
  src/main/webapp/resources/js/components/AnalysesTable/AnalysisState.jsx
  src/main/webapp/resources/js/contexts/AnalysesTableContext.js
  src/main/webapp/resources/js/pages/analyses/AnalysesPage.jsx
Labels: UI

#800 Redirect to client details page after creation.
  src/main/webapp/resources/js/apis/clients/clients.js
  src/main/webapp/resources/js/pages/admin/components/clients/add/AddClientModal.jsx
Labels: UI

#797 Fix remote oauth remote connection details
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/RemoteAPIAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/RemoteAPIModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/oauth/RemoteAPIAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/oauth/RemoteAPIController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIRemoteAPIService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/remote_apis/create.html
  src/main/webapp/pages/remote_apis/remote_api_details.html
  src/main/webapp/resources/js/apis/remote-api/remote-api.js
  src/main/webapp/resources/js/pages/admin/components/Admin.jsx
  src/main/webapp/resources/js/pages/admin/components/remote-connections/AdminRemoteApiPage.jsx
  src/main/webapp/resources/js/pages/admin/components/remote-connections/RemoteApiStatus.jsx
  src/main/webapp/resources/js/pages/admin/components/remote-connections/RemoteApiTable.jsx
  src/main/webapp/resources/js/pages/admin/components/remote-connections/RemoteConnectionDetails.jsx
  src/main/webapp/resources/js/pages/remote-apis/RemoteApiPage.jsx
  src/main/webapp/resources/js/pages/remote-apis/remote-api-details.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/remoteapi/RemoteAPIDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSyncPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/remoteapi/CreateRemoteAPIPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/remoteapi/RemoteAPIDetailsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/utilities/RemoteApiUtilities.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/RemoteAPIAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/RemoteAPIControllerTest.java
Labels: UI

#801 Fix remoate oath create remote project
  CHANGELOG.md
  doc/user/user/project/images/synchronize-connect-api.png
  doc/user/user/project/images/synchronize-details.png
  doc/user/user/project/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/CreateRemoteProjectRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/RemoteAPIAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/RemoteProjectModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIRemoteAPIService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/package.json
  src/main/webapp/pages/projects/project_sync.html
  src/main/webapp/pages/remote_apis/create.html
  src/main/webapp/resources/js/apis/remote-api/remote-api.js
  src/main/webapp/resources/js/components/project/ProjectNav.jsx
  src/main/webapp/resources/js/components/remote-api/CreateRemoteProjectSyncForm.jsx
  src/main/webapp/resources/js/components/remote-api/SyncFrequencySelect.jsx
  src/main/webapp/resources/js/pages/admin/components/remote-connections/RemoteApiStatus.jsx
  src/main/webapp/resources/js/pages/projects/project-sync.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSyncPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSyncPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectsControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIRemoteAPIServiceTest.java
Labels: UI

#793 Update assembly pipeline (which finishes migrating all tools away from IRIDA toolshed)
  CHANGELOG.md
  UPGRADING.md
  doc/_includes/administrator/galaxy/pipelines/shovill-1.0.4.md
  doc/administrator/galaxy/index.md
  doc/administrator/galaxy/pipelines/assembly-annotation-collection/index.md
  doc/administrator/galaxy/pipelines/assembly-annotation/index.md
  doc/administrator/galaxy/pipelines/test/assembly-annotation/assembly-annotation.ga
  docker/virtual-machine/Dockerfile
  docker/virtual-machine/data/tools-list.yml
  src/main/resources/ca/corefacility/bioinformatics/irida/config/workflows.properties
  src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/AssemblyAnnotation/0.6/irida_workflow.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/AssemblyAnnotation/0.6/irida_workflow_structure.ga
  src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/AssemblyAnnotation/0.6/messages_en.properties
  src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/AssemblyAnnotationCollection/0.5/irida_workflow.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/AssemblyAnnotationCollection/0.5/irida_workflow_structure.ga
  src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/AssemblyAnnotationCollection/0.5/messages_en.properties
Labels: tools

#803 Fix remote oauth project sync settings
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/RemoteAPIAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/RemoteProjectSettings.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/RemoteProjectSettingsUpdateRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/ajax/AjaxUpdateItemSuccessResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsRemoteAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsRemoteController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIRemoteProjectService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/projects/settings/pages/remote.html
  src/main/webapp/resources/js/apis/projects/remote-projects.js
  src/main/webapp/resources/js/components/lists/BasicList.jsx
  src/main/webapp/resources/js/components/remote-api/SyncFrequencySelect.jsx
  src/main/webapp/resources/js/pages/projects/remote/ProjectSynchronizationSettings.jsx
  src/main/webapp/resources/js/pages/projects/remote/index.js
  src/main/webapp/resources/js/pages/projects/settings/project-settings-remote.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectRemoteSettingsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectRemoteSettingsIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIRemoteProjectServiceTest.java
Labels: UI

#804 adding db change notice to upgrading guide
  UPGRADING.md
Labels: documentation
