Repository phac-nml/irida, pull requests merged in 2021-09, with the labels that each got.

#1084 Fixed broken UIAnalysesOutputsServiceTest
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIAnalysesOutputsServiceTest.java
Labels: test

#1085 Fix for verifying the project name length
  CHANGELOG.md
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/pages/projects/create/CreateProjectDetails.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/CreateProjectComponent.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/CreateProjectIT.java
Labels: bug, UI

#1083 Fix create first metadata template
  CHANGELOG.md
  src/main/webapp/resources/js/pages/projects/settings/components/metadata/MetadataTemplateCreate.jsx
Labels: bug, UI

#1090 Updating Sample modified date when metadata is updated
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/SampleServiceImpl.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/sample/SampleServiceImplTest.java
Labels: bug, metadata

#1087 Fix for missing RESP API endpoint
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/RESTAnalysisSubmissionController.java
Labels: bug, REST API

#1094 Updated metadata queries for performance
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/MetadataEntryRepositoryImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/MetadataFieldRepositoryImpl.java
Labels: back-end, metadata, REST API

#1091 Fixes filter by file exports all samples
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/specification/ProjectSampleSpecification.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/ExportToFileModel.java
  src/main/webapp/resources/js/pages/projects/samples/project-samples.js
  src/main/webapp/resources/js/utilities/file-utilities.js
Labels: bug, UI

#1100 Added 21.09 info to upgrading guide
  UPGRADING.md
Labels: documentation
