Repository phac-nml/irida, pull requests merged in 2021-04, with the labels that each got.

#969 Default project metadata template
  doc/user/user/sample-metadata/images/metadata-template-details.png
  doc/user/user/sample-metadata/images/metadata-template-list.png
  doc/user/user/sample-metadata/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/project/Project.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/ProjectMetadataTemplate.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/metadata/MetadataAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/LineListController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/dto/UIMetadataTemplate.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectControllerUtils.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIMetadataService.java
  src/main/resources/ca/corefacility/bioinformatics/irida/database/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.05/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.05/project-default-metadata-template.xml
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/projects/_base.html
  src/main/webapp/resources/js/apis/metadata/metadata-templates.js
  src/main/webapp/resources/js/components/icons/Icons.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/TemplateSelect/TemplateSelectOption.jsx
  src/main/webapp/resources/js/pages/projects/linelist/reducers/fields.js
  src/main/webapp/resources/js/pages/projects/linelist/reducers/templates.js
  src/main/webapp/resources/js/pages/projects/metadata/MetadataTemplateManager.jsx
  src/main/webapp/resources/js/pages/projects/metadata/MetadataTemplatesList.jsx
  src/main/webapp/resources/js/pages/projects/redux/fieldsSlice.js
  src/main/webapp/resources/js/pages/projects/redux/projectSlice.js
  src/main/webapp/resources/js/pages/projects/redux/templatesSlice.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectMetadataPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMetadataIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIMetadataServiceTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/test/integration/TableReset.xml
Labels: UI, enhancement

#971 Warning cleanup
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/config/repository/IridaApiFilesystemRepositoryConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaApiSecurityConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/config/services/IridaApiServicesConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/config/web/IridaUIWebConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/JobError.java
  src/main/java/ca/corefacility/bioinformatics/irida/pipeline/upload/galaxy/GalaxyHistoriesService.java
  src/main/java/ca/corefacility/bioinformatics/irida/pipeline/upload/galaxy/GalaxyLibrariesService.java
  src/main/java/ca/corefacility/bioinformatics/irida/pipeline/upload/galaxy/GalaxyWorkflowService.java
  src/test/java/ca/corefacility/bioinformatics/irida/config/IridaApiNoGalaxyTestConfig.java
  src/test/java/ca/corefacility/bioinformatics/irida/pipeline/upload/galaxy/unit/GalaxyHistoriesServiceTest.java
Labels: developer

#976 Enable snv density filter fix
  src/main/webapp/resources/js/components/form/InputWithOptions.jsx
  src/main/webapp/resources/js/pages/launch/launch-context.js
  src/main/webapp/resources/js/utilities/form-utilities.js
Labels: UI, bug

#975 Fix analysis results error loading
  src/main/webapp/resources/js/contexts/AnalysisContext.js
  src/main/webapp/resources/js/pages/analysis/components/Analysis.jsx
  src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisShare.jsx
Labels: UI, bug

#981 Fix reference file upload
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectReferenceFileService.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/ProjectServiceImplTest.java
Labels: back-end, bug

#977 Single request all project metadata
  CHANGELOG.md
  doc/developer/rest/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/web/assembler/resource/sample/SampleMetadataResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectSamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/samples/RESTSampleMetadataController.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/integration/sample/RESTSampleMetadataControllerIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/project/RESTProjectSamplesControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/samples/RESTSampleMetadataControllerTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/web/controller/test/integration/sample/RESTSampleMetadataControllerIT.xml
Labels: REST API, metadata

#987 Hotfix: Throw link error when fast5 not available
  CHANGELOG.md
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/service/remote/impl/Fast5ObjectRemoteServiceImpl.java
  src/main/webapp/package.json
  src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectSynchronizationServiceTest.java
Labels: REST API, federation
