Repository phac-nml/irida, pull requests merged in 2021-11, with the labels that each got.

#1123 update to latest locations for download
  doc/_includes/tutorials/common/initial-data.md
  doc/administrator/galaxy/existing-galaxy/index.md
  doc/administrator/web/index.md
  doc/downloads/index.md
  doc/user/administrator/troubleshooting/pipelines/index.md
  doc/user/tutorials/assembly/index.md
  doc/user/tutorials/mentalist/index.md
  doc/user/tutorials/sistr/index.md
Labels: documentation

#1120 Share Samples UI Testing
  src/main/resources/i18n/messages.properties
  src/main/webapp/package.json
  src/main/webapp/pages/projects/project_samples.html
  src/main/webapp/pages/projects/project_share.html
  src/main/webapp/pages/projects/templates/copy-move-modal.tmpl.html
  src/main/webapp/resources/js/pages/projects/share/ShareLayout.jsx
  src/main/webapp/resources/js/pages/projects/share/ShareProject.jsx
  src/main/webapp/resources/js/pages/projects/share/ShareSamples.jsx
  src/main/webapp/resources/js/pages/projects/share/ShareSuccess.jsx
  src/main/webapp/resources/js/pages/projects/share/SharedSamplesList.jsx
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ShareSamplesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectShareSamplesIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UISampleServiceTest.java
Labels: UI, test

#1122 Update ant design to v4.16.13
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/resources/js/components/Header/main-navigation/components/AnnouncementsSubMenu.jsx
  src/main/webapp/resources/js/components/Header/main-navigation/style.css
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/Announcements.java
Labels: dependencies

#1131 Upgrade react router v6
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/resources/js/pages/projects/linelist/components/Toolbar/Toolbar.jsx
  src/main/webapp/resources/js/pages/projects/samples-metadata-import/components/SampleMetadataImportComplete.jsx
  src/main/webapp/resources/js/pages/projects/samples-metadata-import/components/SampleMetadataImportMapHeaders.jsx
  src/main/webapp/resources/js/pages/projects/samples-metadata-import/components/SampleMetadataImportReview.jsx
  src/main/webapp/resources/js/pages/projects/samples-metadata-import/components/SampleMetadataImportUploadFile.jsx
  src/main/webapp/resources/js/pages/projects/samples-metadata-import/index.js
  src/main/webapp/yarn.lock
Labels: UI, javascript

#1093 LDAP and ADLAP backend changes
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaApiSecurityConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaAuthenticationSecurityConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/config/services/IridaApiPropertyPlaceholderConfig.java
  src/main/resources/ca/corefacility/bioinformatics/irida/config/authentication.properties
Labels: back-end, security

#1133 Share samples from linelist page
  CHANGELOG.md
  doc/_includes/tutorials/common/samples/copy-samples.md
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/pages/projects/linelist/components/ShareSampleButton/index.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/Toolbar/Toolbar.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectLineListPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectLineListPageIT.java
Labels: UI, feature
