Repository phac-nml/irida, pull requests merged in 2021-05, with the labels that each got.

#998 Updated lodash to fix security vulnerability
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: UI, dependencies

#997 Improving line list performance with custom metadata queries
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/joins/project/ProjectSampleJoinRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/MetadataEntryRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/MetadataEntryRepositoryCustom.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/MetadataEntryRepositoryImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/LineListController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/dto/UISampleMetadata.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/SampleServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/sample/SampleService.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/samples/RESTSampleMetadataController.java
  src/main/webapp/resources/js/pages/projects/linelist/reducers/fields.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/LineListControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/samples/RESTSampleMetadataControllerTest.java
Labels: UI, metadata

#1001 Project settings documentation
  doc/images/tutorials/common/projects/add-group-member-button.png
  doc/images/tutorials/common/projects/add-member-button.png
  doc/images/tutorials/common/projects/project-details-groups-tab.png
  doc/images/tutorials/common/projects/project-details-members-tab.png
  doc/user/user/project/images/associated-list.png
  doc/user/user/project/images/associated-local.png
  doc/user/user/project/images/associated-tab.png
  doc/user/user/project/images/delete-project-tab.png
  doc/user/user/project/images/delete-project.png
  doc/user/user/project/images/edit-project-role-button.png
  doc/user/user/project/images/project-details-details.png
  doc/user/user/project/images/project-details-edit-button.png
  doc/user/user/project/images/project-details-reference-files-tab.png
  doc/user/user/project/images/project-details-tab.png
  doc/user/user/project/images/project-members-collaborator.png
  doc/user/user/project/images/project-members-manager.png
  doc/user/user/project/images/project-settings-coverage-edit-button.png
  doc/user/user/project/images/project-settings-coverage-update.png
  doc/user/user/project/images/project-settings-coverate.png
  doc/user/user/project/images/project-settings-details.png
  doc/user/user/project/images/project-settings-no-auto-pipelines.png
  doc/user/user/project/images/project-settings-processing.png
  doc/user/user/project/images/project-settings-sync.png
  doc/user/user/project/images/project-settings-with-auto-pipeline.png
  doc/user/user/project/images/remove-project-member-button.png
  doc/user/user/project/images/remove-project-member-confirm.png
  doc/user/user/project/index.md
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectUserGroupsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectUserGroupsPageIT.java
Labels: documentation

#999 Remote project default template fix
  src/main/java/ca/corefacility/bioinformatics/irida/model/project/Project.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectSynchronizationServiceTest.java
Labels: back-end, federation

#1003 Fixed issue where collaborators could see delete project
  src/main/webapp/resources/js/pages/projects/settings/components/SettingsNav.jsx
  src/main/webapp/resources/js/pages/projects/settings/index.js
Labels: UI

#1008 Don't empty the cart on pipeline lauch
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineStartService.java
Labels: UI

#1007 Excluding unnecessary directories from war file build
  CHANGELOG.md
  pom.xml
Labels: developer

#1006 Hotfix/deprecated analysis states
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/enums/AnalysisState.java
  src/main/resources/i18n/messages.properties
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysesTableAjaxControllerTest.java
Labels: back-end

#1011 Use browserslist @ 4.16.6
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: UI
