Repository phac-nml/irida, pull requests merged in 2021-03, with the labels that each got.

#952 Announcements upgrade handle new users
  doc/_includes/tutorials/common/creating-a-user-account.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/announcements/Announcement.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/user/UserServiceImpl.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/user/UserServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/user/UserServiceImplTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/user/UserServiceImplIT.xml
Labels: back-end

#960 Fix for samples not rendering on project samples page when config property ngsarchive.linker.available set to false
  CHANGELOG.md
  src/main/webapp/resources/js/pages/projects/samples/linker/Linker.jsx
Labels: UI, bug

#961 Hotfix remove unnecessary tables
  CHANGELOG.md
  UPGRADING.md
  pom.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.01/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.01/remove-sample-metadata-entry.xml
Labels: back-end, bug

#965 Metadata field restriction
  src/main/java/ca/corefacility/bioinformatics/irida/model/sample/metadata/MetadataRestriction.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/MetadataRestrictionRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/MetadataTemplateServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/sample/MetadataTemplateService.java
  src/main/resources/ca/corefacility/bioinformatics/irida/database/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.05/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.05/metadata-restrictions.xml
Labels: metadata

#970 Updated to yarn version 2.4.1
  CHANGELOG.md
  src/main/webapp/.yarn/releases/yarn-2.4.1.cjs
  src/main/webapp/.yarnrc.yml
  src/main/webapp/yarn.lock
Labels: developer
