Repository phac-nml/irida, pull requests merged in 2021-02, with the labels that each got.

#886 Object store/ connection check on startup
  src/main/java/ca/corefacility/bioinformatics/irida/config/repository/IridaApiFilesystemRepositoryConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/config/services/IridaApiServicesConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/enums/StorageType.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageAwsUtilityImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageAzureUtilityImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageLocalUtilityImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageUtility.java
Labels: back-end

#932 Pipeline Launch: automated pipelines
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/ProjectSettingsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/settings/ProjectSettingsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/settings/dto/AnalysisTemplate.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/settings/dto/Coverage.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/settings/dto/Priorities.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/settings/exceptions/UpdateException.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/launchPipeline/LaunchAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/launchPipeline/LaunchController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/launchPipeline/dtos/LaunchRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineStartService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectSettingsService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/projects/settings/pages/processing.html
  src/main/webapp/pages/projects/templates/remove-analysis-template-modal.html
  src/main/webapp/pages/templates/i18n/README.md
  src/main/webapp/resources/js/apis/pipelines/pipelines.js
  src/main/webapp/resources/js/apis/projects/settings.js
  src/main/webapp/resources/js/components/pipelines/Pipelines.jsx
  src/main/webapp/resources/js/pages/launch/LaunchButton.jsx
  src/main/webapp/resources/js/pages/launch/LaunchForm.jsx
  src/main/webapp/resources/js/pages/launch/SharePipelineResults.jsx
  src/main/webapp/resources/js/pages/launch/launch-context.js
  src/main/webapp/resources/js/pages/launch/launch-dispatch.js
  src/main/webapp/resources/js/pages/launch/launch-utilities.js
  src/main/webapp/resources/js/pages/projects/associated-projects/ViewAssociatedProjects.jsx
  src/main/webapp/resources/js/pages/projects/processing/AnalysisTemplates.jsx
  src/main/webapp/resources/js/pages/projects/processing/AutomatedPipelineHeader.jsx
  src/main/webapp/resources/js/pages/projects/processing/ProcessingAutomatedPipelines.jsx
  src/main/webapp/resources/js/pages/projects/processing/ProcessingCoverage.jsx
  src/main/webapp/resources/js/pages/projects/processing/ProcessingPriorities.jsx
  src/main/webapp/resources/js/pages/projects/processing/index.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSettingsProcessingPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSettingsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectSettingsAjaxControllerTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/ProjectsPageIT.xml
Labels: UI

#933 HOTFIX: Fix tabular result viewer
  CHANGELOG.md
  pom.xml
  src/main/webapp/resources/js/pages/analysis/components/AnalysisTabularPreview.jsx
Labels: UI, bug

#943 Launch service testing
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineService.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pipelines/AssemblyPipelinePageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIPipelineServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIPipelineStartServiceTest.java
Labels: UI, test

#947 Fixed webpack not outputting css files
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/webpack.config.js
  src/main/webapp/yarn.lock
Labels: UI, bug

#946 Ant Design update v4.12.3
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/resources/js/components/Header/main-navigation/components/CartLink.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisTabularPreview.jsx
  src/main/webapp/resources/js/pages/projects/reference-files/ReferenceFiles.jsx
  src/main/webapp/yarn.lock
Labels: dependencies

#942 Metadata Phylogeny-tree Advanced Visualisation fix
  CHANGELOG.md
  src/main/webapp/resources/js/pages/visualizations/phylogenetics/components/phylocanvas/phylocanvas.component.js
Labels: UI, bug

#944 Launch user docs
  doc/Gemfile.lock
  doc/images/tutorials/common/pipelines/ready-to-launch-button.png
  doc/user/tutorials/assembly/images/assembly-pipeline-page.png
  doc/user/tutorials/assembly/index.md
  doc/user/tutorials/bio_hansel/images/biohansel-pipeline-page.png
  doc/user/tutorials/bio_hansel/images/biohansel-pipeline-params.png
  doc/user/tutorials/bio_hansel/index.md
  doc/user/tutorials/mentalist/images/mentalist-pipeline-page.png
  doc/user/tutorials/mentalist/images/mentalist-pipeline-parameters.png
  doc/user/tutorials/mentalist/index.md
  doc/user/tutorials/refseq_masher/images/refseq-pipeline-customize.png
  doc/user/tutorials/refseq_masher/images/refseq-pipeline-page.png
  doc/user/tutorials/refseq_masher/index.md
  doc/user/tutorials/sistr/images/sistr-pipeline-page.png
  doc/user/tutorials/sistr/images/view-your-analyses.png
  doc/user/tutorials/sistr/index.md
  doc/user/tutorials/snvphyl/images/snvphyl-pipeline-customize.png
  doc/user/tutorials/snvphyl/images/snvphyl-pipeline-page.png
  doc/user/tutorials/snvphyl/images/snvphyl-pipeline-snv-density.png
  doc/user/tutorials/snvphyl/images/snvphyl-pipeline-upload-ref-file.png
  doc/user/tutorials/snvphyl/index.md
  doc/user/user/pipelines/images/analysis-email-upon-completion.png
  doc/user/user/pipelines/images/analysis-share-launch.png
  doc/user/user/pipelines/images/general-details.png
  doc/user/user/pipelines/images/parameters-default.png
  doc/user/user/pipelines/images/parameters-exposed.png
  doc/user/user/pipelines/images/parameters-modified.png
  doc/user/user/pipelines/images/pipeline-launch.png
  doc/user/user/pipelines/images/pipeline-running.png
  doc/user/user/pipelines/images/pipeline-samples.png
  doc/user/user/pipelines/images/reference-file-required.png
  doc/user/user/pipelines/images/save-results-to-samples.png
  doc/user/user/pipelines/images/share-results.png
  doc/user/user/pipelines/index.md
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/launch.html
  src/main/webapp/resources/js/pages/launch/parameters/SavedParameters.jsx
  src/main/webapp/resources/js/pages/launch/references/ReferenceFiles.jsx
  src/main/webapp/yarn.lock
Labels: UI, documentation

#950 HOTFIX: Added ownership flag to copying sample to project in REST API
  CHANGELOG.md
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectSamplesController.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/integration/project/ProjectSamplesIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/project/RESTProjectSamplesControllerTest.java
Labels: REST API

#928 Changed git ignore for apidocs down to the main gitignore file
  .gitignore
  doc/.gitignore
Labels: documentation

#951 Fixed missing filter menus on analysis outputs table
  CHANGELOG.md
  src/main/webapp/resources/js/pages/analyses/analysis-outputs-table.js
Labels: UI, bug
