Repository phac-nml/irida, pull requests merged in 2021-06, with the labels that each got.

#1010 Project events update to use Ant Design
  CHANGELOG.md
  doc/user/user/project/images/project-recent-activities.png
  doc/user/user/project/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/activities/ActivitiesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/activities/ActivityType.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/activities/dto/Activity.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/activities/dto/ActivityItem.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/dto/list/ListItem.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/dto/list/PagedListResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectEventsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIActivitiesService.java
  src/main/resources/i18n/messages.properties
  src/main/resources/mail/welcome-email.html
  src/main/webapp/entries.js
  src/main/webapp/pages/projects/project_activity.html
  src/main/webapp/pages/projects/project_details.html
  src/main/webapp/resources/js/apis/activities/activities.js
  src/main/webapp/resources/js/components/activities/ActivityListItem.jsx
  src/main/webapp/resources/js/components/icons/Icons.jsx
  src/main/webapp/resources/js/components/project/ProjectNav.jsx
  src/main/webapp/resources/js/i18n.js
  src/main/webapp/resources/js/pages/projects/ProjectActivity.jsx
  src/main/webapp/resources/js/pages/projects/project-events.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectActivityPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectActivityPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectEventsControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectsControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIActivitiesServiceTest.java
Labels: UI

#1019 Fix page title on remote IRIDA connections page.
  CHANGELOG.md
  src/main/webapp/pages/remote_apis/list.html
Labels: UI, bug

#1015 Make plugin path configurable
  CHANGELOG.md
  doc/administrator/web/config/irida.conf
  doc/administrator/web/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/config/services/IridaPluginConfig.java
  src/main/resources/ca/corefacility/bioinformatics/irida/config/filesystem.properties
Labels: tools

#1031 Add base navigation for project analyses refactor
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/projects/analyses/_base.html
  src/main/webapp/pages/projects/analyses/pages/analyses_table.html
  src/main/webapp/pages/projects/analyses/pages/outputs.html
  src/main/webapp/pages/projects/project_analyses.html
  src/main/webapp/resources/js/components/AnalysesTable/AnalysesTable.jsx
  src/main/webapp/resources/js/components/project/ProjectNav.jsx
  src/main/webapp/resources/js/contexts/AnalysesTableContext.js
  src/main/webapp/resources/js/pages/analyses/AnalysesPage.jsx
  src/main/webapp/resources/js/pages/projects/project-analyses/ProjectAnalysesPage.jsx
  src/main/webapp/resources/js/pages/projects/project-analyses/components/AutomatedSingleSampleAnalysisOutputs.jsx
  src/main/webapp/resources/js/pages/projects/project-analyses/components/ProjectAnalysesPage.jsx
  src/main/webapp/resources/js/pages/projects/project-analyses/components/SharedSingleSampleAnalysisOutputs.jsx
  src/main/webapp/resources/js/pages/projects/project-analyses/index.js
  src/main/webapp/resources/js/pages/projects/project-analyses/store.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectAnalysesPage.java
Labels: UI

#1036 Refactor base permission
  src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaApiSecurityConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/BasePermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/IridaPermissionEvaluator.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/RepositoryBackedPermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/analysis/ReadAnalysisPermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/analysis/ReadAnalysisSubmissionPermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/analysis/UpdateAnalysisSubmissionPermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/analysis/UpdateSamplesFromAnalysisSubmissionPermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/files/ReadReferenceFilePermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/files/ReadSequencingObjectPermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/files/ReadSequencingRunPermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/files/UpdateReferenceFilePermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/files/UpdateSequencingRunPermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/metadata/ReadMetadataTemplatePermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/metadata/UpdateMetadataTemplatePermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/project/ModifyProjectPermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/project/ReadExportSubmissionPermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/project/ReadProjectPermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/sample/ReadSamplePermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/sample/UpdateSamplePermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/user/UpdateUserGroupPermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/user/UpdateUserPermission.java
  src/test/java/ca/corefacility/bioinformatics/irida/security/permissions/RepositoryBackedPermissionTest.java
Labels: metadata, security

#1029 Create New Project (Ant Design Update)
  CHANGELOG.md
  doc/_includes/tutorials/common/creating-a-project.md
  doc/images/tutorials/common/projects/create-new-project-form.png
  doc/images/tutorials/common/projects/project-organism.png
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/CartAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/dto/CartSamplesByUserPermissions.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/CreateProjectRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UICartService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectsService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/projects/project_new.html
  src/main/webapp/resources/js/apis/cart/cart.js
  src/main/webapp/resources/js/apis/projects/create.js
  src/main/webapp/resources/js/apis/projects/projects.js
  src/main/webapp/resources/js/components/ontology/OntologySelect.jsx
  src/main/webapp/resources/js/components/samples/SampleDetailViewer.jsx
  src/main/webapp/resources/js/pages/projects/create/CreateProjectDetails.jsx
  src/main/webapp/resources/js/pages/projects/create/CreateProjectLayout.jsx
  src/main/webapp/resources/js/pages/projects/create/CreateProjectSamples.jsx
  src/main/webapp/resources/js/pages/projects/create/index.js
  src/main/webapp/resources/js/pages/projects/create/store.js
  src/main/webapp/resources/js/pages/projects/list/ProjectsTable.jsx
  src/main/webapp/resources/js/pages/projects/projects-new.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/CreateProjectComponent.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectsNewPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/CreateProjectIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectsNewPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectsControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UICartServiceTest.java
Labels: UI

#1038 Casting to ResponseResource in FastaView
  src/main/java/ca/corefacility/bioinformatics/irida/web/spring/view/FastaView.java
Labels: REST API

#1039 Update Redux Toolkit to stable version
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: developer

#1040 ProjectMetadataResponse permission
  src/main/java/ca/corefacility/bioinformatics/irida/model/sample/metadata/MetadataFieldResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/sample/metadata/ProjectMetadataResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/LineListController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIMetadataService.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/BasePermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/metadata/ReadProjectMetadataResponsePermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/MetadataTemplateServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/SampleServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/sample/MetadataTemplateService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/sample/SampleService.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/samples/RESTSampleMetadataController.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/LineListControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/security/permissions/metadata/ReadProjectMetadataResponsePermissionTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/sample/SampleServiceImplIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/samples/RESTSampleMetadataControllerTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/SampleServiceImplIT.xml
Labels: metadata, security
