Repository phac-nml/irida, pull requests merged in 2021-07, with the labels that each got.

#1049 Permission for reading individual metadata entries
  src/main/java/ca/corefacility/bioinformatics/irida/model/sample/metadata/MetadataEntry.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/MetadataEntryRepositoryCustom.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/MetadataEntryRepositoryImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/LineListController.java
  src/main/java/ca/corefacility/bioinformatics/irida/security/permissions/metadata/ReadMetadataEntryPermission.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/SampleServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/sample/SampleService.java
  src/test/java/ca/corefacility/bioinformatics/irida/security/permissions/metadata/ReadMetadataEntryPermissionTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/sample/SampleServiceImplIT.java
Labels: metadata, security

#1064 Chromedriver update to v92
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: test

#1065 Fix issue updating UI for metadata filed restrictions
  src/main/webapp/resources/js/pages/projects/settings/components/metadata/MetadataFieldsListManager.jsx
Labels: UI, bug
