Repository phac-nml/irida, pull requests merged in 2021-01, with the labels that each got.

#894 Update IRIDA documentation publishing strategy
  .github/workflows/ci-test.yml
  CHANGELOG.md
  README.md
  build-docs.py
  doc/.gitignore
  doc/Gemfile
  doc/Gemfile.lock
  doc/README.md
  doc/_build-config.yml
  doc/_config.yml
  doc/_includes/head.html
  doc/_includes/tutorials/common/creating-a-project.md
  doc/_includes/tutorials/common/images/your-projects.png
  doc/_plugins/font-awesome/font_awesome.rb
  doc/_plugins/kramdown-with-pygments/README.md
  doc/_plugins/kramdown-with-pygments/kramdown_pygments.rb
  doc/_sass/_base.scss
  doc/css/font-awesome-4.3.0/css/font-awesome.css
  doc/css/font-awesome-4.3.0/css/font-awesome.min.css
  doc/css/font-awesome-4.3.0/fonts/FontAwesome.otf
  doc/css/font-awesome-4.3.0/fonts/fontawesome-webfont.eot
  doc/css/font-awesome-4.3.0/fonts/fontawesome-webfont.svg
  doc/css/font-awesome-4.3.0/fonts/fontawesome-webfont.ttf
  doc/css/font-awesome-4.3.0/fonts/fontawesome-webfont.woff
  doc/css/font-awesome-4.3.0/fonts/fontawesome-webfont.woff2
  doc/developer/getting-started/index.md
  doc/feed.xml
  doc/feeds/feed.json
  doc/images/tutorials/common/projects/create-new-project-btn.png
  doc/images/tutorials/common/projects/your-projects.png
  doc/index.html
  doc/index.md
  doc/scripts/search.js
  doc/search/index.html
  doc/user/user/pipelines/index.md
  doc/user/user/project/index.md
  pom.xml
  scripts/build-docs.sh
  src/main/webapp/yarn.lock
Labels: documentation

#908 Docs dependencies updated in Gemfile.lock
  doc/Gemfile.lock
Labels: documentation

#849 Add html result viewer
  CHANGELOG.md
  doc/developer/tools/pipelines/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/package.json
  src/main/webapp/pages/analysis/html-output.html
  src/main/webapp/resources/js/apis/analysis/analysis.js
  src/main/webapp/resources/js/components/OutputFiles/OutputFileHeader.jsx
  src/main/webapp/resources/js/contexts/AnalysisOutputsContext.js
  src/main/webapp/resources/js/pages/analysis/components/AnalysisHtmlPreview.jsx
  src/main/webapp/resources/js/pages/analysis/components/outputs/OutputFilePreview.jsx
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysisControllerTest.java
Labels: UI, enhancement

#892 Announcements upgrade user dashboard
  src/main/java/ca/corefacility/bioinformatics/irida/model/announcements/Announcement.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/announcements/AnnouncementUserJoin.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/announcements/AnnouncementAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAnnouncementsService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/announcements/announcements.html
  src/main/webapp/pages/announcements/control.html
  src/main/webapp/pages/index.html
  src/main/webapp/resources/js/apis/announcements/announcements.js
  src/main/webapp/resources/js/components/Buttons/LinkButton.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/AnnouncementForm.jsx
  src/main/webapp/resources/js/pages/admin/components/announcements/AnnouncementsTable.jsx
  src/main/webapp/resources/js/pages/announcement/announcementDashboard.js
  src/main/webapp/resources/js/pages/announcement/components/AnnouncementDashboard.jsx
  src/main/webapp/resources/js/pages/announcement/components/PriorityFlag.jsx
  src/main/webapp/resources/js/pages/announcement/components/ViewUnreadAnnouncement.jsx
  src/main/webapp/resources/js/pages/dashboard.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/AnnouncementDashboardPage.java
Labels: UI

#901 Added hashing service to allow remote APIs to check for changes before launching full sync
  CHANGELOG.md
  doc/user/user/project/images/project-settings-sync.png
  doc/user/user/project/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/project/Project.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/remote/RemoteStatus.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/remote/ProjectRemoteRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/remote/impl/ProjectRemoteRepositoryImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/remote/RemoteProjectSettingsUpdateRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIRemoteProjectService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectHashingService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectRemoteService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectSynchronizationService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/remote/impl/ProjectRemoteServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/assembler/resource/ProjectHashResource.java
  src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectsController.java
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.01/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.01/full-project-hash.xml
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/projects/remote-projects.js
  src/main/webapp/resources/js/pages/projects/remote/ProjectSynchronizationSettings.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIRemoteProjectServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectHashingServiceIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectHashingServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectSynchronizationServiceTest.java
Labels: REST API, UI, federation

#911 Minor changes for first announcements release
  CHANGELOG.md
  doc/user/administrator/images/add-announcement-button.png
  doc/user/administrator/images/add-announcement.png
  doc/user/administrator/images/announcement-details-button.png
  doc/user/administrator/images/announcement-details.png
  doc/user/administrator/images/announcements-home-page.png
  doc/user/administrator/images/announcements-side-menu.png
  doc/user/administrator/images/delete-announcement-button.png
  doc/user/administrator/images/delete-announcement-confirmation.png
  doc/user/administrator/images/edit-announcement-button.png
  doc/user/administrator/images/edit-announcement.png
  doc/user/administrator/index.md
  doc/user/user/dashboard/images/announcements-display-to-user.png
  doc/user/user/dashboard/images/announcements-mark-as-read-user.png
  doc/user/user/dashboard/images/announcements-mark-as-read-user_1.png
  doc/user/user/dashboard/images/announcements-mark-as-read-user_2.png
  doc/user/user/dashboard/images/announcements-view-read-announcements-page.png
  doc/user/user/dashboard/images/announcements-view-read-announcements.png
  doc/user/user/dashboard/index.md
  src/main/webapp/pages/announcements/read.html
  src/main/webapp/resources/js/pages/announcement/announcements.js
Labels: UI, documentation

#917 Made cart link easier to click
  src/main/webapp/resources/js/components/Header/main-navigation/components/CartLink.jsx
Labels: UI

#897 Email pipeline result error
  CHANGELOG.md
  doc/user/tutorials/assembly/images/analysis-in-progress.png
  doc/user/tutorials/assembly/index.md
  doc/user/tutorials/bio_hansel/images/analysis-in-progress.png
  doc/user/tutorials/bio_hansel/index.md
  doc/user/tutorials/mentalist/images/analysis-in-progress.png
  doc/user/tutorials/refseq_masher/images/analysis-in-progress.png
  doc/user/tutorials/refseq_masher/index.md
  doc/user/tutorials/sistr/images/analysis-in-progress.png
  doc/user/tutorials/sistr/index.md
  doc/user/tutorials/snvphyl/images/analysis-in-progress.png
  doc/user/tutorials/snvphyl/index.md
  doc/user/user/pipelines/images/analysis-email-upon-completion-running.png
  doc/user/user/pipelines/images/analysis-email-upon-completion.png
  doc/user/user/pipelines/index.md
  doc/user/user/sistr/images/sistr-typing-status.png
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/submission/AbstractAnalysisSubmission.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/submission/AnalysisSubmission.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/submission/AnalysisSubmissionTemplate.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysisDetails.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysisEmailPipelineResult.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/dto/PipelineStartParameters.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/AnalysisSubmissionService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/analysis/execution/AnalysisExecutionServiceAspect.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/AnalysisExecutionScheduledTaskImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceImpl.java
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.01/all-changes.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.01/analysis-submission-email-pipeline-result-on-error.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/sql/required-data.sql
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/pipelines/types/generic_pipeline.html
  src/main/webapp/resources/js/apis/analysis/analysis.js
  src/main/webapp/resources/js/components/Buttons/SimpleRadioButtonGroup.jsx
  src/main/webapp/resources/js/contexts/AnalysisDetailsContext.js
  src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisDetails.jsx
  src/main/webapp/resources/js/pages/pipelines/pipeline.launch.js
  src/test/java/ca/corefacility/bioinformatics/irida/processing/impl/unit/AutomatedAnalysisFileProcessorTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisDetailsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/pipelines/BasicPipelinePage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pipelines/AssemblyPipelinePageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysisAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/AnalysisExecutionScheduledTaskImplTest.java
Labels: UI, back-end

#915 Fix issue with clearing samples from the cart
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UICartService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/sessionAttrs/Cart.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UICartServiceTest.java
Labels: UI, bug

#795 Add password authentication for SMTP server
  CHANGELOG.md
  doc/administrator/web/config/web.conf
  src/main/java/ca/corefacility/bioinformatics/irida/config/services/WebEmailConfig.java
  src/main/resources/configuration.properties
Labels: adminstrator, back-end

#909 Pipeline Launch: Server Connection
  src/main/java/ca/corefacility/bioinformatics/irida/exceptions/pipelines/ReferenceFileRequiredException.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/pipeline/DynamicSource.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/pipeline/SavedPipelineParameters.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/ui/Input.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/ui/InputWithOptions.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/launchPipeline/LaunchAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/launchPipeline/dtos/LaunchRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/launchPipeline/dtos/UIPipelineDetailsResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/dto/PipelineStartParameters.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/dto/WorkflowParametersToSave.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineStartService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/AnalysisExecutionScheduledTaskImpl.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/launch.html
  src/main/webapp/resources/js/components/form/InputWithOptions.jsx
  src/main/webapp/resources/js/components/pipeline/Pipeline.jsx
  src/main/webapp/resources/js/pages/launch/DynamicSources.jsx
  src/main/webapp/resources/js/pages/launch/LaunchDetails.jsx
  src/main/webapp/resources/js/pages/launch/LaunchForm.jsx
  src/main/webapp/resources/js/pages/launch/LaunchParameters.jsx
  src/main/webapp/resources/js/pages/launch/LaunchParametersWithOptions.jsx
  src/main/webapp/resources/js/pages/launch/ParameterWithOptions.jsx
  src/main/webapp/resources/js/pages/launch/SharePipelineResults.jsx
  src/main/webapp/resources/js/pages/launch/launch-context.js
  src/main/webapp/resources/js/pages/launch/launch-dispatch.js
  src/main/webapp/resources/js/pages/launch/launch-utilities.js
  src/main/webapp/resources/js/pages/launch/parameters/SavedParameters.jsx
  src/main/webapp/resources/js/pages/launch/references/ReferenceFiles.jsx
  src/main/webapp/resources/js/pages/pipelines/pipeline.launch.js
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSettingsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/pipelines/PipelineControllerTest.java
Labels: UI

#920 Fixed hashing
  src/main/java/ca/corefacility/bioinformatics/irida/model/sample/StaticMetadataTemplateField.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/sample/metadata/PipelineProvidedMetadataEntry.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/submission/IridaWorkflowNamedParameters.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectSynchronizationService.java
  src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectHashingServiceIT.java
  src/test/resources/ca/corefacility/bioinformatics/irida/test/integration/TableReset.xml
Labels: back-end, federation

#921 Updated frontend-maven-plugin
  CHANGELOG.md
  pom.xml
Labels: developer

#923 Fix issue moving a large number of samples between project
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesController.java
  src/main/webapp/resources/js/pages/projects/samples/project-samples.js
Labels: UI, bug

#925 Changed links to new docs in UPGRADING
  CHANGELOG.md
  UPGRADING.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: documentation

#922 Pipeline Launch: remove saved params from modal
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/pipeline/CreateNamedParameterSetAjaxResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/pipeline/SavePipelineParametersRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/launchPipeline/LaunchAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/package.json
  src/main/webapp/resources/js/components/page/PageWrapper.jsx
  src/main/webapp/resources/js/pages/launch/LaunchContent.jsx
  src/main/webapp/resources/js/pages/launch/LaunchPage.jsx
  src/main/webapp/resources/js/pages/launch/LaunchPageHeader.jsx
  src/main/webapp/resources/js/pages/launch/LaunchParameters.jsx
  src/main/webapp/resources/js/pages/launch/launch-context.js
  src/main/webapp/resources/js/pages/launch/launch-dispatch.js
  src/main/webapp/resources/js/pages/launch/launch-utilities.test.js
  src/main/webapp/resources/js/pages/launch/parameters/ParametersFooter.jsx
  src/main/webapp/resources/js/pages/launch/parameters/ParametersModal.jsx
  src/main/webapp/resources/js/pages/launch/parameters/SaveParametersAsFooter.jsx
  src/main/webapp/resources/js/pages/launch/parameters/SavedParameters.jsx
  src/main/webapp/yarn.lock
Labels: UI, feature
