Repository phac-nml/irida, pull requests merged in 2022-03, with the labels that each got.

#1201 Default-sample-sequencing-object
  src/main/java/ca/corefacility/bioinformatics/irida/model/sample/Sample.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/launchPipeline/dtos/LaunchSample.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineSampleService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java
  src/main/resources/application.properties
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/RENAME_ME_WHEN_READY/add-default-sequencing-object-to-sample.xml
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/RENAME_ME_WHEN_READY/all-changes.xml
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/samples/samples.js
  src/main/webapp/resources/js/components/samples/components/SampleFileList.jsx
  src/main/webapp/resources/js/components/samples/sampleSlice.js
  src/main/webapp/resources/js/components/sequence-files/PairedFileRenderer.jsx
  src/main/webapp/resources/js/components/sequence-files/SequenceFileDetailsRenderer.jsx
  src/main/webapp/resources/js/components/sequence-files/SequenceFileHeader.jsx
  src/main/webapp/resources/js/components/sequence-files/SequenceFileHeaderOwner.jsx
  src/main/webapp/resources/js/components/sequence-files/SingleEndFileRenderer.jsx
  src/main/webapp/resources/js/pages/launch/LaunchFiles.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/CartPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/SampleDetailsViewer.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/samples/SamplesAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UISampleServiceTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/CartView.xml
  src/test/resources/files/sequence-files/04-4444_S1_L001_R1_001.fastq
  src/test/resources/files/sequence-files/04-4444_S1_L001_R2_001.fastq
Labels: enhancement, UI

#1216 Updated dashboard recent activities to use ant design
  CHANGELOG.md
  doc/developer/interface/index.md
  doc/user/administrator/images/admin-panel-navbar-button.png
  doc/user/user/dashboard/images/announcements-page.png
  doc/user/user/dashboard/images/announcements-submenu.png
  doc/user/user/dashboard/images/cart.png
  doc/user/user/dashboard/images/dashboard.png
  doc/user/user/dashboard/images/main-menu-manager.png
  doc/user/user/dashboard/images/main-menu-user.png
  doc/user/user/dashboard/images/main-menu.png
  doc/user/user/dashboard/images/recent-activities.png
  doc/user/user/dashboard/images/search-bar.png
  doc/user/user/dashboard/images/settings-panel-manager.png
  doc/user/user/dashboard/images/settings-panel-user.png
  doc/user/user/dashboard/images/settings-panel.png
  doc/user/user/dashboard/images/user-project-statistics.png
  doc/user/user/dashboard/images/user-settings.png
  doc/user/user/dashboard/index.md
  doc/user/user/login/images/irida-dashboard.png
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/ProjectEventRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/analysis/submission/AnalysisSubmissionRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/joins/project/ProjectUserJoinRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/activities/ActivitiesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/activities/ActivityType.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectEventsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIActivitiesService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIUserStatisticsService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/users/UserStatisticsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/users/dto/UserStatisticsResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/AnalysisSubmissionService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/ProjectEventService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/ProjectService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/ProjectEventServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/ProjectServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceImpl.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/eventsold/admin.html
  src/main/webapp/pages/eventsold/events.html
  src/main/webapp/pages/eventsold/fragments/event.html
  src/main/webapp/pages/index.html
  src/main/webapp/resources/js/apis/activities/activities.js
  src/main/webapp/resources/js/apis/dashboard/dashboard.js
  src/main/webapp/resources/js/components/activities/ActivityListItem.jsx
  src/main/webapp/resources/js/components/icons/Icons.jsx
  src/main/webapp/resources/js/components/samples/components/SampleMetadata.jsx
  src/main/webapp/resources/js/modules/events/events.js
  src/main/webapp/resources/js/pages/activities/activities.js
  src/main/webapp/resources/js/pages/dashboard.js
  src/main/webapp/resources/js/pages/dashboard/Dashboard.jsx
  src/main/webapp/resources/js/pages/dashboard/components/RecentActivity.jsx
  src/main/webapp/resources/js/pages/dashboard/components/RecentActivityAllProjects.jsx
  src/main/webapp/resources/js/pages/dashboard/components/RecentActivityList.jsx
  src/main/webapp/resources/js/pages/dashboard/components/RecentActivityUserProjects.jsx
  src/main/webapp/resources/js/pages/dashboard/components/UserProjectStatistics.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/DashboardPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/DashboardPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectEventsControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIActivitiesServiceTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/DashboardPageIT.xml
Labels: UI

#1215 Updated to Ant Design v4.19.1
  CHANGELOG.md
  src/main/resources/i18n/messages.properties
  src/main/webapp/package.json
  src/main/webapp/pages/eventsold/admin.html
  src/main/webapp/pages/eventsold/events.html
  src/main/webapp/pages/eventsold/fragments/event.html
  src/main/webapp/pages/template/page.html
  src/main/webapp/resources/js/components/Header/Breadcrumbs.jsx
  src/main/webapp/resources/js/components/Header/MainNavigation.jsx
  src/main/webapp/resources/js/components/Header/PageHeader.jsx
  src/main/webapp/resources/js/components/Header/main-navigation/components/AnnouncementsSubMenu.jsx
  src/main/webapp/resources/js/components/Header/main-navigation/components/CartLink.jsx
  src/main/webapp/resources/js/components/Header/main-navigation/components/GlobalSearch.jsx
  src/main/webapp/resources/js/components/ant.design/table-search-props.js
  src/main/webapp/resources/js/pages/dashboard/components/RecentActivityList.jsx
  src/main/webapp/resources/js/pages/projects/samples/linker/Linker.jsx
  src/main/webapp/yarn.lock
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/Announcements.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/CreateProjectComponent.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/pipelines/LaunchPipelinePage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/CreateProjectIT.java
Labels: UI, dependencies

#1222 Updated CI JavaScript heap size
  .github/workflows/ci-test.yml
Labels: test, developer, javascript

#1225 Updated sharing samples to include sharing large numbers
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/ProjectRepository.java
  src/main/webapp/package.json
  src/main/webapp/resources/js/components/Header/main-navigation/components/GlobalSearch.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/ShareSampleButton/index.jsx
  src/main/webapp/resources/js/pages/projects/share/ShareLarge.jsx
  src/main/webapp/resources/js/pages/projects/share/index.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysesUserOutputsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysesUserPage.java
Labels: UI, feature

#1228 Added links to main nav and fixed breadcrumbs
  src/main/webapp/pages/template/page.html
  src/main/webapp/resources/js/components/Header/MainNavigation.jsx
Labels: UI

#1207 Sample details refactor/ sample analyses
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/analysis/submission/AnalysisSubmissionRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/dto/SampleAnalyses.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAnalysesService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/SequencingRunServiceImpl.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/samples/samples.js
  src/main/webapp/resources/js/components/samples/components/SampleAnalyses.jsx
  src/main/webapp/resources/js/components/samples/components/SampleAnalysesState.jsx
  src/main/webapp/resources/js/components/samples/sampleAnalysesSlice.js
  src/main/webapp/resources/js/components/samples/store.js
  src/main/webapp/resources/js/components/sequence-files/SequenceFileHeaderOwner.jsx
  src/main/webapp/resources/js/components/sequence-files/SingleEndFileRenderer.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/CartPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/SampleDetailsViewer.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/cart/CartPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/samples/SamplesAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIAnalysesServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UISampleServiceTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/CartView.xml
Labels: UI
