Repository phac-nml/irida, pull requests merged in 2022-11, with the labels that each got.

#1384 Object store/ azure testing
  .github/workflows/ci-test.yml
  build.gradle.kts
  doc/developer/getting-started/index.md
  run-tests.sh
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageAzureUtilityImpl.java
  src/test/java/ca/corefacility/bioinformatics/irida/annotation/FileSystemIntegrationTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/cloud/IridaFileStorageAzureUtilityTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/cloud/IridaFileStorageTestUtility.java
Labels: test

#1398 Hotfix: Sharing samples as manager
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/SampleServiceImpl.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectShareSamplesIT.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesPage.xml
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectShareSamples.xml
Labels: bug

#1412 TEST: Fixes flaky tests in testRemoteProjectManagerPageSetup
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/admin/AdminClientsPage.java
Labels: test

#1405 DEPENDENCY: Updated react-router to 6.4.3
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/pnpm-lock.yaml
  src/main/webapp/resources/js/pages/projects/ProjectSPA.tsx
Labels: UI, dependencies

#1409 ENHANCEMENT: Global search update to Ant Design
  CHANGELOG.md
  doc/user/user/dashboard/images/search-bar.png
  doc/user/user/dashboard/images/search-project-result.png
  doc/user/user/dashboard/images/search-sample-result.png
  doc/user/user/dashboard/index.md
  doc/user/user/search/images/global-search-box.png
  doc/user/user/search/images/global-search-counts.png
  doc/user/user/search/images/global-search-results.png
  doc/user/user/search/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/config/web/IridaUIWebConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/utilities/Formats.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/utilities/components/DataTable.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/SubmissionIds.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/datatables/DataTablesColumnDefinitions.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/datatables/DataTablesExportToFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/datatables/DataTablesExportTypes.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/datatables/DataTablesExportable.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/datatables/DataTablesParams.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/datatables/DataTablesResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/datatables/config/DataTablesRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/datatables/config/DataTablesRequestResolver.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/datatables/export/ExportFormatException.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/datatables/models/AbstractExportModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/datatables/models/ProjectSampleModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/datatables/DTProjectSamples.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/search/SearchController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/search/dto/SearchItem.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/search/dto/SearchProject.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/search/dto/SearchRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/search/dto/SearchSample.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/package.json
  src/main/webapp/pages/search/search.html
  src/main/webapp/pnpm-lock.yaml
  src/main/webapp/resources/css/app.css
  src/main/webapp/resources/js/apis/search/search.ts
  src/main/webapp/resources/js/apis/users/user.ts
  src/main/webapp/resources/js/app.js
  src/main/webapp/resources/js/pages/projects/samples/components/SamplesTable.jsx
  src/main/webapp/resources/js/pages/search/ProjectTag.tsx
  src/main/webapp/resources/js/pages/search/SearchCount.tsx
  src/main/webapp/resources/js/pages/search/SearchLayout.tsx
  src/main/webapp/resources/js/pages/search/SearchProjectsTable.tsx
  src/main/webapp/resources/js/pages/search/SearchSamplesTable.tsx
  src/main/webapp/resources/js/pages/search/index.tsx
  src/main/webapp/resources/js/pages/search/loaders/user-loader.ts
  src/main/webapp/resources/js/pages/search/search.js
  src/main/webapp/resources/js/types/irida/index.d.ts
  src/main/webapp/resources/js/utilities/datatables-utilities.js
  src/main/webapp/resources/js/utilities/date-utilities.ts
  src/main/webapp/resources/js/utilities/fontawesome-utilities.js
  src/main/webapp/resources/js/vendor/datatables/datatables.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/SearchResultPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/AbstractPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/SearchResultPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/ProjectsPageIT.xml
Labels: UI
