Repository phac-nml/irida, pull requests merged in 2022-02, with the labels that each got.

#1188 Updated run script to ignore yarn
  CHANGELOG.md
  doc/developer/setup/index.md
  run.sh
Labels: developer

#1166 Metadata field security no projects alert
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/ProjectRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/ProjectServiceImpl.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/projects/project_samples.html
  src/main/webapp/resources/js/pages/projects/share/ShareMetadata.jsx
  src/main/webapp/resources/js/pages/projects/share/ShareProject.jsx
  src/main/webapp/resources/js/pages/projects/share/TargetMetadataRestriction.jsx
  src/main/webapp/resources/js/pages/projects/share/index.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ShareSamplesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectShareSamplesIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectSamplesControllerTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/ProjectServiceImplIT.xml
Labels: UI

#1184 Sample details refactor/ file concat
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/samples/samples.js
  src/main/webapp/resources/js/components/samples/components/SampleFileContenate.jsx
  src/main/webapp/resources/js/components/samples/components/SampleFileList.jsx
  src/main/webapp/resources/js/components/samples/components/SampleFiles.jsx
  src/main/webapp/resources/js/components/samples/components/SampleMetadata.jsx
  src/main/webapp/resources/js/components/samples/sampleFilesSlice.js
  src/main/webapp/resources/js/components/sequence-files/PairedFileRenderer.jsx
  src/main/webapp/resources/js/components/sequence-files/SequenceFileDetailsRenderer.jsx
  src/main/webapp/resources/js/components/sequence-files/SequenceFileHeader.jsx
  src/main/webapp/resources/js/components/sequence-files/SequenceFileHeaderOwner.jsx
  src/main/webapp/resources/js/components/sequence-files/SingleEndFileRenderer.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/AbstractIridaUIITChromeDriver.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/CartPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/SampleDetailsViewer.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/cart/CartPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/samples/SamplesAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UISampleServiceTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/CartView.xml
Labels: enhancement, UI

#1193 Yarn updates
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: dependencies

#1195 Metada field security sharing docs
  doc/_includes/tutorials/common/samples/copy-samples.md
  doc/images/tutorials/common/samples/share-destination.png
  doc/images/tutorials/common/samples/share-locked-sample.png
  doc/images/tutorials/common/samples/share-metadata-current.png
  doc/images/tutorials/common/samples/share-metadata-exists.png
  doc/images/tutorials/common/samples/share-metadata.png
  doc/images/tutorials/common/samples/share-page.png
  doc/images/tutorials/common/samples/share-sample.png
  src/main/webapp/resources/js/pages/projects/share/ShareMetadata.jsx
Labels: UI, documentation

#1152 Update create remote client
  CHANGELOG.md
  doc/user/administrator/images/add-api.png
  doc/user/administrator/images/create-api-details.png
  doc/user/administrator/images/remote-api-side-menu.png
  doc/user/administrator/images/remove-api.png
  doc/user/administrator/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/RemoteAPIAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/ajax/AjaxFormErrorResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/oauth/RemoteAPIController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/rempoteapi/dto/RemoteAPITableAdminModel.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/remote_apis/create.html
  src/main/webapp/pages/remote_apis/list.html
  src/main/webapp/resources/js/pages/admin/components/Admin.jsx
  src/main/webapp/resources/js/pages/admin/components/remote-connections/AdminRemoteApiPage.jsx
  src/main/webapp/resources/js/pages/admin/components/remote-connections/RemoteApiStatus.jsx
  src/main/webapp/resources/js/pages/admin/components/remote-connections/RemoteApiTable.jsx
  src/main/webapp/resources/js/pages/admin/components/remote-connections/RemoteConnectionDetails.jsx
  src/main/webapp/resources/js/pages/remote-apis/CreateRemoteApiModal.jsx
  src/main/webapp/resources/js/pages/remote-apis/RemoteApiPage.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/clients/CreateClientPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/remoteapi/CreateRemoteAPIPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/remoteapi/RemoteAPIsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectRemoteSettingsIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/remoteapi/CreateRemoteAPIPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/remoteapi/RemoteAPIDetailsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/remoteapi/RemoteAPIsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/utilities/RemoteApiUtilities.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/RemoteAPIAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/RemoteAPIControllerTest.java
Labels: UI
