Repository phac-nml/irida, pull requests merged in 2022-08, with the labels that each got.

#1346 Fixes issue when filtering by file with a windows encoded text file.
  CHANGELOG.md
  src/main/webapp/resources/js/pages/projects/samples/components/FilterByFileModal.jsx
  src/main/webapp/resources/js/pages/projects/samples/components/SamplesMenu.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesView.xml
  src/test/resources/files/filter-by-file/sample-filter-windows.txt
  src/test/resources/files/filter-by-file/sample-names-with-associated.txt
  src/test/resources/files/filter-by-file/sample-names.txt
  src/test/resources/files/sampleNamesForFilter.txt
Labels: bug, UI

#1348 Fix delete project
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/project/Project.java
  src/main/resources/ca/corefacility/bioinformatics/irida/sql/required-data.sql
  src/main/webapp/resources/js/pages/projects/settings/components/DeleteProject.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectDeletePage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectDeletePageIT.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/ProjectsPageIT.xml
Labels: bug

#1352 Displaying identifiers for project drop downs
  CHANGELOG.md
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/components/selects/SearchByNameAndIdSelect.tsx
  src/main/webapp/resources/js/pages/projects/share/ShareProject.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ShareSamplesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectShareSamplesIT.java
Labels: UI

#1357 Fixes issue where sample selection is not maintained between table pages.
  src/main/webapp/resources/js/pages/projects/redux/samplesSlice.js
  src/main/webapp/resources/js/pages/projects/samples/components/SamplesTable.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
Labels: bug, UI
