Repository phac-nml/irida, pull requests merged in 2022-10, with the labels that each got.

#1374 Sample details refactor/ cleanup
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/sequencingRuns/dto/SequenceFileDetails.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISequencingRunService.java
  src/main/resources/ca/corefacility/bioinformatics/irida/sql/required-data.sql
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/projects/export/_base.html
  src/main/webapp/pages/projects/export/admin.html
  src/main/webapp/pages/projects/export/list.html
  src/main/webapp/pages/projects/export/ncbi.html
  src/main/webapp/pages/samples/_base.html
  src/main/webapp/pages/samples/sample.html
  src/main/webapp/pages/samples/sample_edit.html
  src/main/webapp/pages/samples/sample_files.html
  src/main/webapp/pages/samples/sample_files_concatenate.html
  src/main/webapp/pages/templates/_file.utils.html
  src/main/webapp/pages/templates/_sequenceFile.html
  src/main/webapp/resources/css/pages/sample-edit.css
  src/main/webapp/resources/css/pages/sample-files.css
  src/main/webapp/resources/js/apis/files/files.js
  src/main/webapp/resources/js/components/files/FileUploader.jsx
  src/main/webapp/resources/js/components/files/UploadProgressNotification.js
  src/main/webapp/resources/js/components/files/file-upload-utilities.js
  src/main/webapp/resources/js/components/sample/SampleFileUploader.jsx
  src/main/webapp/resources/js/components/sample/SampleMenuBar.jsx
  src/main/webapp/resources/js/pages/SamplePage.jsx
  src/main/webapp/resources/js/pages/samples/sample-edit.js
  src/main/webapp/resources/js/pages/samples/sample-files-concatenate.js
  src/main/webapp/resources/js/pages/samples/sample-files.js
  src/main/webapp/resources/js/pages/sequencing-runs/components/SequencingRunDetailsPage.jsx
  src/main/webapp/resources/js/pages/sequencing-runs/store.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/samples/SampleDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/samples/SampleEditPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/samples/SampleFilesConcatenatePage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/samples/SampleFilesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/samples/SampleDetailsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/samples/SampleEditPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/samples/SampleFilesConcatenatePageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/samples/SampleFilesPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/samples/SamplesControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UISequencingRunServiceTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/sequencingRuns/SequencingRunsPagesIT.xml
Labels: back-end, developer

#1376 Sample details refactor fixes
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java
  src/main/webapp/resources/js/pages/sequencing-runs/components/SequencingRunDetailsPage.jsx
Labels: back-end

#1377 Fixed analysis results manage results
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysisDetails.java
  src/main/webapp/resources/js/contexts/AnalysisDetailsContext.js
  src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisShare.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisDetailsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysisAjaxControllerTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAdminView.xml
Labels: bug, UI

#1389 Added missing images for NCBI Exports documentation
  doc/_includes/tutorials/common/ncbi-export.md
  doc/images/tutorials/common/ncbi-export/ncbi-export-default-sample-settings.png
  doc/images/tutorials/common/ncbi-export/ncbi-export-sample-validation.png
Labels: documentation
