Repository phac-nml/irida, pull requests merged in 2022-05, with the labels that each got.

#1264 Fixed line list loading
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/LineListController.java
  src/main/webapp/resources/js/pages/projects/linelist/components/Table/Table.jsx
Labels: bug, UI, back-end

#1266 Fix project subscriptions changeset
  src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/22.05/user-account-project-subscription.xml
Labels: bug

#1269 Fix linelist create template
  src/main/webapp/resources/js/pages/projects/linelist/components/Table/Table.jsx
  src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/SaveTemplateModal.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectLineListPage.java
Labels: bug, UI

#1267 Fix size of user account icon in the main navigation
  src/main/webapp/resources/js/components/Header/MainNavigation.jsx
Labels: bug, UI

#1271 Fix excel numeric columns
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/utilities/FileUtilities.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/dto/ExcelCol.java
  src/main/webapp/resources/js/pages/analysis/components/AnalysisExcelPreview.jsx
Labels: UI

#1279 Antd activation & forgot/reset password
  CHANGELOG.md
  doc/developer/interface/custom-login/index.md
  doc/user/user/login/images/create-password.png
  doc/user/user/login/images/irida-activate-account-page.png
  doc/user/user/login/images/irida-login-activate-account.png
  doc/user/user/login/images/irida-login-password-reset.png
  doc/user/user/login/images/irida-login.png
  doc/user/user/login/images/irida-password-updated.png
  doc/user/user/login/images/password-reset-confirm.png
  doc/user/user/login/images/password-reset.png
  doc/user/user/login/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaWebSecurityConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/security/CredentialsExpriredAuthenticationFailureHandler.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/PasswordResetAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/PasswordResetController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/UserPasswordResetDetails.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/login/LoginController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/login/PasswordResetAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/login/PasswordResetController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPasswordResetService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIUsersService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/users/UsersAjaxController.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/pages/password/activate.html
  src/main/webapp/pages/password/create_password_reset.html
  src/main/webapp/pages/password/password_reset.html
  src/main/webapp/pages/password/password_reset_success.html
  src/main/webapp/pages/password/reset_created.html
  src/main/webapp/resources/js/apis/password-reset.js
  src/main/webapp/resources/js/apis/passwordReset.js
  src/main/webapp/resources/js/apis/users/users.js
  src/main/webapp/resources/js/components/icons/Icons.jsx
  src/main/webapp/resources/js/pages/LoginPage.jsx
  src/main/webapp/resources/js/pages/password/ActivateAccount.jsx
  src/main/webapp/resources/js/pages/password/ForgotPassword.jsx
  src/main/webapp/resources/js/pages/password/PasswordReset.jsx
  src/main/webapp/resources/js/pages/password/store.js
  src/main/webapp/resources/js/pages/store.js
  src/main/webapp/resources/js/pages/user/components/UserResetPasswordLink.jsx
  src/main/webapp/resources/js/pages/user/store.js
  src/main/webapp/resources/js/utilities/url-utilities.js
  src/main/webapp/resources/js/utilities/validation-utilities.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/LoginPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/user/ActivateAccountPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/user/CreatePasswordResetPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/user/PasswordResetPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/users/ActivateAccountPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/users/CreatePasswordResetPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/users/PasswordResetPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/LoginControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/PasswordResetControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIPasswordResetServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIUsersServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/PasswordResetAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/users/UsersAjaxControllerTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/ActivateAccountPageIT.xml
Labels: UI, test, back-end, documentation
