Repository phac-nml/irida, pull requests merged in 2022-12, with the labels that each got.

#1420 Removed old reference to `vendor` bundle and external jQuery in webpack
  src/main/webapp/entries.js
  src/main/webapp/package.json
  src/main/webapp/pages/remote_apis/parent_reload.html
  src/main/webapp/pages/template/base.html
  src/main/webapp/pages/template/page.html
  src/main/webapp/pnpm-lock.yaml
  src/main/webapp/resources/css/app.css
  src/main/webapp/resources/js/components/Header/MainNavigation/MainNavigation.css
  src/main/webapp/resources/js/pages/analysis/common/AnalysisSteps.jsx
  src/main/webapp/resources/js/styles/break-points.js
  src/main/webapp/resources/js/utilities/bootstrap-utilities.js
  src/main/webapp/resources/js/vendors.js
  src/main/webapp/webpack.config.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/AbstractPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/utilities/Ajax.java
Labels: UI, developer, dependencies

#1421 Project SPA: Update to main navigation
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/DashboardController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/SPAController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/CurrentUser.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/announcements/AnnouncementAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAnnouncementsService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/entries.js
  src/main/webapp/package.json
  src/main/webapp/pages/dashboard.html
  src/main/webapp/pages/index.html
  src/main/webapp/pages/template/page.html
  src/main/webapp/pnpm-lock.yaml
  src/main/webapp/resources/js/components/Header/MainNavigation/MainNavigation.css
  src/main/webapp/resources/js/components/Header/MainNavigation/MainNavigation.jsx
  src/main/webapp/resources/js/components/Header/MainNavigation/components/AnnouncementsSubMenu.jsx
  src/main/webapp/resources/js/components/Header/MainNavigation/components/CartLink.jsx
  src/main/webapp/resources/js/components/Header/MainNavigation/components/GlobalSearch.css
  src/main/webapp/resources/js/components/Header/MainNavigation/components/GlobalSearch.jsx
  src/main/webapp/resources/js/components/Header/MainNavigation/index.js
  src/main/webapp/resources/js/components/Header/PageHeader.jsx
  src/main/webapp/resources/js/components/ant.design/menu-utilities.tsx
  src/main/webapp/resources/js/components/main-navigation/components/AnnouncementLink.tsx
  src/main/webapp/resources/js/components/main-navigation/components/CartLink.tsx
  src/main/webapp/resources/js/components/main-navigation/components/CurrentUser.tsx
  src/main/webapp/resources/js/components/main-navigation/components/GlobalSearch.tsx
  src/main/webapp/resources/js/components/main-navigation/index.css
  src/main/webapp/resources/js/components/main-navigation/index.tsx
  src/main/webapp/resources/js/data/routes.ts
  src/main/webapp/resources/js/index.tsx
  src/main/webapp/resources/js/pages/projects/ProjectSPA.tsx
  src/main/webapp/resources/js/redux/endpoints/announcements.ts
  src/main/webapp/resources/js/redux/endpoints/api.ts
  src/main/webapp/resources/js/redux/endpoints/cart.ts
  src/main/webapp/resources/js/redux/endpoints/tags.ts
  src/main/webapp/resources/js/redux/endpoints/user.ts
  src/main/webapp/resources/js/redux/store.ts
  src/main/webapp/resources/js/types/ant-design/index.d.ts
  src/main/webapp/resources/js/types/irida/index.d.ts
  src/main/webapp/resources/js/utilities/url-utilities.ts
  src/main/webapp/resources/vendor/datatables/select.bootstrap.css
Labels: UI, feature

#1423 Project spa navigation
  src/main/webapp/resources/js/components/project/project-navigation.tsx
  src/main/webapp/resources/js/index.tsx
  src/main/webapp/resources/js/layouts/app-layout.tsx
  src/main/webapp/resources/js/layouts/project-layout.tsx
  src/main/webapp/resources/js/redux/endpoints/project.ts
  src/main/webapp/resources/js/redux/endpoints/tags.ts
Labels: UI, feature

#1426 Removed unused Select2Utility file
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/Select2Utility.java
Labels: test

#1422 Removed old view handlers
  src/main/java/ca/corefacility/bioinformatics/irida/config/web/IridaUIWebConfig.java
Labels: UI, developer

#1388 Object store/ aws testing
  .github/workflows/ci-test.yml
  build.gradle.kts
  run-tests.sh
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageAwsUtilityImpl.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/cloud/IridaFileStorageAwsUtilityTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/cloud/IridaFileStorageTestUtility.java
Labels: test

#1433 HOTFIX: display synchronize new remote project url errors
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/exceptions/IridaOAuthException.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/remote/resttemplate/IridaOAuthErrorHandler.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/RemoteAPIAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIRemoteAPIService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/remote-api/remote-api.js
  src/main/webapp/resources/js/components/remote-api/CreateRemoteProjectSyncForm.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSyncPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/remoteapi/RemoteAPIsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSyncPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIRemoteAPIServiceTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/ProjectsPageIT.xml
Labels: bug, UI

#1391 Object store/ UI fixes
  src/main/java/ca/corefacility/bioinformatics/irida/processing/concatenate/impl/SequenceFilePairConcatenator.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageLocalUtilityImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/dto/SampleConcatenationModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/pages/samples/sample_files.html
  src/main/webapp/resources/js/apis/samples/samples.ts
  src/main/webapp/resources/js/components/alerts/ErrorAlert.tsx
  src/main/webapp/resources/js/components/samples/components/SampleFileContenate.tsx
  src/main/webapp/resources/js/components/samples/components/SampleFileList.tsx
  src/main/webapp/resources/js/components/samples/components/SampleFiles.tsx
  src/main/webapp/resources/js/components/samples/sampleFilesSlice.ts
  src/main/webapp/resources/js/pages/analysis/components/AnalysisBioHansel.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/CartPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/SampleDetailsViewer.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/samples/SamplesAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UISampleServiceTest.java
Labels: UI

#1439 HOTFIX: Fixed issue with export file and instrument model using the NCBI Exporter
  CHANGELOG.md
  src/main/webapp/resources/js/pages/projects/ncbi/create/CreateNcbiExport.tsx
  src/main/webapp/resources/js/pages/projects/ncbi/create/CreateNcbiSampleDetails.tsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/NcbiExportPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/NcbiExportPageIT.java
Labels: bug, critical, javascript
