Repository phac-nml/irida, pull requests merged in 2022-09, with the labels that each got.

#1356 Fix parameter null values
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/exceptions/pipelines/MissingRequiredParametersException.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/ui/InputWithOptions.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/launchPipeline/LaunchAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineStartService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/pipelines/pipelines.js
  src/main/webapp/resources/js/components/form/InputWithOptions.jsx
  src/main/webapp/resources/js/pages/launch/LaunchForm.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/cart/CartPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/pipelines/LaunchPipelinePage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pipelines/BioHanselPipelinePageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIPipelineStartServiceTest.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/pipelines/BioHanselPipelinePageIT.xml
Labels: UI

#1353 Unify validate sample names
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/SampleRepository.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/ProjectSamplesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/dto/ValidateSampleNameModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/dto/ValidateSampleNamesRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/dto/ValidateSampleNamesResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/dto/SampleNameCheckRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/dto/SampleNameCheckResponse.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/dto/ValidSample.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectSampleService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/SampleServiceImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/sample/SampleService.java
  src/main/webapp/resources/js/apis/projects/samples.ts
  src/main/webapp/resources/js/pages/projects/samples/components/FilterByFileModal.jsx
  src/main/webapp/resources/js/pages/projects/samples/index.js
  src/main/webapp/resources/js/pages/projects/share/index.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
Labels: developer

#1326 Sample details refactor/ single end default
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/components/samples/components/SampleFileContenate.tsx
  src/main/webapp/resources/js/components/samples/components/SequencingObjectList.tsx
  src/main/webapp/resources/js/components/sequence-files/SequenceObjectListItem.tsx
  src/main/webapp/resources/js/pages/launch/LaunchFiles.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/CartPageIT.java
Labels: UI

#1359 Add description and metadata to create & update project sample endpoints
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/CreateSampleRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/FieldUpdate.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/UpdateSampleRequest.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/ProjectSamplesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectSampleService.java
  src/main/resources/i18n/messages.properties
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIProjectSampleServiceTest.java
Labels: developer

#1361 Sample details refactor/ add automated assembly
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/dto/SampleSequencingObjectFileModel.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/samples/samples.ts
  src/main/webapp/resources/js/components/menu/EllipsisMenu.tsx
  src/main/webapp/resources/js/components/samples/SampleDetailViewer.tsx
  src/main/webapp/resources/js/components/samples/components/GenomeAssemblyList.tsx
  src/main/webapp/resources/js/components/samples/components/SampleFiles.tsx
  src/main/webapp/resources/js/components/samples/components/SequencingObjectList.tsx
  src/main/webapp/resources/js/components/samples/sampleFilesSlice.ts
  src/main/webapp/resources/js/components/sequence-files/SequenceObjectListItem.tsx
  src/main/webapp/resources/js/hooks/useInterval.ts
  src/main/webapp/resources/js/pages/cart/components/CartSamples.jsx
  src/main/webapp/resources/js/pages/cart/components/SampleRenderer.jsx
  src/main/webapp/resources/js/types/irida/index.d.ts
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/CartPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/SampleDetailsViewer.java
Labels: UI

#1365 Added functionality to cancel axios requests for uploading files
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/requests.ts
  src/main/webapp/resources/js/components/samples/SampleDetailViewer.tsx
  src/main/webapp/resources/js/components/samples/components/SampleFiles.tsx
  src/main/webapp/resources/js/components/samples/sampleFilesSlice.ts
Labels: UI

#1366 Sample details refactor/ documentation
  doc/_includes/tutorials/common/samples/download-sequence-file.md
  doc/_includes/tutorials/common/samples/view-individual-sample.md
  doc/_includes/tutorials/common/samples/view-sequence-files.md
  doc/_includes/tutorials/common/uploading-sample-files.md
  doc/images/tutorials/common/samples/ellipsis-menu.png
  doc/images/tutorials/common/samples/fastqc-charts.png
  doc/images/tutorials/common/samples/fastqc-details.png
  doc/images/tutorials/common/samples/fastqc-overrepresented.png
  doc/images/tutorials/common/samples/sample-detail-viewer-files-tab.png
  doc/images/tutorials/common/samples/sample-detail-viewer-files-upload-btn.png
  doc/images/tutorials/common/samples/sample-detail-viewer-upload-cancel-btn.png
  doc/images/tutorials/common/samples/sample-detail-viewer.png
  doc/images/tutorials/common/samples/sample-sequence-file-paired-end.png
  doc/images/tutorials/common/samples/sample-sequence-file-single-end.png
  doc/images/tutorials/common/samples/sequence-file-concatenate-modal.png
  doc/images/tutorials/common/samples/sequence-file-concatenate-warning.png
  doc/images/tutorials/common/samples/sequence-file-concatenate.png
  doc/images/tutorials/common/samples/sequence-file-qc.png
  doc/images/tutorials/common/samples/upload-sample-progress-cancel.png
  doc/user/user/sample-metadata/images/sample-detail-viewer-metadata.png
  doc/user/user/sample-metadata/index.md
  doc/user/user/samples/images/automated-assembly.png
  doc/user/user/samples/images/ellipsis-menu.png
  doc/user/user/samples/images/sample-contained-files.png
  doc/user/user/samples/images/sample-details-edit-btn.png
  doc/user/user/samples/images/sample-details-edit.png
  doc/user/user/samples/index.md
  src/main/webapp/resources/js/components/samples/components/SampleInfo.tsx
Labels: documentation
