Repository phac-nml/irida, pull requests merged in 2022-04, with the labels that each got.

#1235 Allow arbitrary text for organism
  CHANGELOG.md
  src/main/webapp/resources/js/components/ant.design/EditableParagraph.jsx
  src/main/webapp/resources/js/components/ontology/OntologyInput.jsx
  src/main/webapp/resources/js/components/ontology/index.js
  src/main/webapp/resources/js/pages/projects/create/CreateProjectDetails.jsx
  src/main/webapp/resources/js/pages/projects/samples/add-sample/AddSampleButton.jsx
  src/main/webapp/resources/js/pages/projects/settings/components/ProjectDetails.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/CreateProjectComponent.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectDetailsPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/CreateProjectIT.java
Labels: bug, UI

#1236 Fix flaky tests on Project Members Page
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java
Labels: test

#1233 Updated to display page size selector
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/tables/TableRequest.java
  src/main/webapp/resources/js/components/analyses-outputs/SingleSampleAnalysisOutputs.jsx
  src/main/webapp/resources/js/components/ant.design/PagedTable/PagedTableContext.js
  src/main/webapp/resources/js/components/ncbi/export-table/NcbiExportTable.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupMembersTable.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupProjectsTable.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisExcelPreview.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisTabularPreview.jsx
  src/main/webapp/resources/js/pages/projects/list/ProjectsTable.jsx
  src/main/webapp/resources/js/pages/projects/settings/components/ReferenceFiles.jsx
  src/main/webapp/resources/js/pages/projects/settings/components/associated/ViewAssociatedProjects.jsx
  src/main/webapp/resources/js/pages/sequence-files/components/OverRepresentedSequences.jsx
  src/main/webapp/resources/js/utilities/antdesign-table-utilities.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/RemoteAPIAjaxControllerTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIUserGroupsServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/announcements/AnnouncementsAjaxControllerTest.java
Labels: UI

#1232 Update metadata/project role update notifications
  pom.xml
  src/main/java/ca/corefacility/bioinformatics/irida/constraints/MetadataRoleValidate.java
  src/main/java/ca/corefacility/bioinformatics/irida/constraints/impl/ProjectMetadataRoleValidator.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/joins/impl/ProjectUserJoin.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/user/group/UserGroupProjectJoin.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/ProjectMembersAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/ProjectUserGroupsAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/exceptions/UIConstraintViolationException.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectMembersService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectUserGroupsService.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/utilities/ExceptionUtilities.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/ProjectService.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/impl/ProjectServiceImpl.java
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/apis/projects/members.js
  src/main/webapp/resources/js/apis/projects/user-groups.js
  src/main/webapp/resources/js/components/Buttons/AddMemberButton.jsx
  src/main/webapp/resources/js/components/Buttons/RemoveTableItemButton.jsx
  src/main/webapp/resources/js/components/ant.design/PagedTable/PagedTableContext.js
  src/main/webapp/resources/js/components/project-members/ProjectMembersTable.jsx
  src/main/webapp/resources/js/components/project-user-groups/AddGroupButton.jsx
  src/main/webapp/resources/js/components/project-user-groups/ProjectUserGroupsTable.jsx
  src/main/webapp/resources/js/components/roles/RoleSelect.jsx
  src/main/webapp/resources/js/pages/UserGroupsPage/index.js
  src/test/java/ca/corefacility/bioinformatics/irida/model/ProjectUserJoinTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/model/UserGroupProjectJoinTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIProjectMembersServiceTest.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIProjectUserGroupServiceTest.java
Labels: bug, UI

#1255 Updated launch page reference file upload error message
  CHANGELOG.md
  doc/user/user/pipelines/images/reference-file-invalid.png
  doc/user/user/pipelines/index.md
  doc/user/user/project/images/reference-file-invalid.png
  doc/user/user/project/index.md
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/pages/launch/references/UploadReferenceFile.jsx
  src/main/webapp/resources/js/pages/projects/settings/components/ReferenceFiles.jsx
Labels: bug, UI
