Repository phac-nml/irida, pull requests merged in 2022-01, with the labels that each got.

#1153 Update to yarn 3 & browserlist
  CHANGELOG.md
  pom.xml
  src/main/webapp/.yarn/releases/yarn-2.4.1.cjs
  src/main/webapp/.yarn/releases/yarn-3.1.1.cjs
  src/main/webapp/.yarnrc.yml
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: dependencies

#1164 Zipped html support
  CHANGELOG.md
  doc/user/user/pipelines/images/view-results-html-quast-html.png
  doc/user/user/pipelines/index.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/AnalysisOutputFile.java
  src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/ProjectSampleAnalysisOutputInfo.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/analysis/submission/AnalysisSubmissionRepositoryImpl.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/utilities/FileUtilities.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java
  src/main/java/ca/corefacility/bioinformatics/irida/service/analysis/workspace/galaxy/AnalysisWorkspaceServiceGalaxy.java
  src/main/webapp/resources/js/components/analyses-outputs/SingleSampleAnalysisOutputs.jsx
  src/main/webapp/resources/js/contexts/AnalysisOutputsContext.js
  src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/utilities/FileUtilitiesTest.java
  src/test/resources/files/snp_tree.tree.zip
Labels: enhancement, UI

#1170 Update and Cleanup JS Dependencies
  src/main/webapp/package.json
  src/main/webapp/yarn.lock
Labels: dependencies, javascript

#1174 Main navigation
  src/main/resources/i18n/messages.properties
  src/main/webapp/resources/js/components/Header/MainNavigation.jsx
  src/main/webapp/resources/js/components/Header/main-navigation/components/AnnouncementsSubMenu.jsx
  src/main/webapp/resources/js/components/Header/main-navigation/components/CartLink.jsx
  src/main/webapp/resources/js/components/Header/main-navigation/components/GlobalSearch.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/AbstractPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/cart/CartPage.java
Labels: bug, UI

#1175 Analysis tree output fix
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/UpdatedAnalysisProgress.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
  src/main/webapp/resources/js/contexts/AnalysisContext.js
  src/main/webapp/resources/js/pages/analysis/AnalysisCompletePage.jsx
  src/main/webapp/resources/js/pages/analysis/AnalysisErrorPage.jsx
  src/main/webapp/resources/js/pages/analysis/AnalysisRunningPage.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisError.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisMenu.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisSettings.jsx
  src/main/webapp/resources/js/pages/analysis/components/AnalysisSistr.jsx
  src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisDetails.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisDetailsPageIT.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java
Labels: UI

#1176 React router update for sequence files
  src/main/webapp/resources/js/pages/sequence-files/components/FastQC.jsx
  src/main/webapp/resources/js/pages/sequence-files/components/FastQCCharts.jsx
  src/main/webapp/resources/js/pages/sequence-files/index.js
Labels: UI, developer, dependencies

#1177 React router cart tools
  src/main/webapp/resources/js/pages/cart/components/CartTools.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/cart/CartPage.java
Labels: UI, developer, dependencies

#1178 React router project analyses
  CHANGELOG.md
  src/main/webapp/package.json
  src/main/webapp/resources/js/pages/projects/project-analyses/components/AnalysesNav.jsx
  src/main/webapp/resources/js/pages/projects/project-analyses/components/AutomatedSingleSampleAnalysisOutputs.jsx
  src/main/webapp/resources/js/pages/projects/project-analyses/components/ProjectAnalysesPage.jsx
  src/main/webapp/resources/js/pages/projects/project-analyses/components/SharedSingleSampleAnalysisOutputs.jsx
  src/main/webapp/resources/js/pages/projects/project-analyses/index.js
  src/main/webapp/yarn.lock
Labels: UI, developer, dependencies
