Repository phac-nml/irida, pull requests merged in 2023-02, with the labels that each got.

#1457 Fix for updating sample modified date when metadata is deleted
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java
  src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java
  src/main/webapp/resources/js/apis/samples/samples.ts
  src/main/webapp/resources/js/components/samples/components/SampleMetadata.tsx
Labels: bug

#1462 Fixed sample details viewer files display
  src/main/webapp/resources/js/components/samples/components/SampleFiles.tsx
  src/main/webapp/resources/js/components/samples/sampleFilesSlice.ts
Labels: bug, UI

#1463 Aws local emulator
  doc/developer/setup/index.md
  run-tests.sh
  src/main/java/ca/corefacility/bioinformatics/irida/config/repository/IridaApiFilesystemRepositoryConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/config/services/IridaApiServicesConfig.java
  src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageAwsUtilityImpl.java
  src/main/resources/ca/corefacility/bioinformatics/irida/config/filesystem.properties
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/cloud/IridaFileStorageAwsUtilityTest.java
Labels: back-end, developer

#1467 Fix remove sample error
  CHANGELOG.md
  src/main/java/ca/corefacility/bioinformatics/irida/model/sample/Sample.java
  src/main/webapp/resources/js/pages/projects/samples/components/RemoveModal.jsx
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
  src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
  src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesPage.xml
Labels: bug, critical
